### ISSUE TITLE
[Bug]: caching breaks ft_highlights

### ISSUE THREAD

**Issue by mmirus** [olimorris/onedarkpro.nvim#100]
### Your OneDarkPro config

```lua
local onedarkpro = require("onedarkpro")

onedarkpro.setup({
  caching = true,
  ft_highlights = {
    markdown = {
      TSTitle = { fg = "${red}", style = "bold" },
    },
  },
})

vim.cmd("colorscheme onedarkpro")

```

### Error messages

N/A

### Expected

ft_highlights should be applied when cache is loaded.

### Actual

ft_highlights are not applied when cache is loaded.

### Reproduce the bug

I was not able to verify this with the minimal config, since caching breaks highlighting on it entirely. Instead, I just pared down my theme config to the smallest size possible.

1. Disable caching
2. Define at least one ft_highlight in your config
3. Reload
4. View a file where the ft_highlight is applied to confirm it's working
5. Enable caching
6. Reload
7. View the same file

https://user-images.githubusercontent.com/524994/193854845-10da3569-b30b-490c-b57c-9449182d7f7c.mp4

Note: using a non-ft_highlight like `["@text.title.markdown"]` does not have this problem. Unfortunately, it seems like some highlight groups may not be available using that syntax, so I can't move fully over yet. (Or perhaps I'm doing something wrong.) Example: the ft_highlight `      TSLiteral = { fg = "${green}" }` works (when caching is disabled) for styling `inline code blocks`, but the regular highlight `["@text.literal.markdown"] = { fg = "${green}" }` does not.

### Final checks

- [X] I have made sure that the colorscheme's caching is not the issue
- [X] I have made sure this is not a duplicate issue
- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`

**Comment by olimorris** [comment]
Thanks so much for flagging @mmirus.

This is a planned (yet undocumented) omission. I'm planning on revamping the filetype highlights in the next day or two. I've come to the realisation that Treesitter's support for filetype highlights is way more performant and reliable than the current implementation.

**Comment by mmirus** [comment]
Sounds good! I thought that might be the case. In that case, we can consider this closed if you like!

One similar thing I'm seeing is that caching also seems to break some custom Telescope highlights (non-ft_highlight). Should I create a new issue for that?

https://user-images.githubusercontent.com/524994/193860680-92465773-f436-4430-8053-7a477e582a8b.mp4

**Comment by olimorris** [comment]
I noticed there was some weird telescope irregularities too. Do they disappear if you turn off the telescope from the plugins section?

**Comment by mmirus** [comment]
Good suggestion! Yes, it seems that is the case:

https://user-images.githubusercontent.com/524994/193862012-d011eda4-f76c-4adf-a73e-356023e05b9c.mp4

Possibly it's the order of the cache file? Custom highlights may need to be written after built-in highlights?

**Comment by mmirus** [comment]
I did this as a test:

```lua
-- in my config...
TelescopeBorder = { bg = "${float_bg}", fg = "${float_bg}", style = "bold" },
```

I added bold as a way to identify which line in the cache comes from me.

Here are the `TelescopeBorder` lines in the cache:

```lua
vim.cmd("highlight TelescopeBorder guifg=#22252C guibg=#22252C gui=bold guisp=NONE blend=NONE")
vim.cmd("highlight TelescopeBorder guifg=#5c6370 guibg=#22252C gui=NONE guisp=NONE blend=NONE")
vim.cmd("highlight! link TelescopePreviewBorder TelescopeBorder")
vim.cmd("highlight! link TelescopePromptBorder TelescopeBorder")
```

You can see the bold one comes first.

**Comment by olimorris** [comment]
Funny that I came across the ordering separately just now too. Removing `table.sort` from the cache file will do it.

**Comment by mmirus** [comment]
Seems like it! Thanks!
