### ISSUE TITLE
[Bug]: Invalid caracter colors/onedarkpro.vim in line 3

### ISSUE THREAD

**Issue by Fedex159** [olimorris/onedarkpro.nvim#104]
### Your OneDarkPro config

```
local status, onedarkpro = pcall(require, 'onedarkpro')
if (not status) then return end

onedarkpro.setup {
  theme = 'onedark',
  styles = {
    comments = "italic",
  }
}

vim.cmd('colorscheme onedarkpro')
```
![imagen](https://user-images.githubusercontent.com/44141208/194668639-fd8f1b45-43bd-40ce-805c-fc74588041ae.png)

### System
- Fedora 36
- Kernel: 5.19.14-201.fsync.fc36.x86_64
- NVIM v0.7.2
- Gnome terminal

### Error messages

```
Se ha detectado un error al procesar /tmp/onedarkpro/pack/packer/start/onedarkpro.nvim/colors/onedarkpro.vim:
línea    3
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
W18: Hay un carácter no válido en el nombre del grupo
```
![imagen](https://user-images.githubusercontent.com/44141208/194668300-d7c4f065-3623-4747-87a3-ac624e5687a3.png)

### Describe the bug

When you open nvim with minimal config, you can see this error, the error don't affect the normal functionality for the plugin, but is shows everytime you open nvim.

Solution:
Go back to this commit `24ab2c8d5e29f31f5b00e5bd529fcefb65178e99` and the error don't shows.

### Reproduce the bug

1. Open Nvim with minimal config.
2. Check log message in screen

### Final checks

- [X] I have made sure that the colorscheme's caching is not the issue
- [X] I have made sure this is not a duplicate issue
- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`

**Comment by olimorris** [comment]
Hi @Fedex159. I've tried reproducing with the `minimal.lua` file and I can't recreate this.

What if you remove the `styles` table from the config?

**Comment by Fedex159** [comment]
> Hi @Fedex159. I've tried reproducing with the `minimal.lua` file and I can't recreate this.
> 
> What if you remove the `styles` table from the config?

Hi @olimorris , here I recorded a video, is the same. The theme like I say, work fine, I don't know what is generating this error, maybe is some my system config?, or maybe for use my system in Spanish?.

[Video error](https://user-images.githubusercontent.com/44141208/194712557-af4b8f37-9e32-4823-83f1-45299ae9c990.webm)

**Comment by olimorris** [comment]
I'm wondering if the `italic` setting is messing things up. What if you try changing the styles to `bold`?

**Comment by Jerovich** [comment]
Hello,

Same problem here. Changing styles to bold makes no difference for me @olimorris.

@Fedex159 I've got it en English so it seems no language issue.

**Comment by olimorris** [comment]
> Hello,
> 
> Same problem here. Changing styles to bold makes no difference for me @olimorris.
> 
> @Fedex159 I've got it en English so it seems no language issue.

Are you using Neovim 0.7.2 as well?

**Comment by Jerovich** [comment]
> > Hello,
> > Same problem here. Changing styles to bold makes no difference for me @olimorris.
> > @Fedex159 I've got it en English so it seems no language issue.
> 
> Are you using Neovim 0.7.2 as well?

NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by Jerovich** [comment]
It feels like `require("onedarkpro").load()` in onedarkpro.vim is trying to load some syntax highlight groups that for any reason no longer exist, could it be?

I'm not by any means a lua expert. I'm digging a little on .lua files around but can't make a conclussion.

**Comment by olimorris** [comment]
I'm testing on `0.8` and you both are on `0.7` so I will start the investigation there

**Comment by olimorris** [comment]
Okay...got it. Most defo is a `0.7` issue. Shall work on this now.

**Comment by Jerovich** [comment]
Much appreciated! I'll stick around to make any test you may need.

**Comment by olimorris** [comment]
Thanks to @Fedex159 for pointing out the commit that caused it. Basically, `Neovim 0.7` doesn't like highlight groups defined as `["@method.call.python"]` which are integral to the filetype highlighting feature.

Apologies for the inconvenience on this!

**Comment by Jerovich** [comment]
@olimorris it completely solved it.

Many thanks for your effort and the fantastic plugin!
