### ISSUE TITLE
Need advice/help disabling coloring text based on diagnostic info

### ISSUE THREAD

**Issue by amaanq** [olimorris/onedarkpro.nvim#105]
### Issue/Question/Enhancement

Something that has been irking me is how a diagnostic warn/error will color the text with the type (red for err, yellow for warn, etc). I don't particularly like this and only want the undercurls. I noticed setting undercurl to true in the options does add the undercurls, but it does not turn off this text highlighting, here's an example:

![image](https://user-images.githubusercontent.com/29718261/194722464-f1d225ca-e7e4-4fb2-a333-4b0af39e8d3b.png)

Although it is somewhat of a false positive warning, the matter at hand is I just don't want capabilities (on the left) to be yellow in color, I want it simply to have a yellow undercurl. Let me know how to fix this, thanks!

**Comment by olimorris** [comment]
What's your LSP config which covers the styling? The `native_lsp.lua` file contains all LSP related highlight groups so you could override those

**Comment by amaanq** [comment]
I'm not sure if this is an opinionated choice on your end or a bug - if the former I would appreciate advice on how to make it so diagnostics are only undercurls :) 

Lsp config regarding diagnostics:

```lua
local M = {}

M.signs = { Error = " ", Warn = " ", Hint = " ", Info = " " }

function M.setup()
	-- Automatically update diagnostics
	vim.diagnostic.config({
		underline = true,
		update_in_insert = false,
		virtual_text = { spacing = 4, prefix = "●" },
		severity_sort = true,
	})

	vim.lsp.handlers["workspace/diagnostic/refresh"] = function(_, _, ctx)
		local ns = vim.lsp.diagnostic.get_namespace(ctx.client_id)
		pcall(vim.diagnostic.reset, ns)
		return true
	end

	-- vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
	-- 	underline = true,
	-- })

	for type, icon in pairs(M.signs) do
		local hl = "DiagnosticSign" .. type
		vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = "" })
	end
end

return M
```

**Comment by olimorris** [comment]
Have you played with overriding the highlights from `native_lsp`? It implements the highlights from `:h diagnostic`, [here](https://github.com/neovim/neovim/blob/18afacee1d98b9987391b8bdef08282fb156fa88/runtime/doc/diagnostic.txt#L176).

That should be the only way to do it. Sorry I'm not too au fait with the lsp ui beyond the defaults.

**Comment by amaanq** [comment]
Oh gotcha, using a different theme (in my case tokyo night) only shows undercurls for diagnostic info and I haven't changed my config. So I presumed it was an opinionated theme choice. I'll keep digging...

**Comment by olimorris** [comment]
Yeah just compare what Tokyo Night is doing with the LSP highlights and apply them in your config 👍🏼 .

**Comment by olimorris** [comment]
Ahhhh. So it looks like Tokyo Night uses `sp` to highlight the LSP underline highlight groups...

For you to achieve the same:

```lua
highlights = {
  DiagnosticUnderlineError = { sp = "{red}", style = "undercurl" },
  DiagnosticUnderlineWarn = { sp = "{yellow}", style = "undercurl" },
  DiagnosticUnderlineInfo = { sp = "{blue}", style = "undercurl" },
  DiagnosticUnderlineHint = { sp = "{cyan}", style = "undercurl" },
}
```
