### ISSUE TITLE
[Bug]: Weird character display in feline status bar

### ISSUE THREAD

**Issue by RayZ0rr** [olimorris/onedarkpro.nvim#106]
### Your OneDarkPro config

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/onedarkpro"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
    install_plugins = true
end

local packer = require("packer")

packer.init({
    package_root = test_dir .. "/pack",
    compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

-- install plugins
packer.startup(function(use)
    use("wbthomason/packer.nvim")
    use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
    use("olimorris/onedarkpro.nvim")
    use {
      'feline-nvim/feline.nvim',
      requires = 'kyazdani42/nvim-web-devicons',
      -- Enable for default status bar
      config = function()
          require('feline').setup()
      end
     }
--   use {
--     'ibhagwan/fzf-lua',
--     requires = {
--       'kyazdani42/nvim-web-devicons'
--     }, -- optional for icons
--   }
-- use {
--   'akinsho/bufferline.nvim',
--   requires = 'kyazdani42/nvim-web-devicons',
--   config = function()
--       require('bufferline').setup()
--   end
-- }

    -- Add any additional plugins here

    if install_plugins then
        packer.sync()
    end
end)

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
    treesitter.setup({
        ensure_installed = "all",
        ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
        highlight = { enable = true },
    })
end

-- setup onedarkpro
local ok, onedarkpro = pcall(require, "onedarkpro")
if ok then
    onedarkpro.setup({
      -- Your onedarkpro config here
    })
    vim.cmd("colorscheme onedarkpro")
end
```

### Describe the bug

Sometimes in the '_statusbar_' characters of "**^**" is displayed.****

![2022-10-10_10-23](https://user-images.githubusercontent.com/96843787/194801729-19770efb-0976-416b-9427-f2be5a880c55.png)
![2022-10-10_10-24](https://user-images.githubusercontent.com/96843787/194801735-ece61510-68d8-4bcb-bbfa-6e49fb60806a.png)
![2022-10-10_10-24_1](https://user-images.githubusercontent.com/96843787/194801742-034741d4-b222-41e4-b2d0-ac690c813ebf.png)

Demonstration without minimal rc.

https://user-images.githubusercontent.com/96843787/194801762-a020cced-2413-4683-8f0c-c3cb7c3ba5ea.mp4

### Reproduce the bug

Open nvim with the above minimal rc.

1. `nvim --clean -u minimal_onedark.lua`
2. Open any other window like with `:PackerStatus` or `:Lexplore`
3. Now changing to either of both windows, the character is displayed.

### Final checks

- [X] I have made sure that the colorscheme's caching is not the issue
- [X] I have made sure this is not a duplicate issue
- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`

**Comment by olimorris** [comment]
Try setting the `StatusLine` highlight to have a bg and fg of `NONE`. You can then override the statusline component highlights in Feline.

I experience this too and apply a blanket highlight override in my config:
```lua
highlights = {
  StatusLine = { bg = "NONE", fg = "NONE" }
}
```

For reference, this occurs because the theme has the following highlight for `StatusLine`, by default:
```lua
StatusLine = { bg = config.options.transparency and "NONE" or theme.palette.bg, fg = theme.palette.fg }
```

Also, feel free to see my [feline.nvim](https://github.com/olimorris/dotfiles/blob/main/.config/nvim/lua/Oli/plugins/statusline.lua) config for how I incorporate this theme into it.

**Comment by RayZ0rr** [comment]
Thank you for the quick response. Your dots were helpful in setting a unified theme
