### ISSUE TITLE
Possible workaround for weird neovim behavior regarding fillchars

### ISSUE THREAD

**Issue by punowo** [olimorris/onedarkpro.nvim#109]
### Issue/Question/Enhancement

Hello. 
Would it be possible to fix this bug (https://github.com/neovim/neovim/issues/19803) in onedarkpro.nvim by making the caret have the same color as the lualine background inside onedarkpro.nvim lualine theme ? 
![Screenshot 2022-10-11 at 16 31 05](https://user-images.githubusercontent.com/96526435/195120799-3fe1e2c6-2424-48a0-b799-86d0ad3eb566.png)

**Comment by olimorris** [comment]
Might be worth checking #106 and let me know if this is related.

Unless there is a highlight group OneDarkPro can color, I'd be reluctant to add anything to the plugin.

**Comment by punowo** [comment]
> Might be worth checking #106 and let me know if this is related.
> 
> Unless there is a highlight group OneDarkPro can color, I'd be reluctant to add anything to the plugin.

Yes. It's related. 
Thank you for pointing me to the other issue. I forgot I can actually configure onedarkpro.nvim using lua.
