### ISSUE TITLE
Could you generate onedarkpro theme for alacritty and kitty?

### ISSUE THREAD

**Issue by Anhelor** [olimorris/onedarkpro.nvim#11]

**Comment by Anhelor** [comment]
I use alacritty, the theme is nice for me

**Comment by olimorris** [comment]
Me too. The hot reloading of config files is amazing. I actually have `onedark` and `onelight` bundled in my [config](https://github.com/akinsho/dotfiles/blob/main/.config/alacritty/alacritty.yml) and then have a command prompt which changes from dark->light or vice versa
