### ISSUE TITLE
[Feature Request]  Add more styles options to code components

### ISSUE THREAD

**Issue by RayZ0rr** [olimorris/onedarkpro.nvim#110]
### Issue/Question/Enhancement

Current style options :

```lua
  styles = { -- Choose from "bold,italic,underline"
      strings = "NONE", -- Style that is applied to strings.
      comments = "NONE", -- Style that is applied to comments
      keywords = "NONE", -- Style that is applied to keywords
      functions = "NONE", -- Style that is applied to functions
      variables = "NONE", -- Style that is applied to variables
      virtual_text = "NONE", -- Style that is applied to virtual text
  },
```

desired one : 

```lua

    styles = {              -- Style to be applied to different syntax groups
      comments = "NONE",    -- Value is any valid attr-list value `:help attr-list`
      conditionals = "NONE",
      constants = "NONE",
      functions = "NONE",
      keywords = "NONE",
      numbers = "NONE",
      operators = "NONE",
      strings = "NONE",
      types = "NONE",
      variables = "NONE",
    },
```

List of some themes that support such settings for reference:

1. https://github.com/EdenEast/nightfox.nvim
2. https://github.com/olimorris/onedarkpro.nvim
3. https://github.com/rmehri01/onenord.nvim
4. https://github.com/catppuccin/nvim
5. https://github.com/folke/tokyonight.nvim
6. https://github.com/navarasu/onedark.nvim

**Comment by olimorris** [comment]
Great suggestion and easy to implement. I'll get on this tonight. One of those features that's so useful, I'm surprised it's not been suggested before. My hunch is that a lot of people are not actually customising OneDarkPro so aren't seeing this stuff. But thank you!

**Comment by olimorris** [comment]
@RayZ0rr I've added some more options in d74d9ba3206d87a0ee450795fa4ea5a90a49016e. Let me know what you think!

**Comment by RayZ0rr** [comment]
Looks awesome. Especially with the caching feature, everything is super smooth. Unless there are breaking changes in upstream nvim, this theme looks feature complete to me. Although I am not knowledgeable in nvim lua API so my inference might be basic.

**Comment by olimorris** [comment]
Very kind words and thank you. Always open to new enhancements, especially ones for adding new filetype highlights.

Thanks again for your suggestion.
