### ISSUE TITLE
Use (or duplicate) JavaScript highlights for TypeScript and React files

### ISSUE THREAD

**Issue by mmirus** [olimorris/onedarkpro.nvim#113]
### Issue/Question/Enhancement

Hey! It would probably make sense to have the JS highlights applied to TS, as well as javascriptreact and typescriptreact.

One way would be something like this for each of the additional permutations:

- import the base JS highlights in typescript.lua (for example)
- extend them as needed (e.g., if there are highlights for TS that JS doesn't have)

This would avoid having to redeclare all the JS highlights.

If there aren't actually any additional highlights for TS et al, then there's probably a simpler approach, and it might make sense to start there unless you already know up front that we'll need to extend/override the base ones.

What do you think?

**Comment by mmirus** [comment]
Update: seems like they actually need to be, e.g., `@variable.typescript` rather than `@variable.javascript` for TS. And from a quick test, I'm not sure there's actually a variant that works for React files? :confused:

**Comment by olimorris** [comment]
Yeah this has been on my mind for a little. I've not yet looked at how something in TypeScript is coloured vs Javascript, in VS Code. I was going to come up with a neat way of injecting a filetype into a filetype highlight template but when I figured it's likely to be just JS and TS, I'm minded to just duplicate the values in separate files. Will try and get to this, this week

**Comment by olimorris** [comment]
@mmirus could you supply some react and typescript examples when you get time and I can work on this.

**Comment by mmirus** [comment]
I will try to follow up here with some examples soon!

**Comment by mmirus** [comment]
Coming up with examples is hard but I threw a few things together based on the Vue and JavaScript examples already in the repo, with another TS example for good measure.

more modern javascriptreact (jsx) adaptation of the current JavaScript example file (which includes React code, not just vanilla JS)

```jsx
import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);
  const handleClick = () => setCount(count + 1);

  return (
    <div>
      <h1>{count}</h1>
      <button onClick={handleClick}>Change!</button>
    </div>
  );
}

```

typescriptreact (tsx) version of the same, made  a bit more complex to give room for additional types

```tsx
import React from 'react';
import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);
  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);

  return (
    <div>
      <Count count={count} />
      <Button type="decrement" onClick={decrement} />
      <Button type="increment" onClick={increment} />
    </div>
  );
}

function Count({ count }: { count: number }) {
  return (
    <h1
      style={{
        color: count < 0 ? 'red' : 'black',
      }}
    >
      The count is currently {count}
    </h1>
  );
}

interface ButtonProps {
  type: 'increment' | 'decrement';
  onClick: () => void;
}

function Button({ type, onClick }: ButtonProps) {
  const label = type === 'increment' ? 'Increment' : 'Decrement';

  return <button onClick={onClick}>{label}</button>;
}

```

typescriptreact (tsx) adaptation of the vue example file (FYI I don't know vue, so I was guessing at how it would actually convert)

```tsx
import { useState } from 'react';

interface DemoProps {
  index: number;
  value: string;
  disabled: boolean;
  isValid: boolean;
}

export function Demo({
  index = 0,
  value = 'Value',
  disabled = false,
  isValid = true,
}: DemoProps) {
  const [showDropdown, setShowDropdown] = useState(false);
  const openDropdown = () => setShowDropdown(true);
  const closeDropdown = () => setShowDropdown(false);

  const options = ['Optional', 'Mandatory'];

  return (
    <div className="relative inline-flex h-auto">
      {/* overlay */}
      {showDropdown && (
        <div
          className="fixed top-0 left-0 z-20 h-screen w-screen bg-transparent"
          onClick={closeDropdown}
        >
          &nbsp;
        </div>
      )}
      <button
        disabled={disabled}
        onClick={openDropdown}
        className={`${inputClass(
          isValid
        )} text-2xs focus:ring-purple-light inline-block h-6 w-full appearance-none overflow-hidden overflow-ellipsis whitespace-pre rounded-md border border-gray-300 bg-gray-200 px-1.5 pr-4 text-left focus:outline-none focus:ring-1 disabled:text-gray-400`}
      >
        <div className="flex items-center space-x-1">
          {!isValid && (
            <div>
              <svg
                width="4"
                height="14"
                viewBox="0 0 3 13"
                fill="currentColor"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fillRule="evenodd"
                  clipRule="evenodd"
                  d="M1.5 0C0.671573 0 0 0.671574 0 1.5V7.5C0 8.32843 0.671573 9 1.5 9C2.32843 9 3 8.32843 3 7.5V1.5C3 0.671574 2.32843 0 1.5 0ZM1.5 10C0.671573 10 0 10.6716 0 11.5C0 12.3284 0.671573 13 1.5 13C2.32843 13 3 12.3284 3 11.5C3 10.6716 2.32843 10 1.5 10Z"
                  fill="#C10707"
                />
              </svg>
            </div>
          )}
          <div className="overflow-hidden overflow-ellipsis">{value}</div>
        </div>

        <div
          className={`${
            disabled ? 'text-gray-400' : 'text-purple-light'
          } pointer-events-none absolute inset-y-0 right-0 flex items-center pr-1`}
        >
          <svg
            className="h-2.5 w-2.5"
            width="9"
            height="6"
            viewBox="0 0 9 6"
            fill="currentColor"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M4.45879 5.6777L0.561677 0.4277L8.35591 0.4277L4.45879 5.6777Z" />
          </svg>
        </div>
      </button>
      <Transition
        enter-active-class="transition duration-100 ease-out"
        enter-from-class="transform scale-95 opacity-0"
        enter-to-class="transform scale-100 opacity-100"
        leave-active-class="transition duration-75 ease-in"
        leave-from-class="transform scale-100 opacity-100"
        leave-to-class="transform scale-95 opacity-0"
      >
        <div
          className={`absolute top-7 right-0 z-30 rounded shadow ${
            showDropdown ? 'block' : 'none'
          }`}
        >
          <div className="absolute -top-2 right-1 rotate-180 transform text-gray-300">
            <svg
              className="h-2.5 w-2.5"
              width="9"
              height="6"
              viewBox="0 0 9 6"
              fill="currentColor"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M4.45879 5.6777L0.561677 0.4277L8.35591 0.4277L4.45879 5.6777Z" />
            </svg>
          </div>
          <Slot>
            <ul className="text-2xs -right-10 box-border rounded border border-gray-300 bg-gray-200">
              {options.map((val, id) => {
                return (
                  <li
                    className="hover:border-purple-light cursor-pointer rounded border px-1"
                    key={id}
                    role="option"
                    onClick={() => setPriority(val, index)}
                  >
                    {val}
                  </li>
                );
              })}
            </ul>
          </Slot>
        </div>
      </Transition>
    </div>
  );
}

function inputClass(isValid: boolean) {
  return isValid ? 'border-red-700' : '';
}

function setPriority(...args: Array<string | number>) {
  console.log('setPriority', args);
}

```

typscript (ts) sample

```ts
enum AnEnum {
  One,
  Two,
  Three,
  Four,
}

type FuncType = (n: number) => Promise<AnEnum>;

interface AnInterface {
  prop1: AnEnum;
  prop2: string[];
  prop3: Array<number | string>;
  prop4: FuncType;
  prop5: number;
}

async function aFunction({
  prop1,
  prop4,
  prop5,
}: AnInterface): Promise<AnEnum> {
  if (prop5 > 34) {
    const result = await prop4(prop5);
    return result;
  }

  return prop1;
}

aFunction({
  prop1: AnEnum.One,
  prop2: ['a', 'b', 'c'],
  prop3: [1, 2, 'hi', 4],
  prop4: () => Promise.resolve(AnEnum.Two),
  prop5: 35,
});

export { AnEnum, aFunction };

```

**Comment by olimorris** [comment]
Sorry for the slowness in replying to this. I added `tsx` support in f776595560bcd3e37a36ee57fa92ebe4e39abc54. 

I found out that `jsx` highlights are included in the vanilla javascript treesitter parser.

Let me know your feedback!

**Comment by mmirus** [comment]
Thanks for adding that! Comparing TSX and JSX, it seems that they render some colors and styles differently. See below (TSX on left, JSX on right).

![image](https://user-images.githubusercontent.com/524994/203112616-e6fad888-d3a1-434d-8ddd-052e39676b79.png)

I don't think it's my config. Is that intentional?

**Comment by olimorris** [comment]
I prioritised JS over JSX but there may well be some slight differences now as it was one of the earlier filetypes.

I've got some mods to make the colorscheme and then I'm going to do a full review and comparison as I would like to add more of the config options to the filetypes.

**Comment by mmirus** [comment]
Sounds good! For future reference, these are the differences that stand out to me:
- JSX applies the italic option far more broadly than TSX does
- Attribute names on the tags have different colors (red vs orange)

**Comment by olimorris** [comment]
@mmirus it's been a while and you're well.

I've got a PR for some TypeScript improvements (#164). Not sure if you're writing much TS these days but if you are, would love you to take a look and check it out. I'm most keen to ensure that the custom Treesitter queries I write don't slow Neovim down on a big TS file.

**Comment by mmirus** [comment]
Hey @olimorris! Thanks for reaching out! So far I haven't noticed any issues, but I might not be on the necessary version of neovim. I'm on 0.8.3. I'm guessing some or all of this won't apply for me until 0.9?

**Comment by olimorris** [comment]
They're custom Treesitter queries and they're pretty niche so may not have cropped up. I have added the latest support for LSP semantic tokens so when you do upgrade to Neovim 0.9 you're in for a treat (hopefully).

**Comment by mmirus** [comment]
Looking forward to it!
