### ISSUE TITLE
[Bug]: Buffer colors are not working properly on Lualine after the last updates

### ISSUE THREAD

**Issue by CleoMenezesJr** [olimorris/onedarkpro.nvim#114]
### Your OneDarkPro config

```lua
require("onedarkpro").setup({
  dark_theme = "onedark", -- The default dark theme
  light_theme = "onelight", -- The default light theme
  colors = {}, -- Override default colors by specifying colors for 'onelight' or 'onedark' themes
  highlights = {}, -- Override default highlight groups
  -- ft_highlights = {}, -- Override default highlight groups for specific filetypes
  plugins = { -- Override which plugin highlight groups are loaded
    -- See the Supported Plugins section for a list of available plugins
  },
  styles = { -- Choose from "bold,italic,underline"
      strings = "italic", -- Style that is applied to strings.
      comments = "NONE", -- Style that is applied to comments
      keywords = "bold", -- Style that is applied to keywords
      functions = "italic", -- Style that is applied to functions
      variables = "NONE", -- Style that is applied to variables
      virtual_text = "NONE", -- Style that is applied to virtual text
  },
  options = {
      bold = true, -- Use the colorscheme's opinionated bold styles?
      italic = true, -- Use the colorscheme's opinionated italic styles?
      underline = true, -- Use the colorscheme's opinionated underline styles?
      undercurl = false, -- Use the colorscheme's opinionated undercurl styles?
      cursorline = true, -- Use cursorline highlighting?
      transparency = false, -- Use a transparent background?
      terminal_colors = false, -- Use the colorscheme's colors for Neovim's :terminal?
      window_unfocused_color = false, -- When the window is out of focus, change the normal background?
  }
})

```

### Describe the bug

By activating the previous versions it was possible to change the color of the active and inactive buffer as I show in the image below:
![image](https://user-images.githubusercontent.com/54215258/195457251-ea9d49e0-eef9-4da9-9754-173aef6b0993.png)

Now I can only use the inactive buffer color as I show in the video:
[Screencast from 2022-10-12 19-06-28.webm](https://user-images.githubusercontent.com/54215258/195456987-e4f9d02e-d2ce-43a3-9d04-581461328b31.webm)

This problem is not reproduced on topics like Kanagawa

### Final checks

- [X] I have made sure that the colorscheme's caching is not the issue
- [X] I have made sure this is not a duplicate issue
- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`

**Comment by olimorris** [comment]
Please can you fill out the bug report properly and share the latest commit where this worked
