### ISSUE TITLE
[Error]: W18 Invalid character in group name

### ISSUE THREAD

**Issue by roadupcc** [olimorris/onedarkpro.nvim#116]
### Issue/Question/Enhancement

<img width="945" alt="image" src="https://user-images.githubusercontent.com/18000037/195983049-6ecf1f98-7760-4f86-8f2b-89f0d9134cc8.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/18000037/195983084-362e3cba-9de5-4dd8-8dc5-6fff6a44cfab.png">

**Comment by olimorris** [comment]
Can you raise a bug report please
