### ISSUE TITLE
[Bug]: W18 invalid character in group name

### ISSUE THREAD

**Issue by roadupcc** [olimorris/onedarkpro.nvim#117]
### Your OneDarkPro config

```lua
local ok, onedarkpro = pcall(require, "onedarkpro")
if ok then
onedarkpro.setup({
    light_theme = "onelight",
    colors = {
        onelight = {
            black = "#000000",
            gray = "#868686",
            red = "#fd2231",
            fg = "#000000",
            bg = "#ffffff",
            orange = "#aa7005",
            yellow = "#cc8b0e",
            purple = "#7e38e8",
            green = "#128409",
            cyan = "#1a99a9",
            blue = "#1179cb"
        }
    },
    styles = {
        keywords = "bold,italic",
        comments = "italic",
        variables = "bold",
        functions = "bold,italic"
    },
    highlights = {
        Pmenu = {
            bg = "#555555",
            fg = "#ff0000"
        },
        PmenuSel = {
            bg = "#00ff00",
            fg = "#ffffff"
        }
    },
    options = {
        bold = true
    }
})
vim.cmd("colorscheme onedarkpro")
end
```

### Error messages

```lua
处理 /Users/roadup/.local/share/nvim/site/pack/packer/start/onedarkpro.nvim/colors/onedarkpro.vim 时发生错误:
第    3 行:
W18: 组名中含有无效字符
W18: 组名中含有无效字符
W18: 组名中含有无效字符
W18: 组名中含有无效字符
...
```

### Describe the bug

nvim start with an error
```txt
W18 invalid character in group name
```
<img width="796" alt="image" src="https://user-images.githubusercontent.com/18000037/195991099-b8bfb288-bf9b-4428-bb4d-ed43e74e8363.png">

### Final checks

- [X] I have made sure that the colorscheme's caching is not the issue
- [X] I have made sure this is not a duplicate issue
- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`

**Comment by olimorris** [comment]
I can't reproduce this. Are you sure you've properly tested with the `mihimal.lua` file wnd updated to the latest plugin? This was an issue on `Neovim 0.7` before an update

**Comment by olimorris** [comment]
Is this related to #104?

**Comment by roadupcc** [comment]
I got, my neovim 's version is `NVIM v0.8.0-dev+3-g3f2e9298b`, I downgrade to version 7, it is Ok.

Thank you.
