### ISSUE TITLE
Default TelescopeSelection to CursorLine highlight?

### ISSUE THREAD

**Issue by a2bb892** [olimorris/onedarkpro.nvim#123]
### Issue/Question/Enhancement

I really like this theme and how it's customizable!

I have a custom highlight setup for `TelescopeSelection` to match the `CursorLine`:

```
highlights = {
  TelescopeSelection = { link = 'CursorLine' },
}
```

I'm wondering if this should be built in to the theme to honor the `cursorline` config? :thinking: 

It looks like `TelescopeSelection` is already trying to use the config?:
https://github.com/olimorris/onedarkpro.nvim/blob/050e23fa587ee959387fe8d67711f189caa5704b/lua/onedarkpro/highlights/plugins/telescope.lua#L10-L11

But it looks like it needs to be setup more like this?:
https://github.com/olimorris/onedarkpro.nvim/blob/050e23fa587ee959387fe8d67711f189caa5704b/lua/onedarkpro/highlights/editor.lua#L14

Anywho, just wondering if I should just keeping using my custom highlight for this (which I'm perfectly fine with) or if it should be included in the theme? :smiley:

**Comment by olimorris** [comment]
So glad you like it and thanks fpr your comment.

The purple was an opinionated choice, being the main colour of the theme. I'm hesitant to change it, simply because it's been present for a long time with zero feedback; therefore I assume people are okay with it.

Also, given it's a one liner to change, I'd advise to keep doing that.

**Comment by olimorris** [comment]
Also, always looking for filetype contributors so if you have any to add, please do so

**Comment by a2bb892** [comment]
> The purple was an opinionated choice, being the main colour of the theme. I'm hesitant to change it, simply because it's been present for a long time with zero feedback; therefore I assume people are okay with it.

Ah, sorry, if it wasn't clear, I wasn't proposing changing the foreground colour, but the background colour. :smiley: 

Via the [README](https://github.com/olimorris/onedarkpro.nvim#cursorline), there is a way to specify a cursorline colour in the config, which AFICT is the background colour.

And it looks like the cursor line is set with that config here:
https://github.com/olimorris/onedarkpro.nvim/blob/050e23fa587ee959387fe8d67711f189caa5704b/lua/onedarkpro/highlights/editor.lua#L14

I was proposing that the background for `TelescopeSelection` be setup the same way as that. :point_up: 

So, if someone has a custom cursor line background setup (via the config) then it would use that, or else fall back to no background highlight (like the cursor line setup does now). Hope that helps clarify what I was asking about! :sweat_smile:

**Comment by olimorris** [comment]
Sorry, misunderstand you there. Very good spot!

`TelescopeSelection` and `TelescopeMultiSelection` were throwing out `nil` with the weird `config.cursorline` setting so many thanks!
