### ISSUE TITLE
Inverse highlight for different types

### ISSUE THREAD

**Issue by aklk1ng** [olimorris/onedarkpro.nvim#125]
### Issue/Question/Enhancement

![2022-11-04_19-03](https://user-images.githubusercontent.com/94452368/199958103-46c62dde-c953-4267-8ec4-c06b7f24c743.png)
**How can I inverse highlight for different types when rows are selected?Though it's just a visual difference, wanted to give it a try**

**Comment by olimorris** [comment]
Please check the `editor.lua` file. All of the default highlight groups and their descriptions are contained within that:

```lua
Visual = { bg = theme.generated.selection }, -- Visual mode selection
```

So you can override this, for example:

```lua
Visual = { bg = "${purple}", fg = "${bg}" }
```

<img width="1058" alt="Screen Shot 2022-11-05 at 12 02 45@2x" src="https://user-images.githubusercontent.com/9512444/200118911-02be6b27-934c-4094-92f4-025c83576260.png">
