### ISSUE TITLE
Different color when nvimtree is inactive 

### ISSUE THREAD

**Issue by vtmx** [olimorris/onedarkpro.nvim#13]
![error](https://i.imgur.com/htE7RKf.png)

Does anyone know why this happens? 
I tested in Konsole and Alacritty.

**Comment by olimorris** [comment]
This is intended behaviour to highlight `nvim-tree` going out of focus. You can change this by overriding the highlight group `NvimTreeNormalNC`. Something like:

```lua
hlgroups = {
  NvimTreeNormalNC = { bg = '${bg}' }
}
```

**Comment by vtmx** [comment]
> This is intended behaviour to highlight `nvim-tree` going out of focus. You can change this by overriding the highlight group `NvimTreeNormalNC`. Something like:
> 
> ```lua
> hlgroups = {
>   NvimTreeNormalNC = { bg = '${bg}' }
> }
> ```

Thanks!
