### ISSUE TITLE
My color scheme is not displayed correctly

### ISSUE THREAD

**Issue by xuyastc** [olimorris/onedarkpro.nvim#133]
### Issue/Question/Enhancement

**Hi. I need you help**
**Below is my configuration**
<img width="650" alt="image" src="https://user-images.githubusercontent.com/37319368/204275381-39616fdd-3979-46bd-8df2-687372719382.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/37319368/204275420-b9741743-e295-4ef0-8c62-aafdbb88df0a.png">

**Below is my interface display**
<img width="621" alt="image" src="https://user-images.githubusercontent.com/37319368/204275518-3e2bf4f8-cd17-4907-9f63-bea64ea1c7d2.png">

**Below is display in vscode**
<img width="607" alt="image" src="https://user-images.githubusercontent.com/37319368/204275596-2c6b4f08-f09a-4ec9-8b4e-03b86205eda0.png">

**What should I do to display it like vscode?**

**Comment by olimorris** [comment]
This looks like Treesitter is not installed. Try running `:checkhealth` and check that everything is installed and working as expected. Also, is highlighting enabled in Treesitter?
