### ISSUE TITLE
Improve hashing and caching

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedarkpro.nvim#137]
### Issue/Question/Enhancement

The current approach to using a fingerprint, whilst cool, is actually really messy when it comes to merging PRs. Really the compilation process should take place when the git repo changes which will occur when the user forces an update. So probably reading the timestamps of the `.git` repo will suffice.

**Comment by mmirus** [comment]
I saw you had to do that after my last PR and was wondering if it was a new step I was supposed to do when contributing. :heavy_check_mark:

**Comment by olimorris** [comment]
Closed by c00380e17dfe68ff8935a8592258903fd3e0064f
