### ISSUE TITLE
[Enhancement] Add support for semantic token highlighting.

### ISSUE THREAD

**Issue by csy19960309** [olimorris/onedarkpro.nvim#138]
### Enhancement

It would be nice if _onedarkpro.nvim_ can offer syntax highlights with the help of LSP.
Semantic token highlighting has been merged into the master branch of neovim https://github.com/neovim/neovim/commit/9f035559defd9d575f37fd825954610065d9cf96.

**Comment by olimorris** [comment]
Completely agree. This is was raised by @mmirus in https://github.com/olimorris/onedarkpro.nvim/discussions/82#discussioncomment-3500196 and something that we will definitely incorporate.

Reading through the commits, it looks like some new highlight groups are by default, linked to vim syntax groups.

```lua
--LSP semantic tokens
"default link @class Structure",
"default link @struct Structure",
"default link @enum Type",
"default link @enumMember Constant",
"default link @event Identifier",
"default link @interface Identifier",
"default link @modifier Identifier",
"default link @regexp SpecialChar",
"default link @typeParameter Type",
"default link @decorator Identifier",
```

So should be very easy to incorporate. Also, that will give us some absolutely incredible highlighting. I'm running `nvim 0.8` at present so if someone wants to be beat me to it, I'll be happy to accept a PR.

**Comment by olimorris** [comment]
I've just had a play with Neovim 0.9 (no config breaking changes so far btw). I see there's a [PR](https://github.com/nvim-treesitter/playground/pull/57) for Treesitter Playground which will make it easier to identify which tokens are being used for what.

**Comment by csy19960309** [comment]
> I've just had a play with Neovim 0.9 (no config breaking changes so far btw). I see there's a [PR](https://github.com/nvim-treesitter/playground/pull/57) for Treesitter Playground which will make it easier to identify which tokens are being used for what. Propose we wait for that before adding support.

All right. but having to install Treesitter to make use of semantic tokens seems to be a little bit unnecesarry. Hope some kind guy can give a PR so that we can enjoy that feature directly with LSP :)

**Comment by olimorris** [comment]
> All right. but having to install Treesitter to make use of semantic tokens seems to be a little bit unnecesarry. Hope some kind guy can give a PR so that we can enjoy that feature directly with LSP :)

No you don't it's built into the core of Neovim and as long as your LSP server supports semantic tokens, you'll get the highlighting.

Treesitter Playground is a separate plugin which has functionality allowing you to identify which highlight groups Treesitter is applying to your code. There's a PR to extend it so it can do the same for LSP semantic tokens. I want to use Playground to allow me to see where Neovim applies the `@class` semantic token, for example, and therefore what color it should be in the theme. I could probably guess but I suspect the PR will be merged in the next couple of days.

**Comment by csy19960309** [comment]
> > All right. but having to install Treesitter to make use of semantic tokens seems to be a little bit unnecesarry. Hope some kind guy can give a PR so that we can enjoy that feature directly with LSP :)
> 
> No you don't it's built into the core of Neovim and as long as your LSP server supports semantic tokens, you'll get the highlighting.
> 
> Treesitter Playground is a separate plugin which has functionality allowing you to identify which highlight groups Treesitter is applying to your code. There's a PR to extend it so it can do the same for LSP semantic tokens. I want to use Playground to allow me to see where Neovim applies the `@class` semantic token, for example, and therefore what color it should be in the theme. I could probably guess but I suspect the PR will be merged in the next couple of days.

Well I thought the playground was what I had to install to enable the highlighting, sorry for the misunderstanding. Now we just wait for that PR the be merged :)

**Comment by olimorris** [comment]
Quick update on this:

- Semantic tokens are now merged in Neovim 0.9 as per [#21100](https://github.com/neovim/neovim/pull/21100)
- We now have the `:Inspect` command in Neovim 0.9 which shows the origin of highlight groups, be them Treesitter or semantic tokens, as per: [#21393](https://github.com/neovim/neovim/pull/21393)
- The issue of modifiers (brilliantly described in [#21576](https://github.com/neovim/neovim/issues/21576)) is still to follow

Implementation of the tokens is a simple case of adding in the new highlight groups as indicated above. I'll give this some time as want to do some reconciliation back to VS Code but will likely implement in the next month.

**Comment by olimorris** [comment]
In 0e641816457ab32cfc8c64bb59056a585619bf2f I've started to define semantic tokens. I've been restrained in the tokens I've defined so far (matching to `sumneko_lua` in VS Code) and the results are impressive:

## Before
![Screen Shot 2023-01-08 at 17 50 49@2x](https://user-images.githubusercontent.com/9512444/211211200-49d5108c-a024-4a72-bd5c-dc2352b16a82.png)


## After
![Screen Shot 2023-01-08 at 17 53 21@2x](https://user-images.githubusercontent.com/9512444/211211277-64096d48-4345-409d-8f4b-d9d77742392b.png)

## Visual Studio Code
![Screen Shot 2023-01-08 at 17 54 17@2x](https://user-images.githubusercontent.com/9512444/211211332-d76af8c2-7aca-4f76-8bd6-a9a8915018ec.png)

I'm planning on overhauling the way `styles` are applied in the next week or two.

**Comment by csy19960309** [comment]
> In [0e64181](https://github.com/olimorris/onedarkpro.nvim/commit/0e641816457ab32cfc8c64bb59056a585619bf2f) I've started to define semantic tokens. I've been restrained in the tokens I've defined so far (matching to `sumneko_lua` in VS Code) and the results are impressive:
> 
> ## Before
> ![Screen Shot 2023-01-08 at 21 00 51@2x](https://user-images.githubusercontent.com/9512444/211218846-5846ca9b-8815-498f-99cf-21a7f5e9d23e.png)
> 
> ## After
> ![Screen Shot 2023-01-08 at 17 53 21@2x](https://user-images.githubusercontent.com/9512444/211211277-64096d48-4345-409d-8f4b-d9d77742392b.png)
> 
> ## Visual Studio Code
> ![Screen Shot 2023-01-08 at 17 54 17@2x](https://user-images.githubusercontent.com/9512444/211211332-d76af8c2-7aca-4f76-8bd6-a9a8915018ec.png)
> 
> I'm planning on overhauling the way `styles` are applied in the next week or two.

I updated to the latest commit and it works like a charm. Thanks for the work!

**Comment by olimorris** [comment]
I'll close this for now but expect to add more highlights over time
