### ISSUE TITLE
Need some help setting up the colorscheme exactly like the vscode variant

### ISSUE THREAD

**Issue by pramitsingh0** [olimorris/onedarkpro.nvim#143]
### Issue/Question/Enhancement

tried to use the colorscheme out of the box by installing it and setting it up using `vim.cmd('colorscheme onedark')`. Prior to this I was using onedark.nvim. I installed onedarkpro.nvim and set it up using. Didn't see any changes at all. I uninstalled onedark.nvim then tried setting it up again. But no changes at all, except the onedark_dark variant changes the background color to a darker shade.
I have attached a screenshot for reference. 
I have treesitter configured too.
I use neovim version 0.8.1
![image](https://user-images.githubusercontent.com/52959209/209571913-23803b88-3684-4b9c-be81-d03ea4a192a2.png)

**Comment by pramitsingh0** [comment]
Never mind I realised I was using an older version of treesitter. Sorry, my bad.

**Comment by olimorris** [comment]
Were there any files left over from the previous `onedark` install? Assuming you're using packer so there could be a namespace clash.

Can you try this with the `minimal.lua` file in the bug report?

**Comment by pramitsingh0** [comment]
![image](https://user-images.githubusercontent.com/52959209/209572649-18dd5268-06e1-4877-89e2-b93bdc846c9d.png)
The color schemes are still qiute different. I was wondering if there was some way to make them match. Thank you for your amazing work devs

**Comment by pramitsingh0** [comment]
> Were there any files left over from the previous `onedark` install? Assuming you're using packer so there could be a namespace clash.
> 
> Can you try this with the `minimal.lua` file in the bug report?

Yes sure, I will do it and get back at you with the result

**Comment by pramitsingh0** [comment]
![image](https://user-images.githubusercontent.com/52959209/209573148-2fb54790-44e2-484d-b9fd-d5df4c31e233.png)
I tried it with your minimal config file that you provided in your testing template, as you can see I do not have the bufferline as well as lua line. But the issue still persists.
I have made sure to install the latest version of treesitter as well as onedarkpro.nvim.
I have also made sure to test it with minimal.lua config file
I have run check health and made sure treesitter is working fine

**Comment by olimorris** [comment]
In the latest screenshot that looks like it's taken effect. Are you looking to change certain highlight groups? If so, that's covered in the readme.

Otherwise, I'm not sure what the issue is.

**Comment by pramitsingh0** [comment]
Yes, I will figure that part out. Thanks, I just thought it matches with the vscode one out of the box.

**Comment by olimorris** [comment]
> Yes, I will figure that part out. Thanks, I just thought it matches with the vscode one out of the box.

As much as possible. The limiting factor is Treesitter and its highlights; they're different to how VS Code applies them.

Filetype highlights will allow you to get closer 👍🏼.
