### ISSUE TITLE
Add `glance.nvim` plugin back

### ISSUE THREAD

**Issue by mrjones2014** [olimorris/onedarkpro.nvim#144]
### Issue/Question/Enhancement

`glance.nvim` plugin was removed in this commit: 22bef286d631a951dbd87c3346288c2b0babe3cc

Let's work on new support for `glance.nvim` hopefully in a way that's easier to balance and maintain.

**Comment by olimorris** [comment]
So with `onedark` and no additional configuration, this is `glance.nvim` by default:

<img width="1499" alt="Screen Shot 2023-01-03 at 18 16 15@2x" src="https://user-images.githubusercontent.com/9512444/210417073-1847eb60-b56a-49b0-8f0b-916a39acde8b.png">

**Comment by olimorris** [comment]
The look I was failing to achieve was something which matched how I configure my Telescope config:

<img width="1356" alt="Screen Shot 2023-01-03 at 18 17 39@2x" src="https://user-images.githubusercontent.com/9512444/210417261-6e0b7a96-e9f4-4c43-87bc-1d3e7f600bfa.png">

Three, almost distinct, panels with a different variant of the background color

**Comment by olimorris** [comment]
which is kinda where `glance.nvim` is by default.

What do you think we could add to improve it?

**Comment by mrjones2014** [comment]
Maybe it's just clashing a bit with my `NormalNC` highlight group, but this is what it looks like for me.

![image](https://user-images.githubusercontent.com/8648891/210419476-86d0be0c-7bb0-47b3-91b5-d7a0b62bcc6a.png)

I guess I'm basically looking for a bit more contrast on the bg colors, as well as highlighted list item headings (e.g. the "Definitions (1)" text in the right panel).

I'm not sure if this needs a plugin config or if I just need to tweak my own config so it has more contrast with `NormalNC`.

**Comment by olimorris** [comment]
How does this look:

<img width="1505" alt="Screen Shot 2023-01-03 at 19 50 40@2x" src="https://user-images.githubusercontent.com/9512444/210430814-5d89e4a6-f2f2-48d8-9070-b0bfef4d7476.png">

```lua
require("onedarkpro").setup({
  colors = {
    dark = {
      GlancePreviewNormal = "require('onedarkpro.helpers').darken('bg', 6, 'onedark')",
      GlancePreviewLineNr = "require('onedarkpro.helpers').darken('bg', 6, 'onedark')",
      GlancePreviewSignColumn = "require('onedarkpro.helpers').darken('bg', 6, 'onedark')",
      GlancePreviewCursorLine = "require('onedarkpro.helpers').darken('bg', 4, 'onedark')",
    }
  },
  highlights = {
    GlancePreviewNormal = { bg = "${GlancePreviewNormal}" },
    GlancePreviewLineNr = { bg = "${GlancePreviewLineNr}" },
    GlancePreviewCursorLine = { bg = "${GlancePreviewCursorLine}" },
    GlancePreviewSignColumn = { bg = "${GlancePreviewSignColumn}" },
  }
})
vim.cmd([[colorscheme onedark]])
```

**Comment by olimorris** [comment]
Also have you tried:

```lua
glance.setup({
  theme = {
    mode = 'darken',
  },
})
```

**Comment by olimorris** [comment]
Yeah that's definitely a solid enhancement to put forward.

What are your thoughts on packaging the glance highlights as a plugin vs just posting them in the custom highlights issue?

**Comment by mrjones2014** [comment]
That’s fine I think

**Comment by olimorris** [comment]
I'll close this but feel free to re-open it up to riff some more on the colors.
