### ISSUE TITLE
README needs update after removing lualine support

### ISSUE THREAD

**Issue by VPavliashvili** [olimorris/onedarkpro.nvim#149]
### Issue/Question/Enhancement

After this [commit cf4d0be17db8fe1bcd062f5a65fb857225ba3fa3](https://github.com/olimorris/onedarkpro.nvim/commit/cf4d0be17db8fe1bcd062f5a65fb857225ba3fa3) lualine support has dropped, so [README section `Extras`](https://github.com/olimorris/onedarkpro.nvim#gift-extras) needs update accordingly.

**Comment by olimorris** [comment]
Not at all:

![Screen Shot 2023-01-08 at 17 26 36@2x](https://user-images.githubusercontent.com/9512444/211210165-b7d7e727-188e-4e9c-8a7c-f11aa9ac6853.png)

Not sure what you're seeing but the commit simply removed the reference to the `onedarkpro` colorscheme which doesn't technically exist anymore.

**Comment by VPavliashvili** [comment]
I don't understand exactly what happened, just when I sync packer several hours ago, lualine stopped working because I had set theme to onedarkpro. After than I came to read readme and found this line from extras section 

> Lualine
The theme has Lualine support out of the box for all of its themes. This can be found in the [Lualine folder](https://github.com/olimorris/onedarkpro.nvim/blob/main/lua/lualine/themes/onedarkpro.lua).

but if you click [Lualine folder](https://github.com/olimorris/onedarkpro.nvim/blob/main/lua/lualine/themes/onedarkpro.lua) it returns 404. So I thought that you removed lualine support but kept redundant instruction in readme, sorry if I misunderstood the changes

**Comment by olimorris** [comment]
> I don't understand exactly what happened, just when I sync packer several hours ago, lualine stopped working because I had set theme to onedarkpro. After than I came to read readme and found this line from extras section 

The `onedarkpro` theme has been deprecated for a while now. Please use `onedark`, `onelight` or equivalent.

> The theme has Lualine support out of the box for all of its themes. This can be found in the [Lualine folder](https://github.com/olimorris/onedarkpro.nvim/blob/main/lua/lualine/themes/onedarkpro.lua).
> 

Looks like the link is out of date so thanks.
