### ISSUE TITLE
[Bug]: control+c will close neovim

### ISSUE THREAD

**Issue by YosefRohanP** [olimorris/onedarkpro.nvim#151]
### Your OneDarkPro config

```lua
  onedarkpro.setup({
    -- Your onedarkpro config here
  })
  vim.cmd("colorscheme onedark")
```

### Describe the bug

in windows, if you click control+c, it will actually quit neovim, instead of returning to normal mode.

![image](https://user-images.githubusercontent.com/96975716/211359685-849fc5ec-5205-437a-b649-4080c7516b5d.png)

![image](https://user-images.githubusercontent.com/96975716/211360389-8646a1c1-aaae-4053-a990-1d89bcd2b109.png)

### Reproduce the bug

control+c
it starts from this commit https://github.com/olimorris/onedarkpro.nvim/commit/55a5af203541ddf29993758e4b7d4d95cbba72ad

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by olimorris** [comment]
I haven't actually tested on Windows so cannot say with 100% certainty, but I'd be amazed if this commit is causing Neovim to crash or exit. Have you really tested with the minimal config I provided?

I map `<C-c>` in my [config ](https://github.com/olimorris/dotfiles/blob/31dec6b1730d22ca3410ea0f19fe2ce1828c4807/.config/nvim/lua/Oli/plugins/statusline.lua#L13) with no issues.

If you can provide a `minimal.lua` file to test with I'll see if I can recreate it.

**Comment by YosefRohanP** [comment]
not sure if this is related, but sometimes it shows this just for a split second
![Untitled](https://user-images.githubusercontent.com/96975716/211363572-a84b563f-e6bf-41f8-aea9-0f8cb9416a10.png)

**Comment by YosefRohanP** [comment]
> I haven't actually tested on Windows so cannot say with 100% certainty, but I'd be amazed if this commit is causing Neovim to crash or exit. Have you really tested with the minimal config I provided?
> 
> I map `<C-c>` in my [config ](https://github.com/olimorris/dotfiles/blob/31dec6b1730d22ca3410ea0f19fe2ce1828c4807/.config/nvim/lua/Oli/plugins/statusline.lua#L13) with no issues.
> 
> If you can provide a `minimal.lua` file to test with I'll see if I can recreate it.

I have already tested it with minimal.lua, the only things I changed in it was the 'ensure_installed = "all"'

**Comment by YosefRohanP** [comment]
I found this bug in November, but I just put this in my packer config.
```lua
commit = "6f13896727c82c1ff56acf483d474ba7ad88f230"
```

**Comment by olimorris** [comment]
I've just pushed a fix (61b4f4509a59247118ff93f1707f41d4674a5ac2) which I hope stops the `a subdirectory or file [xxxxxxx] already exists`. Can you let me know if that works?

**Comment by YosefRohanP** [comment]
the message is gone, thank you!

**Comment by YosefRohanP** [comment]
but weirdly, it also fixes the control+c problem, thank you!

**Comment by olimorris** [comment]
Glad to hear and thanks for raising!
