### ISSUE TITLE
TelescopePromptPrefix not being respected? 

### ISSUE THREAD

**Issue by petobens** [olimorris/onedarkpro.nvim#156]
### Your OneDarkPro config

Dunno if this is a problem with onedark or telescope; I tried using:
```lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
    {
        'nvim-telescope/telescope.nvim',
        dependencies = { 'nvim-lua/plenary.nvim' },
    },
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})

-- Plugin setup
require('onedarkpro').setup({})
vim.cmd('colorscheme onedark')
require('telescope').setup({})
```
But cannot quite seem to change the  `TelescopePromptPrefix` highlight. 

### Describe the bug

AFAICT the `TelescopePromptPrefix` as per https://github.com/olimorris/onedarkpro.nvim/blob/main/lua/onedarkpro/highlights/plugins/telescope.lua#L30 should be purple but I'm seing a plain gray one.

I tried running: 
```lua
lua vim.api.nvim_set_hl(0, "TelescopePromptPrefix", {fg="Green"})
```
but that didn't change the color either.

![image](https://user-images.githubusercontent.com/2583971/217125995-56d034de-eacf-4285-8516-3a4fa08948a6.png)

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by olimorris** [comment]
With this minimal config I can see a red prompt:

```lua
local root = "/tmp/onedarkpro"

-- Set stdpaths to use root dir
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
  },
  {
    "olimorris/onedarkpro.nvim",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- Plugin setup
require("telescope").setup()
require("onedarkpro").setup({
  highlights = {
    TelescopePromptNormal = { fg = "${red}" },
  },
})
vim.cmd("colorscheme onedark")
```

<img width="1222" alt="Screen Shot 2023-02-07 at 13 44 22@2x" src="https://user-images.githubusercontent.com/9512444/217261681-1970f7ac-0f17-49be-b3c1-7695184c92da.png">

The order of the `require("telescope").setup()` call shouldn't matter either. Can you test this out?

**Comment by petobens** [comment]
If I try your config with:
```    highlights = {
        TelescopePromptPrefix = { fg = '${red}' },
    },
```
so that only the Prompt symbol should be highlighted in red then it doesn't seem to work (i.e I want only to change the prompt symbol highlight not the text). Can you reproduce this?

**Comment by olimorris** [comment]
What do you see if you run `hi TelescopePromptPrefix`?

**Comment by olimorris** [comment]
Wondering if it's related to https://github.com/nvim-telescope/telescope.nvim/issues/2285

**Comment by petobens** [comment]
![image](https://user-images.githubusercontent.com/2583971/218272936-7cc78e73-1a80-44f9-bb3e-f7e74b0af3be.png)

Do you actually get a red hl when using `TelescopePromptPrefix`?

**Comment by olimorris** [comment]
> ![image](https://user-images.githubusercontent.com/2583971/218272936-7cc78e73-1a80-44f9-bb3e-f7e74b0af3be.png)
> 
> Do you actually get a red hl when using `TelescopePromptPrefix`?

This looks correct?! I think `TelescopePromptNormal` might be what you're looking for. This is likely in part down to how I was applying telescope highlights in the theme. A little confusing.

**Comment by xulongwu4** [comment]
I had a similar issue with nvim lightly. However, I believe this might be a bug in neovim nightly itself as I can reproduce this behavior with multiple color schemes. @petobens, are you using the nightly build of neovim?

**Comment by petobens** [comment]
Hi @xulongwu4 ! I'm indeed using the nightly build.

**Comment by olimorris** [comment]
I'm having this too. But in a really weird way.

On opening Telescope, the prompt is the color of `fg`. Then if I delete a session via Telescope, you can see the prompt changes color to `red` (which is correct):

![Screen Shot 2023-02-24 at 08 52 03](https://user-images.githubusercontent.com/9512444/221134828-52d75b14-2c18-4b6c-9a9d-d6127fc05401.gif)

**Comment by xulongwu4** [comment]
https://github.com/nvim-telescope/telescope.nvim/issues/2384

**Comment by olimorris** [comment]
> https://github.com/nvim-telescope/telescope.nvim/issues/2384

Thanks for finding this. Will leave this issue open for now in case others come across it

**Comment by olimorris** [comment]
Conni's sorted this: a3f17d3baf70df58b9d3544ea30abe52a7a832c2
