### ISSUE TITLE
"Vivid" colors

### ISSUE THREAD

**Issue by mmirus** [olimorris/onedarkpro.nvim#16]
Hey there! Not an issue, just sharing info for anyone else interested.

I personally liked the vivid colors from One Dark in VS Code (specifically https://github.com/Binaryify/OneDark-Pro).

If anyone wants to recreate them in this theme, I think this is all that's needed:

```
lua <<EOF
local onedarkpro = require('onedarkpro')
onedarkpro.setup({
  theme = "onedark",
  colors = {
    onedark = {
      -- Vivid colors from https://github.com/Binaryify/OneDark-Pro
      red = "#ef596f",
      green = "#89ca78",
      cyan = "#2bbac5",
      purple = "#d55fde",
    },
  },
})
onedarkpro.load()
EOF
```

**Comment by olimorris** [comment]
I've closed this and pinned it to the top of `issues` so it will stand out more to other users

**Comment by mmirus** [comment]
Thank you!

**Comment by abayomi185** [comment]
Hi @olimorris I'm fairly new to nvim and Lua and looking to change the color of "variables" (assigned) in my config and I'm not sure how. I've tried;
```lua
  { "olimorris/onedarkpro.nvim",
    config = function()
      require("onedarkpro").setup {
        theme = "onedark",
        colors = {
          red = "#97f4c9"
        },
      }
    end
  },
```
![image](https://user-images.githubusercontent.com/21103047/164814183-896c26b6-d165-41db-b4fa-f77162d2aa9a.jpeg)

..but couldn't get it to work. What am I missing?

**Comment by olimorris** [comment]
> ..but couldn't get it to work. What am I missing?

Have your tried at the end of your config?

```lua
onedarkpro.load()
```

**Comment by abayomi185** [comment]
I'm using Lunarvim and I believe it loads the plugin. It also shows that it is installed in PackerStatus.

I have also tried to add the function call in my config;

![Screenshot 2022-04-23 at 20 48 57](https://user-images.githubusercontent.com/21103047/164943975-fce1250e-1403-4689-8f4f-b304d80ad3b2.jpg)

It unfortunately still doesn't change the red variable colour in my code.

**Comment by olimorris** [comment]
Hmmmm. Seems strange. Have you tried adding @mmirus config specifically like below:

> local onedarkpro = require('onedarkpro')
> onedarkpro.setup({
>   theme = "onedark",
>   colors = {
>     onedark = {
>       -- Vivid colors from https://github.com/Binaryify/OneDark-Pro
>       red = "#ef596f",
>       green = "#89ca78",
>       cyan = "#2bbac5",
>       purple = "#d55fde",
>     },
>   }

If you nest a `onedark` table within the `colors` table. That shouldn't actually make a difference but good to rule it out.

Otherwise, I suspect another theme or option is overwriting the `TSVariable` highlight group (assuming you're using Treesitter). What does `:hi TSVariable` show?

**Comment by abayomi185** [comment]
Nesting ```onedark``` does not change the colors.

I am using Treesitter, ```:hi TSVariable``` shows ```TSVariable      xxx guifg=#e06c75```. This is using mmirus’ config.

I also tried disabling all other additional plugins to no avail.

I’ll keep trying to sort it out, I now have a better understanding of how Treesitter works. Thank you!

**Comment by olimorris** [comment]
I'm at a loss to explain it other than there must be something, somewhere in your config which is not applying the change. Are you sure `LunarVim` is definately applying the theme?

I've just tried it in my config and this is the outcome:

## Config
<img width="1501" alt="Screen Shot 2022-04-24 at 22 27 58@2x" src="https://user-images.githubusercontent.com/9512444/164997390-d88c4197-c8f2-4035-b4e3-f963142f9496.png">

## Outcome
<img width="1508" alt="Screen Shot 2022-04-24 at 22 28 25@2x" src="https://user-images.githubusercontent.com/9512444/164997400-e1a57aa8-1016-4050-8434-effcaafe80d2.png">

**Comment by abayomi185** [comment]
It seems that is the case. I did a bunch of testing and it does work but does not persist. I seemingly have to change ```:colorscheme``` back (to a different theme) and forth to see the custom setup, otherwise it defaults to the default setup values. It was hard to tell because quitting and relaunching ```Lunarvim``` didn't change the outcome, also TS-rainbow seems to get disabled.

Thanks again for your help. It's definitely related to my setup so I'll look to find a solution.

## Config
![Screenshot 2022-04-25 at 00 52 18](https://user-images.githubusercontent.com/21103047/165001894-6ad21c59-4f59-4185-93f2-67ce477ae713.jpg)

## Outcome
![Screenshot 2022-04-25 at 00 51 14](https://user-images.githubusercontent.com/21103047/165001870-0235cbed-d24c-4f67-8576-3e9e8ad9128b.jpg)

**Comment by abayomi185** [comment]
I thought I'd put this here in case a search engine brings someone to this issue.

I solved it. It was more my misunderstanding of the structure of LunarVim's config files and Lua.

The setup needs to be added outside the scope of lvim.plugins to persist.

```lua
--[[
lvim is the global options object

Linters should be
filled in as strings with either
a global executable or a path to
an executable
]]
-- THESE ARE EXAMPLE CONFIGS FEEL FREE TO CHANGE TO WHATEVER YOU WANT

-- general
lvim.log.level = "warn"
lvim.format_on_save = true
-- lvim.colorscheme = "one"
-- lvim.colorscheme = "onedarker"
lvim.colorscheme = "onedarkpro"


-- Theme options
require("onedarkpro").setup {
  theme = "onedark",
  -- colors = {
  --   red = "#d1d1d1"
  -- },
  styles = {
    functions = "italic",
    keywords = "italic",
    virtual_text = "italic,underline",
  },
}
```

**Comment by olimorris** [comment]
As an FYI both, I've now added a `onedark_vivid` them as per [this](https://github.com/olimorris/onedarkpro.nvim/commit/2f931d2dd7f0157abda143656b7fb5cb26eeb9a0) commit:

```lua
require("onedarkpro").setup {
  theme = "onedark_vivid",
}
```

**Comment by mmirus** [comment]
Very cool--thank you! I was able to replace my vivid overrides with `dark_theme = "onedark_vivid"` and my remaining `onedark` overrides (unrelated to making things more vivid) kept working.

It may be counterintuitive, but I may go back to the `darken`ed versions of the virtual text. https://github.com/olimorris/onedarkpro.nvim/commit/2f931d2dd7f0157abda143656b7fb5cb26eeb9a0#diff-708b067690c963ab0c5a4dec1eb8f6c0e1f7cda3a447538280b3bde6cd7ffb47 I kind of like having the diagnostic info fade into the background a bit--readable when I need it, but not competing with the code for attention.

I can see other people wanting the opposite, though: "If there's a diagnostic, I want it to be yelling for attention so I deal with it right away."

**Comment by olimorris** [comment]
Awesome! Still a little bit of work I need to do on the internal API to add new themes but mostly there
