### ISSUE TITLE
different token color for constant variables (just like vscode)

### ISSUE THREAD

**Issue by jNaimXIII** [olimorris/onedarkpro.nvim#162]
### Issue/Question/Enhancement

One of my favorite things about OneDarkPro on VSCode is that it highlights variables declared with `const` and `let` differently in javascript / typescript files.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/115424698/222687467-76483d62-30ec-481a-801d-6118b2ec8938.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/115424698/222687478-963e97fe-a4f5-46fb-8894-c3d60e96d4dc.png">

Is there a way to replicate the same behavior in this extension for neovim?

**Comment by olimorris** [comment]
There sure is: https://github.com/olimorris/onedarkpro.nvim#configuring-filetype-highlighting

**Comment by jNaimXIII** [comment]
Well... seems like tree-sitter sees both of them as just a `@variable.typescript`. Don't see a way to identify between a `const` or `let`.

**Comment by jNaimXIII** [comment]
In rust for example, the constants and variables are highlighted separately as they use different identifiers. So, this is a tree-sitter thing and a theme can't do much, is it?

<img width="310" alt="image" src="https://user-images.githubusercontent.com/115424698/222690009-467af64a-a11f-4005-b914-2b33070ca4b5.png">

**Comment by olimorris** [comment]
I've just checked the code snippet in Nightly and it looks the same, even with LSP Semantic Tokens. So yep, this looks like a limitation with Treesitter unfortunately.

You could possibly create some custom Treesitter queries which would see them differently although my knowledge of that is limited.

**Comment by jNaimXIII** [comment]
Yea, same here. I guess I'll leave a feature request in tree-sitter regarding this.

**Comment by olimorris** [comment]
You've sparked my curiosity...I'll look at adding in some custom queries at some point this weekend.

**Comment by jNaimXIII** [comment]
Looking forward to it. 🤗
