### ISSUE TITLE
Enhancement: Custom Treesitter queries

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedarkpro.nvim#163]
### Issue/Question/Enhancement

As outlined in #162, there are some limitations in how Treesitter highlights certain elements; noticeably in JS and TS files.

It would be great if the theme had additional Treesitter queries to address this.

cc: @jNaimXIII

**Comment by jNaimXIII** [comment]
Here's an issue discussing this matter in tree-sitter's repository.

https://github.com/nvim-treesitter/nvim-treesitter/issues/4434

**Comment by jNaimXIII** [comment]
@olimorris We might have some good news.

https://github.com/nvim-treesitter/nvim-treesitter/issues/4434#issuecomment-1453393052

**Comment by olimorris** [comment]
Actually after doing some playing in Treesitter playground, the following would also work:

```scm
;; extends
[
"let"
] @keyword.let

[
"const"
] @keyword.const
```

If it was placed in the `lua/after/queries/javascript/highlights.scm` folder

**Comment by olimorris** [comment]
<img width="526" alt="Screen Shot 2023-03-03 at 11 55 28@2x" src="https://user-images.githubusercontent.com/9512444/222714292-b5fb6768-3922-4e5e-b76e-77c5c4fe553d.png">

```lua
highlights = {
  ["@keyword.let.javascript"] = { bg = "${red}", fg = "${bg}" },
  ["@keyword.const.javascript"] = { bg = "${purple}", fg = "${bg}" },
}
```

Queries were placed in my `~/.config/nvim/queries/javascript/highlights.scm` path.

**Comment by olimorris** [comment]
I just need to update the queries to pick out the actual variables. But proof it can be done

**Comment by jNaimXIII** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/115424698/222714856-6d43aa63-6b5b-44cc-aa86-37c8d4d95a73.png">

Yeah, got the same result. I don't understand how this stuff works but, if it's a step in the right direction then, great.

**Comment by olimorris** [comment]
...and if you update the queries to:

```scm
;; extends
[
("let" (variable_declarator name: (identifier) @keyword.let))
]

[
("const" (variable_declarator name: (identifier) @keyword.const))
]
```

It works but gets overwritten by `@variable.javacript` highlight.

**Comment by jNaimXIII** [comment]
Can't we just slap a `!important` like we always do in CSS? 🙂

**Comment by olimorris** [comment]
Voila:

```scm
;; extends
[
("let" (variable_declarator name: (identifier) @keyword.let) (#set! "priority" 1000))
]

[
("const" (variable_declarator name: (identifier) @keyword.const) (#set! "priority" 1000))
]
```

Great thinking on the `!important` equivalent 😄.

**Comment by olimorris** [comment]
Can now achieve this:

<img width="614" alt="Screen Shot 2023-03-03 at 12 32 43@2x" src="https://user-images.githubusercontent.com/9512444/222721191-d9330144-3c56-4a8f-bee0-f8fd5b0c9aa2.png">

**Comment by jNaimXIII** [comment]
> Voila:
> 
> ```scheme
> ;; extends
> [
> ("let" (variable_declarator name: (identifier) @keyword.let) (#set! "priority" 1000))
> ]
> 
> [
> ("const" (variable_declarator name: (identifier) @keyword.const) (#set! "priority" 1000))
> ]
> ```
> 
> Great thinking on the `!important` equivalent 😄.

What can I say... web dev instincts. :)

**Comment by jNaimXIII** [comment]
> Can now achieve this:
> 
> <img alt="Screen Shot 2023-03-03 at 12 32 43@2x" width="614" src="https://user-images.githubusercontent.com/9512444/222721191-d9330144-3c56-4a8f-bee0-f8fd5b0c9aa2.png">

Noice. Now share the highlights code.

**Comment by olimorris** [comment]
`["@keyword.const.javascript"] = { fg = "${yellow}" }`

**Comment by olimorris** [comment]
Didn't need the `let` highlights in the end.

**Comment by jNaimXIII** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/115424698/222722805-b8a4cf47-ceb8-47a0-b8d5-b28ff865e576.png">

Success!

**Comment by jNaimXIII** [comment]
So, is there a way to make this work automatically by the plugin without any user intervention?

**Comment by amaanq** [comment]
I fixed this here: https://github.com/nvim-treesitter/nvim-treesitter/pull/4435, should have it merged soonish :)

**Comment by jNaimXIII** [comment]
Can't believe I've waited for over a year frustrating over this just for it to be fixed in a single evening. Crazy how things play out if you just speak up. Lessons to be learnt here folks.

**Comment by amaanq** [comment]
I'm really sorry about that 😐 but if you ever have a highlights or general tree-sitter issue do not hesitate to reach out to me :) (but...a year is a long time so I wouldn't have been able to help you then as I've just become maintainer recently)

**Comment by jNaimXIII** [comment]
All's well that ends well. 👍

**Comment by olimorris** [comment]
> So, is there a way to make this work automatically by the plugin without any user intervention?

There is yes. Putting the queries into the plugin instead. I'm going to add this on the roadmap for other languages too as it would be a useful feature.
