### ISSUE TITLE
[Bug]: Custom queries override sane defaults

### ISSUE THREAD

**Issue by amaanq** [olimorris/onedarkpro.nvim#167]
after/queries/python is overriding `@variable.builtin` (self), causing worse highlighting for **any** theme.

I'd recommend either a) using a custom name so as to not interfere with defaults, and they stay specific to this theme, or b) load them only if the plugin is loaded/in use

Relevant: https://github.com/nvim-treesitter/nvim-treesitter/issues/4485

**Comment by olimorris** [comment]
@amaanq thanks for flagging! Stupidity on my part.

Interestingly, how do you conditionally load queries?

**Comment by amaanq** [comment]
ngl, idk 😅 maybe putting it in a different directory and adding it to the runtime path of the theme is in use might work, give it a shot
