### ISSUE TITLE
Lualine Support

### ISSUE THREAD

**Issue by augustocdias** [olimorris/onedarkpro.nvim#17]
Does this plugin support lualine?

**Comment by olimorris** [comment]
> Does this plugin support lualine?

For `onedark`, the only difference is in the `bg` and the additional grays provided by the Lualine theme. For `onelight` however, there is quite a big difference.

@augustocdias could you give me a link to a theme that does support Lualine and I will take a look.

**Comment by augustocdias** [comment]
https://github.com/folke/tokyonight.nvim and https://github.com/monsonjeremy/onedark.nvim support it.

@mmirus that's what I use and that's why I asked because the color for lsp warnings in the lualine implementation is unreadable inside the the green background. I'm currently using tokyonight because of that... I'll create an issue on their side to deal with it

**Comment by olimorris** [comment]
How does this look?
![Screen Shot 2021-11-15 at 22 26 52](https://user-images.githubusercontent.com/9512444/141862781-342c8cbb-027e-4ccf-b6c4-ddd0d0546122.gif)

The `git diff` stuff looks a bit funky:
<img width="151" alt="Screen Shot 2021-11-15 at 22 28 00@2x" src="https://user-images.githubusercontent.com/9512444/141862868-50e10d75-9106-4bac-ad3b-504ba8ffcdc9.png">

...presume this is a `lualine` default you can change?

Oh and the `tme` function is my custom function for toggling between `onedark` and `onelight`.

**Comment by mmirus** [comment]
Looking good!

**Comment by augustocdias** [comment]
Very good I'd say.

**Comment by olimorris** [comment]
Awesome. Have merged into `main`
