### ISSUE TITLE
[Bug]: Can't override colors 

### ISSUE THREAD

**Issue by chikko80** [olimorris/onedarkpro.nvim#175]
### Your OneDarkPro config

```lua
local test_dir = "/tmp/onedarkpro"
local root = vim.fn.fnamemodify(test_dir, ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "olimorris/onedarkpro.nvim",
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },

  -- add any other plugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
  treesitter.setup({
    ensure_installed = "all",
    ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  })
end

-- setup onedarkpro
local ok, onedarkpro = pcall(require, "onedarkpro")
if ok then
  onedarkpro.setup({
    -- Your onedarkpro config here
  })
  vim.cmd("colorscheme onedark")
end


require("onedarkpro").setup({
  highlights = {
    ["@comment"] = { fg = "#FFFFFF", bg = "#FFFFFF" },
    Comment = { fg = "#FFFFFF", bg = "#FFFFFF" }
  }
})


vim.cmd("colorscheme onedark")
```

### Error messages

No Errors

### What i expect to happen
That all comments are white

### What happens
Nothing

### Reproduce the bug

Run the minmal config and do a comment in a lua file (for example)

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by olimorris** [comment]
@chikko80 Can you check the latest commits. Not entirely sure what caused it but I could recreate it with the `minimal.lua` config.

**Comment by chikko80** [comment]
@olimorris Seems like its working, i'll test some things and if everything works as expected i'll close the issue - thanks so far

**Comment by chikko80** [comment]
<img width="2446" alt="Screenshot 2023-03-25 at 11 04 03 PM" src="https://user-images.githubusercontent.com/58805871/227744487-1c13aefc-92bc-42a0-ace5-5835c1809ffa.png">

@olimorris 

Most of it seems to work now but I am still facing the issue that I can't override @keyword and @field.
For testing purposes i tried to highlight everything in white, but the @keyword and @field doesn't work.

```lua
    ["@variable"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@variable.builtin"] = {fg = "#FFFFFF", bg = "#FFFFFF"},

    ["@field"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@keyword"] = { fg = "#FFFFFF", bg = "#FFFFFF"},

    ["@function"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@function.builtin"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@function.call"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@function.macro"] = { fg = "#FFFFFF", bg = "#FFFFFF"},

    ["@method"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@method.call"] = { fg = "#FFFFFF", bg = "#FFFFFF"},

    ["@constructor"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@parameter"] = { fg = "#FFFFFF", bg = "#FFFFFF"},


    ["@type"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@type.builtin"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@type.definition"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@type.qualifier"] = { fg = "#FFFFFF", bg = "#FFFFFF"},

    ["@storageclass"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@attribute"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@property"] = { fg = "#FFFFFF", bg = "#FFFFFF"},
    --
    --
    ["@constant"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@constant.builtin"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@constant.macro"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@namespace"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@symbol"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.constant"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.function"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.method"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["definition.var"] = {fg =  "#FFFFFF" , bg =  "#FFFFFF"},
    ["@definition.parameter"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.macro"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.type"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.field"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.enum"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.namespace"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.import"] = {fg = "#FFFFFF", bg = "#FFFFFF"},
    ["@definition.associated"] = {fg = "#FFFFFF", bg = "#FFFFFF"},

```

**Comment by olimorris** [comment]
Can you share your example file and try `:OnedarkproCache`. There's no reason for some to work and others not to so really strange,

**Comment by chikko80** [comment]
Tried :OnedarkproCache but didn't help

just drop this example rust code in a rest.rs file

```rust
pub struct Test{
    test: String,
    test2: String,
}
```

**Comment by olimorris** [comment]
That looks like it's to be expected unless you do `["@field.rust"]. If I run the `:Inspect` command I see:

- For `test`:
<img width="300" alt="Screen Shot 2023-03-25 at 22 43 15@2x" src="https://user-images.githubusercontent.com/9512444/227745779-7616920f-31a5-46d9-8b00-8970eb69514a.png">

- For `String`:
<img width="437" alt="Screen Shot 2023-03-25 at 22 43 36@2x" src="https://user-images.githubusercontent.com/9512444/227745788-afce1458-4836-4150-bf54-61dd2db50165.png">

This is because you have the filetype highlighting for Rust turned on by default. You can turn this off by:

```lua
filetypes = {
  rust = false,
}
```

**Comment by chikko80** [comment]
Oh okay got it sorry. Just learning all these new plugins currently and it's a bit overwhelming.
But tbh Neovim 0.9 with the lsp semantics comes the closest to vscode and I even customized semantic tokens in my VSCode so it fits perfectly.

Currently if I run Neovim 0.9 with treesitter i'll get a bunch of warnings. Is this expected since 0.9 is only on nightly available right now? Did you already migrate your personal setup to 0.9?


<img width="1485" alt="Screenshot 2023-03-25 at 11 55 47 PM" src="https://user-images.githubusercontent.com/58805871/227746204-e883543d-0a23-4b86-ad65-1f8e792f82ba.png">

**Comment by olimorris** [comment]
@chikko80 completely with you! To take a few weeks away from the Neovim subreddit can feel like life has moved on 🤣.

I actually found I had very few warnings with `0.9/nightly` compared with other versions. Might be some existing plugins need to be updated or have a separate branch for nightly.

Btw, was looking at the Rust filetype highlights last night. Think they're a little "off" compared to VS Code so will push some changes today. Appreciate your feedback on them.
