### ISSUE TITLE
[Bug]: @lsp.type.comment.lua overrides @text.uri.comment

### ISSUE THREAD

**Issue by mmirus** [olimorris/onedarkpro.nvim#188]
### Your OneDarkPro config

This happens with a default onedarkpro.nvim config plus Lua language server. Below is an example using lsp-zero / Mason to install and start the language server. To reproduce the bug, ensure that Mason has automatically installed the language server and then restart neovim.

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "olimorris/onedarkpro.nvim",
    opts = {
      -- Your OneDarkPro config goes here
    },
    config = true
  },

  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },

  -- add any other plugins here
  {
    'VonHeikemen/lsp-zero.nvim',
    branch = 'v2.x',
    dependencies = {
      -- LSP Support
      {'neovim/nvim-lspconfig'},             -- Required
      {                                      -- Optional
	'williamboman/mason.nvim',
	build = function()
	  pcall(vim.cmd, 'MasonUpdate')
	end,
      },
      {'williamboman/mason-lspconfig.nvim'}, -- Optional

      -- Autocompletion
      {'hrsh7th/nvim-cmp'},     -- Required
      {'hrsh7th/cmp-nvim-lsp'}, -- Required
      {'L3MON4D3/LuaSnip'},     -- Required
    },
    config = function() 
      local lsp = require('lsp-zero').preset({})

      lsp.on_attach(function(client, bufnr)
	lsp.default_keymaps({buffer = bufnr})
      end)

      lsp.ensure_installed({ 'lua_ls' })

      -- (Optional) Configure lua language server for neovim
      require('lspconfig').lua_ls.setup(lsp.nvim_lua_ls())

      lsp.setup()
    end
  }
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
  treesitter.setup({
    ensure_installed = "all",
    ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  })
end

vim.cmd("colorscheme onedark")

-- Comment with https://a.url.com in it

```

### Error messages

N/A

### Describe the bug

When the Lua langage server is active, `@lsp.type.comment.lua` overrides `@text.uri.comment`, resulting in URLs in Lua comments being highlighted the same as the surrounding comment.

### What I expect

Here's a comment with the minimal config:

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/a7ef62a2-da6b-43ca-9ee1-d5c351bf87d0)

### What actually happens

Here's a comment with the minimal config plus Lua language server:

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/8729a52c-f2e1-4193-b677-eacdb632cfe4)

### Reproduce the bug

1. Use the minimal.lua shared above which includes lsp-zero with Lua language server
2. Ensure that Mason has finished automatically installing the language server and restart neovim
3. Observe that when you launch neovim the URL in the comment at the end of the file is initially highlighted blue, and then changes to gray when the language server has loaded

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by mmirus** [comment]
No problem!

Here's what I get from `:Inspect`:

```
Treesitter                                                                                   
  - @comment.lua links to Comment lua                                                        
  - @spell.lua links to @spell lua                                                           
  - @spell.comment links to @spell comment                                                   
  - @spell.comment links to @spell comment                                                   
  - @text.uri.comment links to @text.uri comment                                             
  - @nospell.comment links to @nospell comment                                               
                                                                                             
Semantic Tokens                                                                              
  - @lsp.type.comment.lua links to Comment priority: 125
```

The final section is not in the output until the language server finishes loading, of course.

**Comment by olimorris** [comment]
Thank you! Looks like some custom treesitter queries ftw!

Shall do this Friday after I merge the big PR 🙌🏼

**Comment by mmirus** [comment]
Awesome. Thank you!

**Comment by olimorris** [comment]
Closed by mistake.

**Comment by olimorris** [comment]
@mmirus should be fixed. Was a nightmare trying to track the parser down before realising it was the `comment` one!

**Comment by olimorris** [comment]
`@odp.uri.comment` is the highlight group to override if you so wish.

**Comment by mmirus** [comment]
Thanks, @olimorris! Seems like it's working well for me, and I haven't hit the TODO comment issue (I guess since I use todo-comments, based on your last update over on #190).

Seems like with the addition of semantic tokens it's getting harder to juggle the highlight rules.

**Comment by olimorris** [comment]
I foresee a few more semantic token issues on the horizon 😆.
