### ISSUE TITLE
YAML files are not highlighted

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedarkpro.nvim#19]
One of the concessions I had to make with trying to make the theme match VS Code's One Dark Pro was to sacrifice how `YAML` files are highlighted.

The highlight group responsible is `TSField`. Treesitter sees `YAML` files as a collection of fields and highlights them accordingly. However it also applies `TSField` to certain elements in `Python` files. So we end up with a trade off. Do we wish to have `YAML` files highlighted nicely or make `Python` stick as close to the original One Dark Pro as best we can? I guess the choice is up to you.

## Python with TSField set to foreground (default)
<img width="746" alt="Screen Shot 2021-11-28 at 11 14 16@2x" src="https://user-images.githubusercontent.com/9512444/143765494-12055d7d-756b-428e-ab55-46368345ece1.png">

## Python with TSField set to red (which highlights YAML files)
<img width="742" alt="Screen Shot 2021-11-28 at 11 15 08@2x" src="https://user-images.githubusercontent.com/9512444/143765524-6f555e5a-d2ca-41c2-b74d-03279ac32308.png">

## YAML with TSField set to red
<img width="688" alt="Screen Shot 2021-11-28 at 11 15 37@2x" src="https://user-images.githubusercontent.com/9512444/143765543-719fe56f-1584-431e-8413-77b1c5f12362.png">

## Your configuration
If you wish to customise the `TSField` highlight group, you can do so by providing a highlight group override as per the [readme](https://github.com/olimorris/onedarkpro.nvim#configuring-highlight-groups):

```lua
local onedarkpro = require('onedarkpro')
onedarkpro.setup({
  hlgroups = {
    TSField = { fg = "${red}" }
  }
})
onedarkpro.load()
```

**Comment by olimorris** [comment]
Covers the issue raised in #18

**Comment by mmirus** [comment]
Thanks for this! Nice upgrade for me since I work with YAML but not Python. 🥳
