### ISSUE TITLE
Bug with when Treesitter Enable

### ISSUE THREAD

**Issue by vtmx** [olimorris/onedarkpro.nvim#20]
When I skip consecutive lines with Treesitter turned active, these underlines appear and suddenly disappear. 

![bug](https://i.imgur.com/dMmNVRZ.png)

**Comment by olimorris** [comment]
Can you share the full file? I don't think this is theme related and likely to be treesitter. Have you tried with another theme?

**Comment by olimorris** [comment]
@vtmx any update?

**Comment by vtmx** [comment]
Sorry, it looks like it's something with treesitter, I tested on other themes, the same problem occurs. If I disabled it, the go back to normal.

**Comment by olimorris** [comment]
I'll link to my Treesitter config's [here](https://github.com/olimorris/dotfiles/blob/main/.config/nvim/lua/plugins/treesitter.lua) anyway, in case useful.
