### ISSUE TITLE
Changing higlight groups for vim-matchup

### ISSUE THREAD

**Issue by RayZ0rr** [olimorris/onedarkpro.nvim#21]
I have the following in my onedarkpro setup file

```lua
  colors = {}, -- Override default colors. Can specify colors for "onelight" or "onedark" themes by passing in a table
  hlgroups = {  -- Override default highlight groups
    Cursorline = { bg="Grey20" , },
    MatchParen = { bg='Grey20' },
    MatchBackground = { bg='Grey20', fg="Grey40" },
  },

```
However, I am still not able to get a distinct background for the line shown by vim-matchup for start of a function

**Comment by olimorris** [comment]
Are `Grey20` and `Grey40` defined anywhere?

I have defined the following hlgroups and it appears to be working (as per the screenshot below):
```lua
hlgroups = {
  -- Vim matchup
  Cursorline = { bg = "${purple}" },
  MatchParen = { bg = "${purple}" },
  MatchBackground = { bg = "${purple}", fg = "${gray}" },
}
```
<img width="448" alt="Screen Shot 2022-01-16 at 13 27 20@2x" src="https://user-images.githubusercontent.com/9512444/149661895-066f5c32-202f-4662-a4fe-c65cf15d1ebe.png">

**Comment by RayZ0rr** [comment]
I think these colours are inbuilt? I am able to change the colors with `Grey20` and `Grey40` etc.

I will also test with vim-matchup

**Comment by olimorris** [comment]
@RayZ0rr any luck in the end?

**Comment by RayZ0rr** [comment]
No luck with what I intended, the relevant highlights I thought were, `MatchParen` , `MatchParenCur` , `MatchWord` and `MatchBackground`. 

I was trying to get the line of code (for the opening braces) that vim-matchup shows over text when the cursor is at closing braces and the opening braces is not currently visible in the buffer like shown here :

![vim-ondarkpro](https://user-images.githubusercontent.com/96843787/150767557-6d044a59-fb3d-4046-a792-ca71b7022554.gif)


But overall, it looks good, and this thing I can adjust. Okay to close?
