### ISSUE TITLE
Change folded highlight group

### ISSUE THREAD

**Issue by RayZ0rr** [olimorris/onedarkpro.nvim#22]
Could you change the current `Folded` highlight group?

Currently it makes it harder to distinguish folded text from comments.

I can change it in : 
```lua
onedarkpro.setup({
  hlgroups = {}
})
```
but many other highlight groups are linked to it.

**Solution**

Change `LineNr` to

`LineNr = { bg = theme.options.transparency, fg = theme.colors.gray }, -- Line number for ":number" and ":#" commands, and when 'number' or 'relativenumber' option is set.`

and link it in place of `Folded`

**Comment by olimorris** [comment]
Good spot! Have removed all links to `Folded` as this is likely to be a common issue. Thanks for raising.
