### ISSUE TITLE
[Bug]: No Markdown Highlighting

### ISSUE THREAD

**Issue by n-crespo** [olimorris/onedarkpro.nvim#222]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "olimorris/onedarkpro.nvim",
    opts = {
      -- Your OneDarkPro config goes here
    },
    config = true,
  },

  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },

  -- add any other plugins here
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
{
  "folke/tokyonight.nvim",
  lazy = false,
  priority = 1000,
  opts = {},
},
{ "EdenEast/nightfox.nvim" }, -- lazy
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
  treesitter.setup({
    ensure_installed = "markdown",
    ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  })
end

vim.cmd("colorscheme onedark")
```

### What I expect to happen:

Syntax highlighting on markdown files, similar to below: (this is with tokyonight_night enabled with the minimal configuration)

![image](https://github.com/olimorris/onedarkpro.nvim/assets/122305393/2939102c-43f9-4cbe-a205-772fddb2fd8c)

Below is an image from a week ago with onedark_dark from my default configuration: 

![image](https://github.com/olimorris/onedarkpro.nvim/assets/122305393/5f98ebac-c2dd-43b7-9128-278d0570a6c6)

The default configuration: (none of the custom highlighting works either)

```lua
local md_highlight = "#14161a"
return {
  -- theme of choice, transparent, italic comments, markdown italic support
  "olimorris/onedarkpro.nvim",
  name = "onedarkpro",
  priority = 1000, -- Ensure it loads first
  config = function()
    require("onedarkpro").setup({
      styles = { -- For example, to apply bold and italic, use "bold,italic"
        comments = "italic", -- Style that is applied to comments
        virtual_text = "bold", -- Style that is applied to virtual text
      },
      options = {
        cursorline = false, -- Use cursorline highlighting?
        transparency = true, -- Use a transparent background?
        terminal_colors = true, -- Use the theme's colors for Neovim's :terminal?
        highlight_inactive_windows = false, -- When the window is out of focus, change the normal background?
        bold = true,
        italic = true,
        underline = true,
        undercurl = true,
      },
      highlights = {
        ["@text.emphasis"] = { italic = true },
        ["@tag.html"] = { fg = "#89ca78" },

        ["@text.todo.unchecked"] = { bg = md_highlight },
        Headline = { bg = md_highlight },
        CodeBlock = { bg = md_highlight },

        WhichKeyFloat = { bg = nil }, -- transparent whichkey
        TabLineSel = { bg = "#22272f", bold = true },
        MiniStatuslineModeNormal = { bg = "#22272f" },
        LazyButton = { bg = "#22272f" },
        TreeSitterContext = { bg = "#22272f" },
      },
    })
    vim.cmd.colorscheme("onedark_dark")
  end,
}
```

### What actually happens:

No highlighting: 

![image](https://github.com/olimorris/onedarkpro.nvim/assets/122305393/1ac3bd81-a7a3-4737-9783-02bdd5ea85aa)

I could not re-create functional markdown highlighting with the minimal configuration, but I have been using this color scheme for a long time in my regular config and only today has markdown highlighting not worked. 

### Reproduce the bug

Steps to reproduce:

Open any markdown file with this color scheme enabled. 

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by olimorris** [comment]
There was a change in the markdown Tree-sitter parser in the last day or two unfortunately. Hopefully the latest commit resolves it.

If you notice any highlights that haven't been applied, can you do `:Inspect` and let me know what the highlight groups are and what the colors should be?

**Comment by n-crespo** [comment]
Here are some, and a) I don't fully remember what most of them were supposed to look like and b) there may be more highlights I don't have listed 



(I could use a color picker but I'll get slight variations in the hex codes, but I think the following has some standard colors in it that would be consistent with the rest of the color scheme)

```lua 
local onedark = require("onedarkpro.helpers").get_colors("onedark_dark")
```

| old highlight group name| new highlight group name| fix |
|---|---|---|
|`@text.todo.unchecked`| `@markup.list.checked.markdown links to @markup markdown`| I don't know what this used to look like, but the highlight name changed (this is checkboxes) |
|`@text.emphasis`|  `@markup.italic.markdown_inline links to @markup markdown_inline `| should be italic |
|`@tag.html`|  `@tag.html` | This works properly |
|  idk |   `@markup.heading.2.markdown links to @markup markdown`| some kind of light green? I don't have a way to make the theme work properly so I'm not sure what the exact color is. This one probably is `onedark.green` (this applies to all headers) |
| idk | `@markup.strong.markdown_inline links to @markup markdown_inline` | should be bolded |
| idk | `@markup.list.markdown links to @markup markdown` | should be some type of red, probably `onedark.red` (this is the bullet points)|
| idk | `@markup.link.label.markdown_inline` | Should be some shade of blue, probably `onedark.blue` (this is text inside square brackets)|
| idk | `@markup.raw.markdown_inline` | Should be some shade of green, probably `onedark.green` (inline code) |
| idk | `@markup.link.markdown_inline` and `@markup.link.url.markdown_inline` | should be some shade of pink, probably `onedark.pink` (if that exists?) (this is a URL)|
| idk | `@markup.quote.markdown`| This didn't have any highlighting in the old theme, but since it is a quote it could have a fg like this: "#757876" (this is a quote `>`)|

Hope this helps a bit at least! Is the problem just that the highlight names have changed?

**Comment by olimorris** [comment]
Right I've moved my earlier additions to the `treesitter.lua` file and referenced them as per https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights. Also added some of your suggestions...great spot.

Any adjustments you wish to make should be possible via your config...I've tested the following and it works as expected:

```lua
local md_highlight = "#14161a"
return {
  {
    "olimorris/onedarkpro.nvim",
    priority = 1000, -- Ensure it loads first
    opts = {
      styles = { -- For example, to apply bold and italic, use "bold,italic"
        comments = "italic", -- Style that is applied to comments
        virtual_text = "bold", -- Style that is applied to virtual text
      },
      options = {
        cursorline = false, -- Use cursorline highlighting?
        transparency = true, -- Use a transparent background?
        terminal_colors = true, -- Use the theme's colors for Neovim's :terminal?
        highlight_inactive_windows = false, -- When the window is out of focus, change the normal background?
        bold = true,
        italic = true,
        underline = true,
        undercurl = true,
      },
      highlights = {
        ["@text.emphasis"] = { italic = true },
        ["@tag.html"] = { fg = "#89ca78" },

        ["@text.todo.unchecked"] = { bg = md_highlight },
        Headline = { bg = md_highlight },
        CodeBlock = { bg = md_highlight },

        WhichKeyFloat = { bg = nil }, -- transparent whichkey
        TabLineSel = { bg = "#22272f", bold = true },
        MiniStatuslineModeNormal = { bg = "#22272f" },
        LazyButton = { bg = "#22272f" },
        TreeSitterContext = { bg = "#22272f" },
      },
    },
    config = function(_, opts)
      require("onedarkpro").setup(opts)

      vim.cmd([[colorscheme onedark_dark]])
    end,
  },
}
```

**Comment by n-crespo** [comment]
Looks great! Thanks for everything and for the quick response time!

**Comment by n-crespo** [comment]
Btw, not sure it's worth the effort for changing this, but the colors for the part of markdown links inside of the square brackets and text inside the parenthesis are switched: 

![image](https://github.com/olimorris/onedarkpro.nvim/assets/122305393/e981befe-51dd-4eef-b00a-c833bfeb4eb8)

For reference, here how it used to be (switched around)

![image](https://github.com/olimorris/onedarkpro.nvim/assets/122305393/a638da4a-9b6e-4ff0-af1b-1a26dc1e96c2)
