### ISSUE TITLE
[Bug]: missing treesitter-based highlight for JS/TS properties after breaking nvim-treesitter update

### ISSUE THREAD

**Issue by mmirus** [olimorris/onedarkpro.nvim#224]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "olimorris/onedarkpro.nvim",
    opts = {
      -- Your OneDarkPro config goes here
    },
    config = true
  },

  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },

  -- Delete if you do not require LSP
  {
    "VonHeikemen/lsp-zero.nvim",
    branch = "v2.x",
    dependencies = {
      -- LSP Support
      {"neovim/nvim-lspconfig"},             -- Required
      {                                      -- Optional
        "williamboman/mason.nvim",
        build = function()
          pcall(vim.cmd, "MasonUpdate")
        end,
      },
      {"williamboman/mason-lspconfig.nvim"}, -- Optional

      -- Autocompletion
      {"hrsh7th/nvim-cmp"},     -- Required
      {"hrsh7th/cmp-nvim-lsp"}, -- Required
      {"L3MON4D3/LuaSnip"},     -- Required
    },
    config = function()
      local lsp = require("lsp-zero").preset({})

      lsp.on_attach(function(client, bufnr)
        lsp.default_keymaps({buffer = bufnr})
      end)

      lsp.ensure_installed({ "lua_ls", "tsserver" })

      -- (Optional) Configure lua language server for neovim
      require("lspconfig").lua_ls.setup(lsp.nvim_lua_ls())

      lsp.setup()
    end
  }

  -- add any other plugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
  treesitter.setup({
    ensure_installed = "all",
    ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  })
end

vim.cmd("colorscheme onedark")
```

### Describe the bug

Properties in JS/TS objects are not properly highlighted, especially when the language server is not active to provide semantic tokens.

The comment at the top indicates if the file was a JS or TS file.

**Without the language server:**

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/5a137b95-6320-423d-b615-82def447fdea)

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/c0012f7d-7f70-4e20-bd64-c850b8b02e4b)

**With the language server:**

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/35c574f6-dcf5-4731-8cdc-1c1781fa4edc)
:point_up: this one may be all good

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/62ad9326-f26f-495e-880a-fc9c141b2485)
:point_up: still missing for one property

---

Probably unrelated, but interesting: the highlighting of brackets is different in TS vs JS.

### Reproduce the bug

1. Edit a JS or TS file:
    ```js
    // ts
    const obj = {
	    key: 'value',
	    other: () => {},
    }
    
    ```
2. View the outcome.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by zmre** [comment]
+1

More details on the changes are here: https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/

For me, the lack of syntax coloring is really quite evident in markdown files where even bold/italic type styling is gone, heading styling is gone, etc.

**Comment by olimorris** [comment]
> +1
> 
> More details on the changes are here: https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/
> 
> For me, the lack of syntax coloring is really quite evident in markdown files where even bold/italic type styling is gone, heading styling is gone, etc.

@zmre this was fixed in #222

**Comment by olimorris** [comment]
@mmirus can you let me know if the latest commit resolve this?

**Comment by mmirus** [comment]
Yep! There are still differences between JS and TS, but that's probably for a separate ticket if anyone cares. I haven't verified the colors that are being used now are "correct" (i.e., what they were previously or what's in the vscode theme), but nothing is lacking color now.

Thank you!

**Without LSP**

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/d1f76835-7ea9-45b7-8a93-a730b4400e29)

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/205a2adc-9fe5-4839-ad38-e7c8715b7406)

**With LSP**

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/659592f1-6dcf-4100-8452-55bbfe0bf2e1)

![image](https://github.com/olimorris/onedarkpro.nvim/assets/524994/21db8d72-1e71-4e43-924a-8f6c50defb96)

**Comment by olimorris** [comment]
I think I still have it on my todolist to unify the TS/JS styling actually. I think we discussed it over a year ago and I never quite got around to doing it.
