### ISSUE TITLE
vscode onedarkpro vs this one

### ISSUE THREAD

**Issue by sinkyl** [olimorris/onedarkpro.nvim#23]
Hi,

This is a suggestion.
I end up changing many highlights and colors to represent the onedarkpro for vscode that has over 4M downloads, a standard onedarkpro theme. If this repo is for everyone to enjoy the standard onedarkpro theme with neovim you should represent the exact onedarkpro.          

For example, the default backgroud color should be `bg = "#282c34"`, the next line should be purple and not italic `		TSInclude = { fg = theme.colors.blue, style = theme.options.italic }, -- For includes: "#include" in C, "use" or "extern crate" in Rust, or "require" in Lua.` and so on.

People should start from the standard theme and then change settings/highlights/colors if needed. But, if this repo is for yourself just ignore what I just said.

One last suggestion, the plugins by default should be set to false, so we can keep the onedarkpro.settup clean as much as possible.

Thanks

**Comment by olimorris** [comment]
Thanks for the feedback.

Could you let me know the highlights and colors that you've changed and I'll look into incorporating into the theme.

Regarding the italics, I'll caveat by saying in the readme I specify "Use the themes _opinionated_ italic styles?" but there is a case for setting this to `false` by default.

**Comment by sinkyl** [comment]
```
local colors = require("onedarkpro").get_colors("onedark")
...

colors = { 
   bg = "#282c34"
},


hlgroups = { 
   -- onedarkpro -> treesitter.lua plugin
   TSInclude = { fg = colors.purple, style = "NONE" },
   TSTypeBuiltin = { fg = colors.yellow },
   TSConstBuiltin = { fg = colors.purple },
   TSConstructor = { fg = colors.yellow },
   TSRepeat = { style = "NONE" },
   TSFuncMacro = { fg = colors.blue },
   TSParameterReference = { fg = colors.red },

   -- onedarkpro -> theme.lua
   Include = { fg = colors.purple },
   Function = { fg = colors.blue },
   Operator = { fg = colors.fg }, 
   Macro = { fg = colors.blue },
   Special = { fg = colors.fg },
   Structure = { fg = colors.purple },
   Identifier = { fg = colors.red },
   Typedef = { fg = colors.purple },
   Constant = { fg = colors.orange },
 }
```

Results:

- Rust
  nvim
![nvr](https://user-images.githubusercontent.com/24904905/152914840-2d624141-e4c7-471d-a203-8b923dc3567e.png)
  vscode
![vsr](https://user-images.githubusercontent.com/24904905/152914877-efe16895-a13b-482b-9f3a-aca4e237139f.png)

- C
  nvim
![nvc](https://user-images.githubusercontent.com/24904905/152915438-4442884b-9baf-4249-be89-e5831ad6a8de.png)
  vscode
![vsc](https://user-images.githubusercontent.com/24904905/152915471-585a78bc-755e-4be7-b714-895d042219fa.png)

- C#
  nvim (The first <T> in red is annoying. It should be yellow but TSVariables set it to red)
![nvcsharp](https://user-images.githubusercontent.com/24904905/152915806-a2384172-23b6-4ba8-b6dd-3da98fd56383.png)
  vscode
![vscsharp](https://user-images.githubusercontent.com/24904905/152915869-dad25bd1-0115-451a-80aa-fcf5a21e4e60.png)

- Go
  nvim (the functions in the interface are in red)
![nvgo](https://user-images.githubusercontent.com/24904905/152918110-c4336f63-c394-45f9-818c-82c45e773539.png)
  vscode
![vsgo](https://user-images.githubusercontent.com/24904905/152918259-7cccca7c-dcab-44d1-885d-18f05ea9d03d.png)


- Typescript is ok
- Javascript is not

The onedarkpro for vscode is adding unique style for each language. IMO, this repo should do the same.
For now, I'm trying to add custom highlighters with treesitter/playground.
Nice work BTW.

**Comment by olimorris** [comment]
Firstly, thank you for your detailed feedback and config. It is greatly appreciated.

I agree with the majority of your changes and have addressed them in the latest commit. Some I have not included (detail and reasoning below).

> The onedarkpro for vscode is adding unique style for each language. IMO, this repo should do the same.

Yes it does. I have actively thought about doing this and may look into it in the near future. Let me know if you make any progress. Always open to pull requests.

FYI, the hlgroups which I have kept the same are:
```lua
TSRepeat
Operator
Special
```
Reason being that they caused some difference in look between Neovim and VS Code in Ruby, Python and Javascript files which I don't have with their current values. Happy to be corrected and adjust them (could always be a setting I missed in my custom VS Code config).

**Comment by mmirus** [comment]
Thanks both! I was able to remove a few of my customizations after updating.

**Comment by mmirus** [comment]
https://github.com/olimorris/onedarkpro.nvim/commit/bde2f189e904f01f612326b795be9ec5d94b5ce1#diff-6278de756e40002a1404b733de0b7f2d1526f9fd53e80f01b4aff117ac98e17dR112

@olimorris Typo here, I think :wink:

**Comment by olimorris** [comment]
> [bde2f18#diff-6278de756e40002a1404b733de0b7f2d1526f9fd53e80f01b4aff117ac98e17dR112](https://github.com/olimorris/onedarkpro.nvim/commit/bde2f189e904f01f612326b795be9ec5d94b5ce1#diff-6278de756e40002a1404b733de0b7f2d1526f9fd53e80f01b4aff117ac98e17dR112)
> 
> @olimorris Typo here, I think 😉
> 
> Edit: also [bde2f18#diff-6278de756e40002a1404b733de0b7f2d1526f9fd53e80f01b4aff117ac98e17dR93](https://github.com/olimorris/onedarkpro.nvim/commit/bde2f189e904f01f612326b795be9ec5d94b5ce1#diff-6278de756e40002a1404b733de0b7f2d1526f9fd53e80f01b4aff117ac98e17dR93)

I can't see where the typos are in the diff. In the readme?

**Comment by mmirus** [comment]
`Maacro` and `Faunction` in `theme.lua`:

https://github.com/olimorris/onedarkpro.nvim/blob/bde2f189e904f01f612326b795be9ec5d94b5ce1/lua/onedarkpro/theme.lua#L112

https://github.com/olimorris/onedarkpro.nvim/blob/bde2f189e904f01f612326b795be9ec5d94b5ce1/lua/onedarkpro/theme.lua#L93

**Comment by olimorris** [comment]
@mmirus, you sir, are a legend as always! Thanks for spotting

**Comment by mmirus** [comment]
You got it!

**Comment by sinkyl** [comment]
Ok for the highlights but the plugins are somehow always set to true event I change it to false.

**Comment by olimorris** [comment]
Should now be fixed. I've had to apply some trickery to how we merge the default config with the user's custom config. End result is your test cases above now work.

**Comment by olimorris** [comment]
@sinkyl - Would you also be willing to try out the [filetype_hlgroups](https://github.com/olimorris/onedarkpro.nvim/tree/feature/filetype-hlgroups) branch?

I've got a WIP feature which allows you to add custom highlight groups for specific filetypes. Works great on my end (to overcome the `TSField` issue with `yaml` files) but keen to see your use cases and especially if you notice any performance issues.

**Comment by sinkyl** [comment]
All good now.
I'll give a try later.
Thx 💯
