### ISSUE TITLE
[Bug]: Not an editor command: require("onedarkpro").setup

### ISSUE THREAD

**Issue by ianchanning** [olimorris/onedarkpro.nvim#236]
### Your `minimal.lua` config

N/A

### Error messages

```
Not an editor command: require("onedarkpro").setup({ 
  styles = { 
    comments = "italics",
  }
})
```

### Describe the bug

When I source my `.vimrc` file I get the above error.

The documentation here assumes that you are configuring nvim with lua, I of course being a dinosaur am using `.vimrc`.

It would appear that treesitter has hit similar issues https://github.com/nvim-treesitter/nvim-treesitter/issues/616

They put some text in their README https://github.com/nvim-treesitter/nvim-treesitter#modules:

> Following examples assume that you are configuring neovim with lua. If you are using vimscript, see `:h lua-heredoc`. All modules are disabled by default and need to be activated explicitly in your `init.lua`, e.g., via ...

So could you perhaps put some notes in the README above where the first configuration is suggested?

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by olimorris** [comment]
Hey @ianchanning.

This is the first time this has been raised in c. 3 years of the plugin so I've assumed that users who have a `.vimrc` are recognising the examples in the README are Lua ones and making the appropriate adjustments.

Can you propose a PR for this which would have helped you avoid this?

**Comment by ianchanning** [comment]
Thanks for the response :) 

One of the definite issues when using the Lua heredoc syntax is [not to indent the heredoc commands](https://github.com/nvim-treesitter/nvim-treesitter/issues/616#issuecomment-717351140).

In theory it is quite easy to use lua syntax as long as they are surrounded by the heredoc tags:
```vim
" don't indent this block
lua << EOF
  require("onedarkpro").setup({
    styles = {
      types = "NONE",
      methods = "NONE",
      numbers = "NONE",
      strings = "NONE",
      comments = "italic",
      keywords = "bold,italic",
      constants = "NONE",
      functions = "italic",
      operators = "NONE",
      variables = "NONE",
      parameters = "NONE",
      conditionals = "italic",
      virtual_text = "NONE",
    }
  })
EOF
```

But as it is I have to resource the `.vimrc` each time after loading for the changes to have effect, so there is something wrong with how I am using the `setup` commands in my `vimrc`. But at least I know that the lua commands don't throw errors and are clearly working. 

For having to re-source the `.vimrc`, there's a potential that I need to [force everything to be loaded before calling the lua](https://www.reddit.com/r/neovim/comments/qfyrdm/lua_require_doesnt_work_when_placed_in_initvim_or/?rdt=56320) - but I tried that and that doesn't work. Further possibility is that the syntax [gets cleared initially after the `.vimrc`](https://stackoverflow.com/a/16545464/327074), but again, I tried that and that didn't work. 

But whatever it is I don't feel like I have a good answer for your documentation on how to use the `setup` inside a `.vimrc` file. If I find something I'll raise a PR.

**Comment by olimorris** [comment]
Crikey. Just when you thought it was safe to wrap everything in a heredoc without any care for indents 😄.

Your last example, yes I would expect that to work. The theme uses some clever caching to apply your config settings to highlight groups and write them to disk.

Anyway, props for not going into the rabbit hole of a Lua config. There are too many nice things to see and do in life than be in front of a Lua file late all the time 😆 .
