### ISSUE TITLE
[Bug]: Transparent background not applied

### ISSUE THREAD

**Issue by Spencillian** [olimorris/onedarkpro.nvim#237]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs { 'config', 'data', 'state', 'cache' } do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    'olimorris/onedarkpro.nvim',
    opts = {
      transparency = true,
    },
    config = true,
  },

  { 'nvim-treesitter/nvim-treesitter', build = ':TSUpdate' },
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

-- setup treesitter
local ok, treesitter = pcall(require, 'nvim-treesitter.configs')
if ok then
  treesitter.setup {
    ensure_installed = 'all',
    ignore_install = { 'phpdoc' }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  }
end

vim.cmd 'colorscheme onedark'
```

### Expected
With `transparency = true` I'd expect the background to become transparent, revealing the terminal background.
![image](https://github.com/olimorris/onedarkpro.nvim/assets/48698410/d5f09e0a-e187-4bf8-9669-26d966471a8b)
^ with tokyonight
### What Happens
Background is the default
![image](https://github.com/olimorris/onedarkpro.nvim/assets/48698410/cded0b71-6d46-4abb-82f6-3ba07073a939)
^ tested with minimal.lua
All tests done with WSL Ubuntu 22.04 LTS Windows Terminal

### Reproduce the bug

1. copy minimal.lua into a file
2. run the nvim clean command
3. Verify that transparency is not set

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
- [X] If related to semantic tokens, I have checked that my LSP server supports them
- [X] I have made sure this is not a duplicate issue

**Comment by olimorris** [comment]
As per the readme, it should be:

```lua
options = {
  transparency = true
}
```

**Comment by Spencillian** [comment]
Sorry I had tried both variations of `opts` and `options` in my own setup before putting them into the `minimal.lua` and both don't work. 
![image](https://github.com/olimorris/onedarkpro.nvim/assets/48698410/5b58d2f2-b1a5-4501-afcd-5ba06c264c04)
new minimal.lua
```lua
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs { 'config', 'data', 'state', 'cache' } do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    'olimorris/onedarkpro.nvim',
    options = {
      transparency = true,
    },
    config = true,
  },

  { 'nvim-treesitter/nvim-treesitter', build = ':TSUpdate' },
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

-- setup treesitter
local ok, treesitter = pcall(require, 'nvim-treesitter.configs')
if ok then
  treesitter.setup {
    ensure_installed = 'all',
    ignore_install = { 'phpdoc' }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  }
end

vim.cmd 'colorscheme onedark'
```
If there's anything more I can do to debug this issue please let me know. I really like this theme but not having transparency is deal breaker for me.

**Comment by olimorris** [comment]
As per the [readme](https://github.com/olimorris/onedarkpro.nvim?tab=readme-ov-file#configuring-options), you define transparency via the `options` table:

```lua
require("onedarkpro").setup({
  options = {
    transparency = true
  }
})
```

So if you're using Lazy.nvim, your config becomes:

```lua
{
  "olimorris/onedarkpro.nvim",
  opts = {
    options = {
      transparency = true
    }
  }
}
```

**Comment by Spencillian** [comment]
My bad, thank you for your help

**Comment by olimorris** [comment]
My pleasure and I hope you enjoy the theme.

**Comment by phuongpd2k** [comment]
This is my config, and I’m still not transparent yet. :(
`return {
  "olimorris/onedarkpro.nvim",
  priority = 10000, -- Ensure it loads first
  opts = {
    options = {
      transparency = true
    }
  },
  config = function()
    -- Set the colorscheme after the plugin is loaded
    vim.cmd("colorscheme onedark")
  end,
}
`

**Comment by AlifiChiganjati** [comment]
> This is my config, and I’m still not transparent yet. :(
> 
> return {
>   "olimorris/onedarkpro.nvim",
>   priority = 10000, -- Ensure it loads first
>   opts = {
>     options = {
>       transparency = true
>     }
>   },
>   config = function()
>     -- Set the colorscheme after the plugin is loaded
>     vim.cmd("colorscheme onedark")
>   end,
> }


 {
    "olimorris/onedarkpro.nvim",
    priority = 1000, -- Ensure it loads first
    config = function()
      require("onedarkpro").setup({
        options = {
          transparency = true,
        },
      })
      vim.cmd("colorscheme onedark")
    end,
  },
it solve transparent
