### ISSUE TITLE
[Request] Add strikethrough to the style options

### ISSUE THREAD

**Issue by sinkyl** [olimorris/onedarkpro.nvim#25]
```... = { ... style = "strikethrough" }``` should be an option
thx

**Comment by olimorris** [comment]
Sorry I'm confused. Should we putting `strikethrough` against certain highlight groups and/or referencing it in the readme?

**Comment by sinkyl** [comment]
Sorry about that.
I just thought it would be nice having something like below (an nvim-cmp highlight).
```
CmpItemAbbrDeprecated = { fg = colors.fg, style = "strikethrought" },
```

**Comment by sinkyl** [comment]
My bad! I realized that this is not required by the theme, it's already done by nvim-cmp ( `highlight! CmpItemAbbrDeprecated guibg=NONE gui=strikethrough guifg=#808080` ). Sorry for the confusion.

**Comment by olimorris** [comment]
No problem. Sorry I hadn't got around to replying
