### ISSUE TITLE
Share your custom highlights

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedarkpro.nvim#31]
# Telescope
I thought I'd begin by sharing how I have `Telescope` formatted:

## Screenshots

<img width="1382" alt="Screen Shot 2022-03-06 at 07 50 58@2x" src="https://user-images.githubusercontent.com/9512444/156914174-dc94a89c-b309-4a71-90e2-1d66921a4cc1.png">
<img width="1374" alt="Screen Shot 2022-03-06 at 07 51 49@2x" src="https://user-images.githubusercontent.com/9512444/156914184-6cb0d1b3-e0d9-4f5f-9d86-10b535365a80.png">

## Highlights

```lua
colors = {
  onedark = {
    telescope_prompt = utils.lighten(onedarkpro.get_colors("onedark").bg, 0.97),
    telescope_results = utils.darken(onedarkpro.get_colors("onedark").bg, 0.85),
  },
  onelight = {
    telescope_prompt = utils.darken(onedarkpro.get_colors("onelight").bg, 0.98),
    telescope_results = utils.darken(onedarkpro.get_colors("onelight").bg, 0.95),
  },
},
hlgroups = {
  TelescopeBorder = {
    fg = "${telescope_results}",
    bg = "${telescope_results}",
  },
  TelescopePromptBorder = {
    fg = "${telescope_prompt}",
    bg = "${telescope_prompt}",
  },
  TelescopePromptCounter = { fg = "${fg}" },
  TelescopePromptNormal = { fg = "${fg}", bg = "${telescope_prompt}" },
  TelescopePromptPrefix = {
    fg = "${purple}",
    bg = "${telescope_prompt}",
  },
  TelescopePromptTitle = {
    fg = "${telescope_prompt}",
    bg = "${purple}",
  },

  TelescopePreviewTitle = {
    fg = "${telescope_results}",
    bg = "${green}",
  },
  TelescopeResultsTitle = {
    fg = "${telescope_results}",
    bg = "${telescope_results}",
  },

  TelescopeMatching = { fg = "${purple}" },
  TelescopeNormal = { bg = "${telescope_results}" },
  TelescopeSelection = { bg = "${telescope_prompt}" },
}
```
> _Note:_ The config for Telescope itself was taken from the awesome [NvChad](https://github.com/NvChad/NvChad)!

**Comment by mmirus** [comment]
Had occasion to pop open some PHP code for the first time in a while, and thought I'd see how the theme compares to vscode. As it turns out, it's really close!

Here are a handful of changes I've made so far to match vscode more closely:

```lua
    -- PHP
    ["@method.php"] = { fg = "${blue}", style = "bold" },
    ["@method.call.php"] = { link = "@method.php" },
    ["@function.builtin.php"] = { fg = "${cyan}" },
    ["@keyword.php"] = { fg = "${purple}", style = "NONE" },
    ["@keyword.return.php"] = { link = "@keyword.php" },
    ["@namespace.php"] = { fg = "${yellow}", style = "bold" },

```

**Comment by olimorris** [comment]
> Had occasion to pop open some PHP code for the first time in a while, and thought I'd see how the theme compares to vscode. As it turns out, it's really close!
> 
> 
> 
> Here are a handful of changes I've made so far to match vscode more closely:
> 
> 
> 
> ```lua
> 
>     -- PHP
> 
>     ["@method.php"] = { fg = "${blue}", style = "bold" },
> 
>     ["@method.call.php"] = { link = "@method.php" },
> 
>     ["@function.builtin.php"] = { fg = "${cyan}" },
> 
>     ["@keyword.php"] = { fg = "${purple}", style = "NONE" },
> 
>     ["@keyword.return.php"] = { link = "@keyword.php" },
> 
>     ["@namespace.php"] = { fg = "${yellow}", style = "bold" },
> 
> 
> 
> ```

Amazing! Would you consider a pr to add PHP support?

**Comment by mmirus** [comment]
Sure thing! See https://github.com/olimorris/onedarkpro.nvim/pull/118.

**Comment by tristan957** [comment]
I will probably come with some Meson fixes at some point, and I have it on my list to look at C.

**Comment by NickP-real** [comment]
since you change the highlight configuration, can you update the highlight value?

**Comment by olimorris** [comment]
@NickP-real - I've updated my Telescope post for the new theme API

**Comment by smit2909** [comment]
The screenshot has the foldchar in yellow when the code is folded, and gray when not, can someone help on how to achieve that?
