### ISSUE TITLE
SCSS color VSCode

### ISSUE THREAD

**Issue by Asterovim** [olimorris/onedarkpro.nvim#33]
Hello.
I don't understand why i didn't have the same color : 
Vscode One Dark Pro SCSS: 
![image](https://user-images.githubusercontent.com/34446820/157192691-213ee60d-ef18-45ed-b331-7f8e3bf15209.png)

Neovim One Dark Pro SCSS : 
![image](https://user-images.githubusercontent.com/34446820/157192769-66a37b9c-eb1e-4486-bbde-7767a96df8dc.png)

I use neovim v0.6.1
Lastest Treesitter and OneDarkPro (no custom config)

Could you help me please ?

**Comment by olimorris** [comment]
Could you paste your `scss` code and I can take a look.

**Comment by Asterovim** [comment]
> Could you paste your `scss` code and I can take a look.
Thanks you 👍 
```
.entete-twitter {
  display: flex;
}
.field--name-field-tweet-content {
  margin-left: rem-calc(50);
}
.field--name-field-tweet-user {
  a {
    text-decoration: none;
    &:before {
      content: "@";
    }
  }
}

.bloc-partenaires {
  background: $zurb-color-grey;
  .field--name-dynamic-twig-fieldblock-content-bloc-des-partenaires {
    @include xy-grid-container($width: $container-home);
    text-align: center;
    #zf-splide-partenaires-accueil-list {
      align-items: center;
    }
    .field--type-image {
      text-align: center;
    }
  }
}
```

**Comment by olimorris** [comment]
So after doing some digging, this is the best I can come up with:

<img width="900" alt="Screen Shot 2022-03-08 at 09 08 54@2x" src="https://user-images.githubusercontent.com/9512444/157204628-e0081c4a-0a69-48c0-b367-fc927d90efc7.png">

Your settings should be:
```lua
filetype_hlgroups = {
	scss = {
		TSFunction = { fg = "${cyan}" },
		TSProperty = { fg = "${orange}" },
		TSPunctDelimiter = { fg = "${orange}" },
		TSType = { fg = "${red}" },
	},
}
```

Basically, Treesitter groups nearly everything in an `scss` file as `TSProperty` so we're really limited as to how much detail we can specify for the highlight groups.

**Comment by Asterovim** [comment]
> So after doing some digging, this is the best I can come up with:
> 
> <img alt="Screen Shot 2022-03-08 at 09 08 54@2x" width="900" src="https://user-images.githubusercontent.com/9512444/157204628-e0081c4a-0a69-48c0-b367-fc927d90efc7.png">
> 
> Your settings should be:
> 
> ```lua
> filetype_hlgroups = {
> 	scss = {
> 		TSFunction = { fg = "${cyan}" },
> 		TSProperty = { fg = "${orange}" },
> 		TSPunctDelimiter = { fg = "${orange}" },
> 		TSType = { fg = "${red}" },
> 	},
> }
> ```
> 
> Basically, Treesitter groups nearly everything in an `scss` file as `TSProperty` so we're really limited as to how much detail we can specify for the highlight groups.

Thanks you so much.

Last question please, there is a way to change the color of  "$zurb_color_grey" variable ? 
![image](https://user-images.githubusercontent.com/34446820/157228087-527241f9-4cc0-4a70-8796-c0ce5833e0a1.png)

**Comment by olimorris** [comment]
Running it through `TSPlayground` I get:

<img width="880" alt="Screen Shot 2022-03-08 at 13 12 49@2x" src="https://user-images.githubusercontent.com/9512444/157244899-594e2061-101e-4f60-ab25-f4e878221cd2.png">

Seems Treesitter ignores it. Normally you would expect something like:

<img width="892" alt="Screen Shot 2022-03-08 at 13 13 31@2x" src="https://user-images.githubusercontent.com/9512444/157244970-c200f3f1-14e2-4ddc-97b5-f53dcd6de5d0.png">

**Comment by Asterovim** [comment]
Hi,

I have a code that I would like to use, which looks like this:

require("onedarkpro").setup({
  highlights = {
    ["@variable"] = { fg = "#293184" },
  }
})

I want to apply this code only to SCSS files. Can you give me an example of how to accomplish this please? Also, is it possible to include other file types like .less + .scss ?

Thank you.

**Comment by Asterovim** [comment]
> @Asterovim tnis is covered in the readme under filetype highlighting 👍🏼️

Thanks you.

I have try :
```
require("onedarkpro").setup({
  colors = {
    whiskey = "#d19a66";
  },
  highlights = {
  ["@property.scss"] = { fg = "${whiskey}" },
  }
})
```
It's works.

But, i would like to select @class_name and it didn't work :(

If i use :TSHighlightCapturesUnderCursor my class name is "@property" and my code like (background-color) is also "@property".

any idea ? thanks you.

**Comment by olimorris** [comment]
I've just played around with some SCSS...the Treesitter parser doesn't define many highlights so this will need some custom queries

**Comment by olimorris** [comment]
@Asterovim I've just added additional `scss` support in d7513a7. Had to write some custom Treesitter queries to get it looking okay. Let me know what you think.

## Before

![Screen Shot 2023-03-25 at 12 02 09@2x](https://user-images.githubusercontent.com/9512444/227716202-84d855eb-719f-4673-b5b2-14449003549e.png)

## After

![Screen Shot 2023-03-25 at 12 01 19@2x](https://user-images.githubusercontent.com/9512444/227716175-2f6bb783-93b4-4d74-aa0c-3f30ccad1a34.png)

## Visual Studio Code

![Screen Shot 2023-03-25 at 12 03 42@2x](https://user-images.githubusercontent.com/9512444/227716297-895204f2-9458-403e-9073-0d5324717e6e.png)

**Comment by Asterovim** [comment]
> @Asterovim I've just added additional `scss` support in [d7513a7](https://github.com/olimorris/onedarkpro.nvim/commit/d7513a7d7191571c283fc05d45458a621ac51e93). Had to write some custom Treesitter queries to get it looking okay. Let me know what you think.
> 
> ## Before
> ![Screen Shot 2023-03-25 at 12 02 09@2x](https://user-images.githubusercontent.com/9512444/227716202-84d855eb-719f-4673-b5b2-14449003549e.png)
> 
> ## After
> ![Screen Shot 2023-03-25 at 12 01 19@2x](https://user-images.githubusercontent.com/9512444/227716175-2f6bb783-93b4-4d74-aa0c-3f30ccad1a34.png)
> 
> ## Visual Studio Code
> ![Screen Shot 2023-03-25 at 12 03 42@2x](https://user-images.githubusercontent.com/9512444/227716297-895204f2-9458-403e-9073-0d5324717e6e.png)

Thanks you so mutch. It's very very good.

One question please.

There is a way to improve : after/queries/scss/highlights.scm and lua/onedarkpro/highlights/filetypes/scss.lua via config ?
So i can help you to improve it. I have see another small problem like :
```
@font-face {
  font-family: "important-semi-bold";
  src: url("../../../fonts/Oswald/Oswald-SemiBold.ttf") format("truetype");
}
.testselector {
  &-children {
    color: red;
  }
}
```

VSCODE : 
![image](https://user-images.githubusercontent.com/34446820/227765119-be241543-3471-4b15-9384-bb65661d1a09.png)
![image](https://user-images.githubusercontent.com/34446820/227765167-8e904b9e-96eb-499f-85e5-45ab9b8b8e5e.png)
Neovim :
![image](https://user-images.githubusercontent.com/34446820/227765128-68341784-877c-4380-b07b-08cbaa458c71.png)
![image](https://user-images.githubusercontent.com/34446820/227765163-0eeb0482-71b1-4ac6-a896-17be083b221c.png)

**Comment by olimorris** [comment]
No but you can follow what I did in my commmit and send a PR. ChatGPT is a great tutor for Treesitter queries btw
