### ISSUE TITLE
Terminal screen number bug after gulp

### ISSUE THREAD

**Issue by Asterovim** [olimorris/onedarkpro.nvim#34]
Hello.

I have this bug https://github.com/akinsho/toggleterm.nvim/issues/173 with neovim plugin https://github.com/akinsho/toggleterm.nvim

The bug is only with OneDarkPro, if disabled OneDarkPro, i didn't have any bug.

Can you help me ?

**Comment by olimorris** [comment]
Hmmmm. I use `toggleterm.nvim` too and can say I haven't noticed any issue like this. Do you have any custom filetype highlights?

I do specifically ignore toggleterm's filetype, `toggleterm` in the config when applying filetype highlights.

**Comment by Asterovim** [comment]
Thanks you.

I confirm, if i replace :
```
local onedarkpro = require("onedarkpro")
onedarkpro.setup({
  filetype_hlgroups = {
    scss = {
      TSFunction = { fg = "${cyan}" },
      TSProperty = { fg = "${orange}" },
      TSPunctDelimiter = { fg = "${orange}" },
      TSType = { fg = "${red}" },
    },
  }
})
onedarkpro.load()
```

by just : 
`require('onedarkpro').load()`

It's fixed. 

But i need the custom color :( do you have any tips ?

**Comment by olimorris** [comment]
I wondered if that may stop the issue. I think it's due to [Ignoring filetypes and buffer types](https://github.com/olimorris/onedarkpro.nvim#ignoring-filetypes-and-buffer-types).

Could you try this, in your config:
```lua
filetype_hlgroups_ignore = {
  filetypes = {},
  buftypes = {}
}
```

**Comment by Asterovim** [comment]
> I wondered if that may stop the issue. I think it's due to [Ignoring filetypes and buffer types](https://github.com/olimorris/onedarkpro.nvim#ignoring-filetypes-and-buffer-types).
> 
> Could you try this, in your config:
> 
> ```lua
> filetype_hlgroups_ignore = {
>   filetypes = {},
>   buftypes = {}
> }
> ```
> 
> Edit: Might be worth playing around with `filetypes` and `buftypes` and see what happens.
Thanks.

same bug with : 
```
local onedarkpro = require("onedarkpro")
onedarkpro.setup({
  filetype_hlgroups = {
    scss = {
      TSFunction = { fg = "${cyan}" },
      TSProperty = { fg = "${orange}" },
      TSPunctDelimiter = { fg = "${orange}" },
      TSType = { fg = "${red}" },
    },
  },
  filetype_hlgroups_ignore = {
    filetypes = {},
    buftypes = {}
  }
})
onedarkpro.load()
```
:(

**Comment by olimorris** [comment]
Does it only do it when you're running `gulp`?

Could you try adding the following function to `toggleterm`:

```lua
on_close = function()
  lua require("onedarkpro.utils").set_fhlgroups(true)
end
```

and see if that does anything?

**Comment by Asterovim** [comment]
> Does it only do it when you're running `gulp`?
> 
> Could you try adding the following function to `toggleterm`:
> 
> ```lua
> on_close = function()
>   lua require("onedarkpro.utils").set_fhlgroups(true)
> end
> ```
> 
> and see if that does anything?
I don't understand how to add the function into my config. Could you help me ? Im sorry.

**Comment by olimorris** [comment]
Sorry, should have been more explicit:

```lua
require("toggleterm").setup({
  on_close = function()
    require("onedarkpro.utils").set_fhlgroups(true)
  end
})
```

**Comment by Asterovim** [comment]
> Sorry, should have been more explicit:
> 
> ```lua
> require("toggleterm").setup({
>   on_close = function()
>     require("onedarkpro.utils").set_fhlgroups(true)
>   end
> })
> ```
Thanks you.

I have try the "on_close" and it didn't help :(

**Comment by olimorris** [comment]
What about if you just try:

```lua
require("toggleterm").setup({
  on_close = function()
    require("onedarkpro").load()
  end
})
```
Essentially, I'm wondering if reloading the theme fixes the issue.

**Comment by Asterovim** [comment]
> What about if you just try:
> 
> ```lua
> require("toggleterm").setup({
>   on_close = function()
>     require("onedarkpro").load()
>   end
> })
> ```
> 
> Essentially, I'm wondering if reloading the theme fixes the issue.
Thanks you for your time.
Same problem with this.

**Comment by Asterovim** [comment]
if i use https://github.com/navarasu/onedark.nvim with :
```
local onedark = require("onedark")
onedark.setup({
highlights = {
  TSProperty = { fg = "#c99a6e" },
}
})
onedark.load()
```
I didn't have the bug with gulp (but i have changed the color not only for scss).

I think is very close with the exception of "scss" custom color.

**Comment by Asterovim** [comment]
I confirm, i didn't have the problem with this onedarkpro.nvim config :
```
local onedarkpro = require("onedarkpro")
onedarkpro.setup({
  hlgroups = {
      TSFunction = { fg = "${cyan}" },
      TSProperty = { fg = "${orange}" },
      TSPunctDelimiter = { fg = "${orange}" },
      TSType = { fg = "${red}" },
  }
})
onedarkpro.load()
```

The problem is only with custom color by filetype.

**Comment by olimorris** [comment]
Yeah I have no doubt the theme is causing this issue based on your troubleshooting. I'm just stumped as to how the filetype highlights are causing it.

If you could share your repo, I can run `gulp` and take a look myself. You'll just need to tell me what I need to do to get it setup. Not used gulp in an age!

**Comment by Asterovim** [comment]
> Yeah I have no doubt the theme is causing this issue based on your troubleshooting. I'm just stumped as to how the filetype highlights are causing it.
> 
> If you could share your repo, I can run `gulp` and take a look myself. You'll just need to tell me what I need to do to get it setup. Not used gulp in an age!

https://github.com/Asterovim/test-gulp-neovim.git
need nodeJS version 10.

You could install nvm : https://github.com/nvm-sh/nvm
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
nvm install 10
nvm use 10
```

after that, you can :
`git clone  https://github.com/Asterovim/test-gulp-neovim.git`

`cd test-gulp-neovim`
into ToggleTerm :
```
nvm use 10
gulp
```

I think is related to BrowserSync because if i disabled i didn't have any arror.

Thanks you. Im also looking about BrowserSync...

**Comment by Asterovim** [comment]
> Hey sorry for the slow reply. I haven't had time to test the above. I did try running a `yarn dev` which opened a browser, from within `toggleterm` and I couldn't recreate.
> 
> I wondered what happens if you toggle the line numbers on and off again?

If I toogle the line numbers, it's fix the bug.
But if I remove the line numbers and toggle the terminal i have the bug again (with or without gulp).

**Comment by olimorris** [comment]
> If I toogle the line numbers, it's fix the bug. But if I remove the line numbers and toggle the terminal i have the bug again (with or without gulp).

As a hacky workaround, could you do this:
```lua
require("toggleterm").setup({
  on_close = function()
    vim.cmd([[set nonumber]])
    vim.cmd([[set number]])
  end
})
```
