### ISSUE TITLE
Line number color

### ISSUE THREAD

**Issue by thordossche** [olimorris/onedarkpro.nvim#35]
Hi, 

The colortheme worked perfectly but suddenly the line numbers did change color and i can't find a way to fix it. The linenumbers are some sort of purple? Also the CursorLineNr is not applied anymore.

![1647282173](https://user-images.githubusercontent.com/49074469/158236874-f0760a60-db7f-476d-af02-44a633a41f3e.png)

I tried reinstalling but it did not change anything.

Any ideas where it goes wrong?

**Comment by olimorris** [comment]
Hey @thordossche 👋🏼 .

That is really odd. Have you installed a new plugin which is hijacking the `LineNr` highlight group? I haven't touched that line in months, unfortunately.

**Comment by thordossche** [comment]
The change happened when i installed nvim-tree and was trying to change the colorgroups (which did not work strangely enough). The moment the linenumbers changed color was when i changed the cursorline option to false. 

I removed all my plugins and reinstalled onedarkpro and treesitter but the purple linenumbers still appear even with the default config. I tried to change the color of LineNr to the standard gray: `LineNr = { fg = "#7D828D" },` but it does not apply. 

For CursorLineNr: I can change the color of the CursorLineNr only when i enable the cursorline option.

**Comment by thordossche** [comment]
I finally found it... Its really stupid:
so i source files in my init.vim something like:
```
source plugins
source colorscheme
source settings
...
```
I changed the order and sourced my colorscheme as last and it seemed to work so i checked my settings file and there was the culprit: `highlight LineNr guifg=#fcc4ff guibg=NONE`
I have absolutely no idea how that line got there xp

So the issue is fixed thanks for the help and sorry to waste your time for this...

**Comment by olimorris** [comment]
Not a waste of time at all. I want people to enjoy using the theme as much as I do 😄 .

**Comment by thordossche** [comment]
Well i can assure you I LOVE the theme!! Great work!
