### ISSUE TITLE
The color of OneDarkPro Background is Blue

### ISSUE THREAD

**Issue by KananHasanov747** [olimorris/onedarkpro.nvim#37]
I don't know what I'm doing wrong, because I installed the Plugin through `Plug` and I used the lua script that you can see in photo bellow. How can I solved my problem?

<img width="1680" alt="Screen Shot 2022-03-21 at 18 41 39" src="https://user-images.githubusercontent.com/83110215/159285310-938618dd-ba49-4204-b832-5aaf216c3c64.png">

<img width="778" alt="Screen Shot 2022-03-21 at 18 47 11" src="https://user-images.githubusercontent.com/83110215/159286368-94eae0b4-b537-4cf1-80d1-17af04961a5a.png">

**Comment by olimorris** [comment]
If I repeat this with a minimal config:

```vim
call plug#begin()
Plug 'olimorris/onedarkpro.nvim'
call plug#end()

lua << EOF
require("onedarkpro").load()
EOF
```

and try `nvim --noplugin -u minimal.vim ~/path_to_a_file.lua`, I see it working:

![Screen Shot 2022-03-21 at 16 14 45@2x](https://user-images.githubusercontent.com/9512444/159303859-c12bdcb0-1f07-4122-93cc-26a0022eacd0.png)

I can also see overrides working okay:
```vim
lua << EOF
local onedarkpro = require("onedarkpro")
onedarkpro.setup({
    colors = {
 	bg = "#FFF000"
    },
})
onedarkpro.load()
EOF
```
![Screen Shot 2022-03-21 at 16 14 23@2x](https://user-images.githubusercontent.com/9512444/159303800-9e4b9f8a-7bff-45b6-968c-fed9497bc953.png)

Can you try repeating with a minimal config.

**Comment by KananHasanov747** [comment]
doesn't work

**Comment by KananHasanov747** [comment]
I have the error

<img width="778" alt="Screen Shot 2022-03-21 at 20 32 29" src="https://user-images.githubusercontent.com/83110215/159308797-59129c56-475a-47b1-b2f7-0eeb4a931d95.png">

**Comment by olimorris** [comment]
You need to run `PlugInstall` to install it

**Comment by KananHasanov747** [comment]
Alright, I did it, but problem was not gone

<img width="1680" alt="Screen Shot 2022-03-21 at 20 47 37" src="https://user-images.githubusercontent.com/83110215/159312693-7d3c624b-a5ad-40d6-8d26-ce332d91d8e2.png">

**Comment by olimorris** [comment]
Can you run `nvim --version` and share the output?

**Comment by KananHasanov747** [comment]
<img width="1680" alt="Screen Shot 2022-03-21 at 20 54 35" src="https://user-images.githubusercontent.com/83110215/159318087-182f44ac-d399-4bea-8cb7-bf0aded93b9f.png">

**Comment by KananHasanov747** [comment]
NightFox a little bit works wrong, but it works
<img width="1680" alt="Screen Shot 2022-03-21 at 21 23 15" src="https://user-images.githubusercontent.com/83110215/159329304-eaa0d075-fe45-498c-b612-2611706bdac5.png">
<img width="1680" alt="Screen Shot 2022-03-21 at 21 24 36" src="https://user-images.githubusercontent.com/83110215/159329532-ec357b61-5245-4a57-a202-94fde4068ae8.png">

**Comment by olimorris** [comment]
That looks broken too. Is your terminal showing 24 bit colors?

https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern

**Comment by KananHasanov747** [comment]
I think no
<img width="1680" alt="Screen Shot 2022-03-21 at 21 47 10" src="https://user-images.githubusercontent.com/83110215/159333215-c8431fc5-9ab7-49d3-b574-4c4033ff1dc8.png">

**Comment by KananHasanov747** [comment]
but tmux can
<img width="1680" alt="Screen Shot 2022-03-21 at 21 49 26" src="https://user-images.githubusercontent.com/83110215/159333616-98596fc4-d75c-4908-a495-4da62d1d37f6.png">

**Comment by KananHasanov747** [comment]
Also it works in iTerm2
<img width="1680" alt="Screen Shot 2022-03-21 at 22 08 55" src="https://user-images.githubusercontent.com/83110215/159336888-e60c59e6-18cc-446b-868d-8c6f1448e0b7.png">

**Comment by KananHasanov747** [comment]
Ok thanks for help

**Comment by olimorris** [comment]
Pleasure and enjoy the theme!
