### ISSUE TITLE
FoldColumn is not styled.

### ISSUE THREAD

**Issue by alohaia** [olimorris/onedarkpro.nvim#38]
https://github.com/alohaia/onedarkpro.nvim/blob/46b0ffb97f3778a1f6f5da6471a42f3f64bbf238/lua/onedarkpro/theme.lua#L34

It would be OK to use the same style as `Normal`.

**Comment by olimorris** [comment]
You can implement this in your own config with a custom highlight group. Will play around later

**Comment by alohaia** [comment]
Thanks for your reply. I'm looking forward to it.

**Comment by olimorris** [comment]
@alohaia heads up, I implemented today. Let me know your thoughts

**Comment by alohaia** [comment]
@olimorris I tried it just now, it's exactly what I want, pretty good.
