### ISSUE TITLE
Transparency option didn't work

### ISSUE THREAD

**Issue by soutou233** [olimorris/onedarkpro.nvim#39]
I have copied the default config and changed the transparency option from false to true and reload, but it didn't work. Nvim style reamain the same as before.

**Comment by olimorris** [comment]
It's likely to be your terminal configuration. See config for:

* [Kitty](https://sw.kovidgoyal.net/kitty/conf/)
* [Alacritty](https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L70)
* [Iterm](https://til.hashrocket.com/posts/mc3jexz3m1-iterm-transparency-toggle-)

**Comment by soutou233** [comment]
I use Iterm2 and I believe my terminal setting is alright.

Here is my terminal screenshot:
<img width="1313" alt="Screen Shot 2022-04-11 at 12 56 04 PM" src="https://user-images.githubusercontent.com/38411083/162819483-c01c18da-0de6-428e-a838-91dd21db96ec.png">

Here is my nvim editor screenshot and you can see that the background color is dark.
<img width="1183" alt="Screen Shot 2022-04-11 at 12 56 29 PM" src="https://user-images.githubusercontent.com/38411083/162819605-a120c85d-c29a-4211-9bf0-a55d4ac847a3.png">

**Comment by soutou233** [comment]
I actually found the problem that the transparency do applied, but for some reason it's kinda hard to see it under the nvim environment compare to the original terminal window. LOL

**Comment by olimorris** [comment]
I'm at a loss. This is how it looks for me:

![Screen Shot 2022-04-11 at 21 59 37](https://user-images.githubusercontent.com/9512444/162831370-d2f026e0-32ef-495c-b415-c192bfde9f9b.gif)

Obviously cursorline sucks as I haven't changed it.

What about if you run `:hi Normal`. I just see `Normal xxx guifg=#abb2bf`.

Whereas with transparency off, I see `Normal xxx guifg=#abb2bf guibg=#282c34`.

Maybe another plugin is setting the `Normal` color.

**Comment by soutou233** [comment]
I got these: `
:hi Normal
Normal         xxx guifg=#abb2bf guibg=#282c34`

I think for some reason and transparency didn't work although I have changed the transparency option to true

**Comment by olimorris** [comment]
> I got these: `
> 
> :hi Normal
> 
> Normal         xxx guifg=#abb2bf guibg=#282c34`
> 
> 
> 
> I think for some reason and transparency didn't work although I have changed the transparency option to true

Something is setting your background colour after the theme loads. Search your config for highlights and see what's causing it. The transparency option sets going to be NONE

**Comment by soutou233** [comment]
Solved

**Comment by Lalit64** [comment]
> 

Can you please tell me how you solved it.
