### ISSUE TITLE
Can't override nvim-cmp documentation, documentation border and item menu highlights

### ISSUE THREAD

**Issue by sinkyl** [olimorris/onedarkpro.nvim#42]
Somehow I can't change the nvim-cmp documentation, documentation border and item menu highlights.
I tried:

```
hlgroups = {
    CmpDocumentation = { bg = colors.yellow },
    CmpDocumentationBorder = { bg = colors.blue },
    CmpItemMenu = { bg = colors.perple },
}
```
Nothing changes, onedarkpro keep the default highlights.
![123](https://user-images.githubusercontent.com/24904905/164264443-f7e2b65d-d653-4a2c-b2c5-83d2fd0a7325.png)

**Comment by olimorris** [comment]
If you're trying to use default colors from the theme then it should be:

```lua
hlgroups = {
    CmpDocumentation = { bg = "${yellow}" },
    CmpDocumentationBorder = { bg = "${blue}" },
    CmpItemMenu = { bg = "${purple}" },
}
```
as per https://github.com/olimorris/onedarkpro.nvim#configuring-highlight-groups

**Comment by sinkyl** [comment]
I'm using neovim 0.7 and I found out that nvim-cmp changed the way highlights are configured.
[https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1102917158](https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1102917158)
[https://github.com/hrsh7th/nvim-cmp/pull/472#issuecomment-1098381334](https://github.com/hrsh7th/nvim-cmp/pull/472#issuecomment-1098381334)
With this update I am able to change the background with ``` CmpPmenu = { bg = colors.blue } ```. Now, I'm trying to remove the padding and other little things... Anyway, thanks dude!
