### ISSUE TITLE
Error in theme

### ISSUE THREAD

**Issue by Arjun31415** [olimorris/onedarkpro.nvim#43]
```
Error in packer_compiled: .../start/onedarkpro.nvim/lua/onedarkpro/colors/onedark.lua:38: attempt to call field 'lighten' (a nil value)
```
my config-
```
 use {
            'olimorris/onedarkpro.nvim',
            config = [[require('config.onedarkpro')]]
        }
```
```lua
vim.o.background = "dark" -- to load onedark
local onedarkpro = require("onedarkpro")
local config = {dark_theme = "onedark_vivid", light_theme = "onelight"}

onedarkpro.setup({
    dark_theme = "onedark_vivid", -- The default dark theme
    light_theme = "onelight", -- The default light theme
    -- Theme can be overwritten with 'onedark' or 'onelight' as a string
    theme = function()
        if vim.o.background == "dark" then
            return config.dark_theme
        else
            return config.light_theme
        end
    end,
    colors = {onedark = {bg = '#27292d'}}, -- Override default colors by specifying colors for 'onelight' or 'onedark' themes
    options = {
        bold = false, -- Use the themes opinionated bold styles?
        italic = true, -- Use the themes opinionated italic styles?
        underline = false, -- Use the themes opinionated underline styles?
        undercurl = false, -- Use the themes opinionated undercurl styles?
        cursorline = true, -- Use cursorline highlighting?
        transparency = false, -- Use a transparent background?
        terminal_colors = false, -- Use the theme's colors for Neovim's :terminal?
        window_unfocussed_color = false -- When the window is out of focus, change the normal background?
    }
})
require('onedarkpro').load()

```

**Comment by Arjun31415** [comment]
Seems like a problem with this line 
```
    colors.cursorline = colors.cursorline or utils.lighten(colors.bg, 0.97)
```

**Comment by olimorris** [comment]
If you remove the following lines it should work:

```lua
theme = function()
        if vim.o.background == "dark" then
            return config.dark_theme
        else
            return config.light_theme
        end
    end,
``

This is baked into the normal config by default

**Comment by Arjun31415** [comment]
Actually adding this line -
```
    local utils=require("onedarkpro.utils")
```
in the function definition -
```lua
function M.additional_colors()
```
int `onedark.lua` inside the `colors` folder works too

**Comment by Arjun31415** [comment]
> If you remove the following lines it should work:
> 
> ```lua
> theme = function()
>         if vim.o.background == "dark" then
>             return config.dark_theme
>         else
>             return config.light_theme
>         end
>     end,
> ```
> 
> This is baked into the normal config by default

I took this from the readme actually, Ill remove it now

**Comment by Arjun31415** [comment]
> If you remove the following lines it should work:
> 
> ```lua
> theme = function()
>         if vim.o.background == "dark" then
>             return config.dark_theme
>         else
>             return config.light_theme
>         end
>     end,
> ```
> 
> This is baked into the normal config by default

I got this from [here](https://github.com/olimorris/onedarkpro.nvim/blob/1f6e3bbb20f45648f5680606e5e5d5e881133f1f/README.md?plain=1#L180)

**Comment by olimorris** [comment]
I should have been explicit in the Readme. You're using a lot of config which is actually present by default.

Also, I see your colour overrides are setup for `onedark` and not `onedark_vivid`. Try:

```lua
colors = {onedark_vivid = {bg = '#27292d'}},
```

As you're using the `onedark_vivid` theme, you need to tell the config to apply overrides to that.

**Comment by olimorris** [comment]
Oooooh. That shouldn't happen. Thanks for flagging. I will address this weekend.

**Comment by Arjun31415** [comment]
> Actually adding this line -
> 
> ```
>     local utils=require("onedarkpro.utils")
> ```
> 
> in the function definition -
> 
> ```lua
> function M.additional_colors()
> ```
> 
> in `onedark.lua` inside the `colors` folder works too

This seems to work. But I think passing in config as a parameter to the function would be better. If you want I could raise a PR for the same

**Comment by olimorris** [comment]
I've just pushed a fix. Let me know if that works

**Comment by Arjun31415** [comment]
This works. No errors now

**Comment by olimorris** [comment]
Thanks for raising the issue and testing. Great edge case!

**Comment by Arjun31415** [comment]
Glad to help
