### ISSUE TITLE
Transparency doesn't work on NvimTree when unfocused.

### ISSUE THREAD

**Issue by JannatinNaim** [olimorris/onedarkpro.nvim#44]
So, the transparency only works when the cursor is in the NvimTree window.

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/93467756/168603249-7b0eed96-137a-433f-b5af-0fcd6685bdcf.png">

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/93467756/168603307-a5414314-1879-4343-8a36-3e9d431d0590.png">

**Comment by olimorris** [comment]
Great spot! Can you tell me if the latest commit has fixed it?

**Comment by JannatinNaim** [comment]
Yup, fixed. Thanks. :wink:
