### ISSUE TITLE
Single quotes are broken in JSX.

### ISSUE THREAD

**Issue by JannatinNaim** [olimorris/onedarkpro.nvim#46]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/93467756/169269930-d0b2a8f1-48a4-401c-8aab-2062abf8fb60.png">

I'll let the screenshot speak for itself.

**Comment by olimorris** [comment]
If you have Treesitter-Playground installed, can you run `: TSHighlightCapturesUnderCursor`? It will tell you what the Highlight Group Treesitter has assigned is. I can then look and see what we have set.

I'll be surprised if this is a theme issue.

**Comment by JannatinNaim** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/93467756/169296626-f0b34186-2eaf-46d4-abbc-76b1f1a04ca3.png">

Nuked my config and just installed the theme, the issue still persists.

**Comment by olimorris** [comment]
Can you try:

```lua
local onedarkpro = require("onedarkpro")
onedarkpro.setup({
  hlgroups = {
    TSNone = "#FF0000"
  },
})
onedarkpro.load()
```

**Comment by JannatinNaim** [comment]
And... nothing's changed. :)

<img width="428" alt="image" src="https://user-images.githubusercontent.com/93467756/169326826-d4e0aa3a-6448-493d-b372-2da306dab559.png">

**Comment by olimorris** [comment]
Can you share the filename and code so I can test?

**Comment by JannatinNaim** [comment]
It's just a JSX file. The following code on a JSX file has the issue too.

```javascript
const Index = () => {
  return <div>
    Here's some text with a ' in it.
  </div>;
};

export default Index;
```

**Comment by olimorris** [comment]
Really weird...this is what I'm seeing:

<img width="489" alt="Screen Shot 2022-05-19 at 18 48 43@2x" src="https://user-images.githubusercontent.com/9512444/169364962-ed58a4e0-b3d4-4048-bb1c-18f1b17ff668.png">

**Comment by JannatinNaim** [comment]
:) Luck seems to have left my side.

**Comment by olimorris** [comment]
Never give up!

Maybe try reinstalliing Treesitter. I had an issue with it a while back and had to delete all of the parsers off the hard drive and reinstall.

**Comment by JannatinNaim** [comment]
Like I said, I nuked my entire installation and everything (that .local/share/nvim too). I even recently reset my entire Mac and this issue was present back then too. I really don't see any other thing I can try right now.

**Comment by olimorris** [comment]
Yeah I agree! So sorry! Can you send me the file from your earlier post too? I'll give that a try

**Comment by olimorris** [comment]
Ah damn, it seems to look fine:

<img width="1188" alt="Screen Shot 2022-05-19 at 19 13 05@2x" src="https://user-images.githubusercontent.com/9512444/169371401-5b5e98d2-1cc5-4edd-a7f5-fa2a84c97846.png">

Do you just have the default settings for theme?

**Comment by JannatinNaim** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/93467756/169371686-58ad963b-820b-42e5-81f7-441912dac084.png">

Here's the config file I'm using.

**Comment by JannatinNaim** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/93467756/169378590-c5312982-6df0-43c6-8c15-01f8fe578675.png">

One day or another I'm going to get this fixed. :)

**Comment by olimorris** [comment]
Other than disabling all plugins except this and treesitter, I'm out of ideas 😢

**Comment by olimorris** [comment]
Damn! So sorry. Please keep me posted.

Let's leave this ticket open in case anyone can help out

**Comment by JannatinNaim** [comment]
For anyone that might have the same as me, IDK what the solution is. I've tried everything I could, not fixed. I'll close this issue for now.

NOTE: I'm on an M1 Mac (idk if that' useful).

**Comment by olimorris** [comment]
The only issue I can think is trying Neovim 0.7 and not nightly. I tested on 0.7 and couldn't replicate.

Could you share your neovim health check too?

**Comment by JannatinNaim** [comment]
# Health Check

null-ls: require("null-ls.health").check()
========================================================================
  - OK: cspell: the command "cspell" is executable.
  - OK: trim_newlines: the command "awk" is executable.
  - OK: trim_whitespace: the command "awk" is executable.
  - OK: stylua: the command "stylua" is executable.
  - OK: prettier: the command "prettier" is executable.
  - OK: eslint: the command "eslint" is executable.
  - OK: eslint: the command "eslint" is executable.
  - OK: eslint: the command "eslint" is executable.
  - OK: autopep8: the command "autopep8" is executable.
  - OK: flake8: the command "flake8" is executable.
  - OK: markdownlint: the command "markdownlint" is executable.
  - OK: markdownlint: the command "markdownlint" is executable.
  - OK: zsh: the command "zsh" is executable.
  - OK: gitlint: the command "gitlint" is executable.
  - OK: proselint: the command "proselint" is executable.
  - INFO: dictionary: cannot verify if the command is an executable.
  - INFO: gitsigns: cannot verify if the command is an executable.
  - INFO: refactoring: cannot verify if the command is an executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.2 darwin/arm64`
  - OK: **cargo**: `cargo 1.61.0 (a028ae42f 2022-04-29)`
  - OK: **luarocks**: `/Users/jannatinnaim/.asdf/installs/lua/5.4.4/luarocks/bin/luarocks 3.9.0`
  - OK: **Ruby**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`
  - OK: **RubyGem**: `3.3.7`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.5.5`
  - OK: **node**: `v16.15.0`
  - OK: **python3**: `Python 3.9.13`
  - OK: **pip3**: `pip 22.0.4 from /Users/jannatinnaim/.asdf/installs/python/3.9.13/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **javac**: `javac 18`
  - OK: **java**: `Ok`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 2. Remaining: 58. Limit: 60. Reset: Thu Jun  9 00:40:24 2022.

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - bash           ✓ ✓ ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - css            ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /Users/jannatinnaim/.asdf/shims/python3
  - INFO: Other python executable: /opt/homebrew/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.13
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v16.15.0
  - INFO: Nvim node.js host: /Users/jannatinnaim/.asdf/installs/nodejs/16.15.0/.npm/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/jannatinnaim/.cache/nvim/lsp.log
  - INFO: Log size: 113 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for json5: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13

**Comment by JannatinNaim** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/93467756/172682511-f60e34a4-fa29-4119-92f0-75f8373b115c.png">

I seem to be on v0.7.0 too.

**Comment by JannatinNaim** [comment]
I made a docker image with the minimal config. You can get it from here.
https://hub.docker.com/r/jannatinnaim/neovim_minimal

This is what it looks like still.
<img width="417" alt="image" src="https://user-images.githubusercontent.com/93467756/172728397-e431d3bf-8a74-4e65-8a1e-d84a41a058ef.png">

The `index.jsx` file is in `/root/index.jsx`.

**Comment by olimorris** [comment]
Awesome! Will check it out tomorrow

**Comment by olimorris** [comment]
Is everything installed btw? What commands should I use to open Neovim?

**Comment by JannatinNaim** [comment]
Yup, everything is set up so just open neovim as usual.

**Comment by olimorris** [comment]
Okay...confirmed I see the same error as you. I solved it by removing `additional_vim_regex_highlighting = true` in your treesitter config.

**Comment by JannatinNaim** [comment]
All that pain I went through, for this. :) Thanks a lot.

(I honestly didn't know how docker worked so learnt something new because of this 😆)

**Comment by olimorris** [comment]
My pleasure and glad I could help. One of those situations where an external pair of eyes goes a long way.

The Docker Image was a beautiful idea. Definately work getting people to do that for any really complex issues in the future so thanks.
