### ISSUE TITLE
Telescope lose transparency and border after commit 2cf7324

### ISSUE THREAD

**Issue by EvaristeFan** [olimorris/onedarkpro.nvim#47]
Befor the commit:
![2022-05-26_11-27](https://user-images.githubusercontent.com/84007968/170410191-7ccd8b6a-578f-4657-ac1a-f2868011635c.png)
After the commit that is like the style in README, which has no borders and transparency.

**Comment by olimorris** [comment]
This should be fixed. Thanks for flagging

**Comment by olimorris** [comment]
I have altered how Telescope looks in OneDark but if anything looks weird, let me know and I can accomodate

**Comment by EvaristeFan** [comment]
That works. Thanks.
