### ISSUE TITLE
nvim-cmp hlgroup. (and telescope title)

### ISSUE THREAD

**Issue by Lalit64** [olimorris/onedarkpro.nvim#49]
Hey @olimorris, I can't seem to find the hlgroup for nvim-cmp selected item. I have tried PmenuSel but it doesn't seem to work. This also applies to telescope or any popup menu/float. I get this very light color. ↓

<img width="2662" alt="Screenshot 2022-06-05 at 16 05 39" src="https://user-images.githubusercontent.com/79628080/172054516-22a0244a-57fa-47c9-abd4-3212be22a2d7.png">

<img width="2662" alt="Screenshot 2022-06-05 at 16 07 29" src="https://user-images.githubusercontent.com/79628080/172054590-77ad401d-4af6-4d29-9409-22e41e65d347.png">

I also only noticed now that the Telescope title is very light. Any way to fix these ?

**Comment by olimorris** [comment]
Hmmmm. That is odd. Telescope should look like the pic in the Readme. Could you share your config and run `:hi TelescopeResultsTitle` and share the output.

**Comment by Lalit64** [comment]
Config is at https://gitHub.com/lalit64/HydroVim ignore the readme it's under construction. I just need to push the latest changes. Can I talk to you and push the changes tomorrow I am the SAST time zone and it's pretty late for me now. I have school tomorrow so I have to go to bed.

**Comment by olimorris** [comment]
No problem. I'm on holiday at the moment on Pacific Time so will check later on for any updates

**Comment by Lalit64** [comment]
> No problem. I'm on holiday at the moment on Pacific Time so will check later on for any updates

I have pushed the changes. Check them out. Also my iTerm2 background color is #232832;

**Comment by olimorris** [comment]
Can't see anything obvious...

Can you run `:hi TelescopeResultsTitle` and let me know the output?

**Comment by Lalit64** [comment]
<img width="1384" alt="Screenshot 2022-06-07 at 08 08 20" src="https://user-images.githubusercontent.com/79628080/172307859-ec13dc8d-724e-4e72-8b72-e127d97c0b93.png">

How about the cmp. Output for `:hi TelescopeResultsTitle` is above

**Comment by olimorris** [comment]
Regarding cmp, it should be the `Pmenu` highlights that affect it. Have you tried `PmenuSbar`?

**Comment by Lalit64** [comment]
@olimorris Should I be targeting the PmenuSbar bg or fg?

**Comment by olimorris** [comment]
Can you run the `:hi` command for all `Pmenu` groups and confirm if the hex codes match the colors when you use cmp?

**Comment by Lalit64** [comment]
I do have a custom CMP config but that shouldn't change anything.

Take a look at it below.

```lua
local has_words_before = function()
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

local luasnip = require("luasnip")
require("luasnip.loaders.from_vscode").load()
local cmp = require("cmp")
local cmp_autopairs = require("nvim-autopairs.completion.cmp")
cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done({ map_char = { tex = "" } }))
cmp_autopairs.lisp[#cmp_autopairs.lisp + 1] = "racket"

local kind_icons = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "ﰠ",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "פּ",
    Event = "",
    Operator = "",
    TypeParameter = "",
}

local mapping = {
    ["<C-d>"] = cmp.mapping.scroll_docs(-4),
    ["<C-f>"] = cmp.mapping.scroll_docs(4),
    ["<C-e>"] = cmp.mapping({
        i = cmp.mapping.abort(),
        c = cmp.mapping.close(),
    }),
    ["<CR>"] = cmp.mapping({
        i = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true }),
        c = function(fallback)
            if cmp.visible() then
                cmp.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true })
            else
                fallback()
            end
        end,
    }),
    ["<Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
            cmp.select_next_item()
        elseif luasnip.expand_or_jumpable() then
            luasnip.expand_or_jump()
        elseif has_words_before() then
            cmp.complete()
        else
            fallback()
        end
    end, { "i", "s" }),
    ["<S-Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
            cmp.select_prev_item()
        elseif luasnip.jumpable(-1) then
            luasnip.jump(-1)
        else
            fallback()
        end
    end, { "i", "s" }),
    ["<C-Space>"] = cmp.mapping(cmp.mapping.complete(), { "i", "c" }),
    ["<Down>"] = cmp.mapping(cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }), { "i", "c" }),
    ["<Up>"] = cmp.mapping(cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }), { "i", "c" }),
}

cmp.setup({
    completion = { comp232832leteopt = "menu,menuone,noinsert" },
    snippet = {
        expand = function(args)
            luasnip.lsp_expand(args.body)
        end,
    },
    mapping = mapping,
    sources = {
        { name = "nvim_lsp" },
        { name = "buffer", keyword_length = 2 },
        { name = "luasnip" },
        { name = "path", max_item_count = 10 },
    },
    formatting = {
        format = function(entry, vim_item)
            -- Kind icons
            vim_item.kind = string.format("%s %s", kind_icons[vim_item.kind], vim_item.kind)
            -- Source
            -- vim_item.menu = ({
            --     buffer = "[Buffer]",
            --     nvim_lsp = "[LSP]",
            --     luasnip = "[LuaSnip]",
            --     path = "[Path]",
            -- })[entry.source.name]
            return vim_item
        end,
    },
    window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered()
    },
})
```

**Comment by olimorris** [comment]
I can't really help you beyond this unfortunately. To close this out Is recommend the below approach:

- Change `Pmenu` and `PmenuSel` highlight groups to an fg and bg of `#FF0000`. You can see how to do this in the Readme of the plugin.
- Reload Neovim
- Observe if cmp has changed color
- If not, run `:hi Pmenu` and see what the color is. This will indicate another plugin is changing the highlight for Pmenu.

Alternatively, create a minimal config of just onedarkpro and cmp and see if that solves it.

**Comment by Lalit64** [comment]
I have made a minimal config and it seems to be working now. I'm not sure what the issue is in my config.

**Comment by dvalnn** [comment]
> I have made a minimal config and it seems to be working now. I'm not sure what the issue is in my config.
> 
> Edit: I have found the issue 😑! It seems to be nvim-cmp when using
> 
> ```lua
> completion = cmp.config.window.bordered(),
> documentation = cmp.config.window.bordered()
> ```
> 
> Edit 2: Opened an issue in nvim-cmp repository.

Hi!
I have run into the same problem when using those same window options. 
Has your issue been resolved yet upstream? Could you post a link to the solution/ongoing discussion?
