### ISSUE TITLE
Disable autoload on setup

### ISSUE THREAD

**Issue by axieax** [olimorris/onedarkpro.nvim#55]
Would it be possible to disable the autoload behaviour from 5d90d33672521524eda7005ee1e773cfd5816ac6? I have multiple colorschemes enabled and use this plugin as a secondary colorscheme, so overriding the colorscheme by automatically loading it is messing with all my configs. Thanks!

**Comment by olimorris** [comment]
Can't you have a conditional in your config to determine whether to load onedark? I'm reluctant to change this as it was always a bit odd that I had a separate `load` function when most other plugins just have `setup`

**Comment by axieax** [comment]
Most plugins have a `setup` function to set their config and settings. Even for other colorscheme plugins, the theme is only activated when desired with `:colorscheme xxx`.

**Comment by olimorris** [comment]
Yeah that's a fair point! Should be reverted now and thanks for raising the issue.
