### ISSUE TITLE
return config.dark_theme error Default configuration

### ISSUE THREAD

**Issue by xMonody** [olimorris/onedarkpro.nvim#56]
![RV0J2HPAM}$ %N7`~9 C2@9](https://user-images.githubusercontent.com/76483540/178147925-5969514e-b8ca-498f-ba37-1979db14b98d.png)

**Comment by olimorris** [comment]
Can you share your config? I can't replicate this

**Comment by xMonody** [comment]
require("onedarkpro").setup({
  dark_theme = "onedark", -- The default dark theme
  light_theme = "onelight", -- The default light theme
  -- Theme can be overwritten with 'onedark' or 'onelight' as a string
  theme = function()
      if vim.o.background == "dark" then
          return config.dark_theme
      else
          return config.light_theme
      end
  end,
  colors = {}, -- Override default colors by specifying colors for 'onelight' or 'onedark' themes
  hlgroups = {}, -- Override default highlight groups
  filetype_hlgroups = {}, -- Override default highlight groups for specific filetypes
  plugins = { -- Override which plugins highlight groups are loaded
      native_lsp = true,
      polygot = true,
      treesitter = true,
      -- NOTE: Other plugins have been omitted for brevity
  },
  styles = {
      strings = "NONE", -- Style that is applied to strings
      comments = "NONE", -- Style that is applied to comments
      keywords = "NONE", -- Style that is applied to keywords
      functions = "NONE", -- Style that is applied to functions
      variables = "NONE", -- Style that is applied to variables
      virtual_text = "NONE", -- Style that is applied to virtual text
  },
  options = {
      bold = false, -- Use the themes opinionated bold styles?
      italic = false, -- Use the themes opinionated italic styles?
      underline = false, -- Use the themes opinionated underline styles?
      undercurl = false, -- Use the themes opinionated undercurl styles?
      cursorline = false, -- Use cursorline highlighting?
      transparency = false, -- Use a transparent background?
      terminal_colors = false, -- Use the theme's colors for Neovim's :terminal?
      window_unfocussed_color = false, -- When the window is out of focus, change the normal background?
  }
})

**Comment by olimorris** [comment]
I think this may have been fixed in the latest commit. Could you check?

By the way, you can format a code block on GitHub with three `. Makes it easier for us to read.

**Comment by xMonody** [comment]
Thank you for the update
