### ISSUE TITLE
Question: how to setup the theme properly for python?

### ISSUE THREAD

**Issue by rb-one** [olimorris/onedarkpro.nvim#57]
Hi 

Your theme is awesome it's the reason that I'm trying to switch from vim to nvim, I'm trying to get the same results as the images that you share, but at the moment (since I downloaded the theme) the name of the variables and most of the text is in gray, only the name of functions, objects , primitive types and keywords of the language are in colors, name of the variables and arguments of functions are in gray too.

Besides the vim plug part this is my config on init.vim file

`
" Vim Colors Configuration
syntax enable
syntax on
set cursorline

if exists('+termguicolors')
  "let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  "let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

set t_Co=256

colorscheme onedarkpro

`

**Comment by olimorris** [comment]
👋🏼 @rb-one! Hope you're great.

Have you installed Treesitter and enabled syntax highlighting?

**Comment by rb-one** [comment]
Hi @olimorris, thanks for asking, I'm just recovering from covid this week, my bad, I did not install Treesitter, now everything is beautiful thanks for your advice and time.

**Comment by olimorris** [comment]
Most importantly I hope you're recovering and feeling better! And when you get to try the theme out properly, I hope you really enjoy it.

**Comment by rb-one** [comment]
Thanks a lot Oli, I will enjoy it 😃
