### ISSUE TITLE
Missing information for the Spell* highlights

### ISSUE THREAD

**Issue by cazador481** [olimorris/onedarkpro.nvim#58]
The SpellBad, SpellCap, SpellLocal, and SpellRare are not set in onedarkpro

**Comment by olimorris** [comment]
Great shout! Any suggestions on colours? Guessing bad is red.

**Comment by cazador481** [comment]
I think red with an underline, or squiggly would work nicely.

**Comment by olimorris** [comment]
For all of the groups above?

**Comment by cazador481** [comment]
For all groups is fine.

**Comment by cazador481** [comment]
Looks great thanks.
