### ISSUE TITLE
Dark highlight with some plugins

### ISSUE THREAD

**Issue by otavioschwanck** [olimorris/onedarkpro.nvim#60]
Plugins like:
- https://github.com/ggandor/lightspeed.nvim
- danilamihailov/beacon.nvim

The color for highlight is black.
![Kapture 2022-07-20 at 13 21 55](https://user-images.githubusercontent.com/9551316/179980567-15807199-756a-4e79-a18b-c5f16a5c6c02.gif)

**Comment by olimorris** [comment]
Btw...is this a Beacon issue and not Lightspeed?

**Comment by otavioschwanck** [comment]
> Btw...is this a Beacon issue and not Lightspeed?

Lightspeed!

**Comment by olimorris** [comment]
So this was an issue with the `Cursor` highlight group! Great spot and hopefully this is resolved.

**Comment by otavioschwanck** [comment]
Fixed!
