### ISSUE TITLE
Question: how to configure this element?

### ISSUE THREAD

**Issue by dpo** [olimorris/onedarkpro.nvim#66]
Thank you for this beautiful theme! My only gripe is that this element is displayed in a color that makes it hard to read (in my opinion) when using the light theme:
![Screen Shot 2022-08-05 at 19 57 41](https://user-images.githubusercontent.com/38760/183224890-ef73390e-b137-4584-86ee-7564de7bd065.png)

What is that element called and how can I change its colors?

Thank you!

**Comment by olimorris** [comment]
Thanks and glad you like it.

Is that your statusline? If you have `nvim-treesitter/playground` you can run `TSHighlightCapturesUnderCursor` to understand what is applying the highlight.

**Comment by dpo** [comment]
Yes it's the status line. I can't go there with the cursor though?!

**Comment by olimorris** [comment]
You'll need to share your statusline config. Suspect it's applying some highlights for you

**Comment by olimorris** [comment]
I've not heard back from you in a few days so wanted to send over some pointers:

- If you're using a plugin for your statusline, I'd refer to the documentation of that plugin for how you apply highlight groups
- You can create custom highlight groups with this color scheme in your config
- If you're "rolling your own" statusline then I recommend this [gist](https://gist.github.com/romainl/58245df413641497a02ffc06fd1f4747). I used this in my Vim days
- You can still use this color scheme to create your own highlight groups as well

**Comment by dpo** [comment]
Thanks for the help + pointers, and sorry for the delay. I'm using LunarVim. I asked on their Discord but didn't hear back. At this point I'm not sure how to configure that element.

**Comment by olimorris** [comment]
It looks like LunarVim uses `Lualine` out of the box and we have a Lualine theme in built into the plugin.

What if you try overwriting the `bg_statusline` or `fg_gutter` highlight groups? Those are the ones that I use in this color schemes lualine plugin.

**Comment by dpo** [comment]
Thank you so much @olimorris and @mmirus ! Turns out `fg_gutter` is the thing! Sorry if this seemed like a basic RTFM question. Coming from plain vim, there's a learning curve to configuring things with lua. Thanks for your patience!

**Comment by mmirus** [comment]
Glad you got it working the way you want!
