### ISSUE TITLE
Change `SignColumn` and `LineNr` for unfocused windows?

### ISSUE THREAD

**Issue by mrjones2014** [olimorris/onedarkpro.nvim#68]
First of all hi 👋  and this colorscheme looks amazing

I love the option to lighten the bg of inactive windows, is there a way to make it also apply to the sign and number columns?

**Comment by mrjones2014** [comment]
Also, is there a way to customize the unfocused color?

**Comment by mrjones2014** [comment]
Figured it out -- you can achieve this by setting `hlgroups.SignColumn` and `hlgroups.LineNr` to the same color as `colors.color_column`

**Comment by olimorris** [comment]
👋🏼 @mrjones2014 ! It's been a while and you're awesome.

Glad you figured it out and thanks for your kind words. There's a big [rewrite](https://github.com/olimorris/onedarkpro.nvim/tree/develop) coming soon which should make things more zippy too
