### ISSUE TITLE
Need some help fine-tuning the syntax highlighting for Python 

### ISSUE THREAD

**Issue by anthony-S93** [olimorris/onedarkpro.nvim#70]
Hi, Oli. This technically isn't an issue. I just need some help because I am so new at this, having switched to Neovim from VSCode less than 24 hours ago. 

Before I describe the problems I'm having, let me first clarify that I already have the following installed: 
1) nvim-treesitter
2) nvim-lspconfig

![Side By Side](https://user-images.githubusercontent.com/69449791/184296090-d30f0b25-a6c2-4eaf-8451-43d7696ca8cd.jpg)

This picture showed some Python code I wrote for demo purposes. The .py file was opened by two applications: vscode on the left, and neovim on the right. 

Here, I'm trying to do two things:
1) Get the Python modules in the import statements to have a color of their own (the syntax highlighting in vscode changes module names to yellow)
2) Get the Python built-in functions to be in the correct color (blue)
3) Get the variable \_\_name\_\_ to be in the correct color (red; see left picture)

This is the config code in my `.config/nvim/init.vim` file:

```
lua <<END
require("onedarkpro").setup({
    theme = "onedark_vivid",
    colors = {},
    hlgroups = {},
    filetype_hlgroups = {
	    python = {
			TSFunction = { fg = "${blue}"},
			TSParemeter = { fg = "${red}", style = "italic" },
			TSModule = { fg = "${yellow}" }
	    }	
	},
    plugins = {},
    styles = { -- Choose from "bold,italic,underline"
      strings = "NONE", -- Style that is applied to strings.
      comments = "NONE", -- Style that is applied to comments
      keywords = "NONE", -- Style that is applied to keywords
      functions = "NONE", -- Style that is applied to functions
      variables = "NONE", -- Style that is applied to variables
      virtual_text = "NONE", -- Style that is applied to virtual text
    },
    options = {
      bold = false, -- Use the themes opinionated bold styles?
      italic = false, -- Use the themes opinionated italic styles?
      underline = false, -- Use the themes opinionated underline styles?
      undercurl = false, -- Use the themes opinionated undercurl styles?
      cursorline = false, -- Use cursorline highlighting?
      transparency = true, -- Use a transparent background?
      terminal_colors = false, -- Use the theme's colors for Neovim's :terminal?
      window_unfocussed_color = false, -- When the window is out of focus, change the normal background?
  }
})
END
```
As you can see, I tried adding the following to the filetype_hlgroups list: 
```
python = {
			TSFunction = { fg = "${blue}"},
			TSModule = { fg = "${yellow}" 
}
```
But that didn't help at all. Python built-in functions (print, len, etc) didn't change to blue and modules still have the same color as variables. What am I missing here?

The syntax highlighter in VScode is also smart enough to know that the \_\_repr\_\_ is a special operator overloading method, so it gave \_\_repr\_\_ the same color as operators like +, =, etc. What do I need to configure to obtain the same effect?

**Comment by olimorris** [comment]
👋🏼 @anthony-S93.

Firstly, I recommend installing `treesitter-playground` as you can then use the awesome `: TSHighlightCapturesUnderCursor` which tells you what night Treesitter has applied. I am getting a few questions on this recently so will update the README.md.

Secondly, you don't need all that config. If you're just changing a few items from the defaults then just include those. Keeps things much simpler and means that if I change any defaults in the future, you won't run into any deprecation warnings.

Hope you're enjoying the theme.

**Comment by anthony-S93** [comment]
Hello @olimorris 

Thanks for the tip. I'm gonna install treesitter-playground right now. 

And at the risk of sounding completely stupid, by "configs" do you mean the ones that I left empty? I should remove those?

**Comment by olimorris** [comment]
Only include the items in the config that you've changed from the defaults in the README 👍🏼

**Comment by anthony-S93** [comment]
@olimorris 
![TSPlayground](https://user-images.githubusercontent.com/69449791/184304835-2e7abb80-90ea-44d6-a16d-f079e2e3c086.jpg)

Okay. So TS Playground showed me this. So it says that "len" is a function, which is to be expected. So what config should I add so that it will be in blue, which is the color that was set in the `theme.lua` file for functions?

**Comment by anthony-S93** [comment]
![Screenshot_2022-08-12_15-40-51](https://user-images.githubusercontent.com/69449791/184308075-f585c83b-403c-47d4-bea1-f007ebf23f44.jpg)

What a helpful tool indeed! So I just need to add 'TSFuncBuiltin' under filetype_hlgroups to change the colors, correct?

**Comment by olimorris** [comment]
Nice!! Yeah it's super powerful. I use Operator Mono as a font so I experiment with bolds and italics quite a lot in my filetype highlights:

<img width="853" alt="Screen Shot 2022-08-12 at 09 13 07@2x" src="https://user-images.githubusercontent.com/9512444/184313335-48eb1f54-c79e-4a1e-87d1-24a748f0d3d0.png">

**Comment by anthony-S93** [comment]
Thank you for your guidance and for creating this awesome theme!

**Comment by olimorris** [comment]
Btw...feel free to check out my [dotfiles](https://github.com/olimorris/dotfiles) at any point. I've been on Lua Neovim for ages so more than happy to offer some advice.

In terms of plugins that are worth checking out for Python development:

- [Neotest](https://github.com/nvim-neotest/neotest)
- [Refactoring.nvim](https://github.com/ThePrimeagen/refactoring.nvim)

I think both of those will make a material difference to your productivity!

I also recommend:

- [Hop.nvim](https://github.com/phaazon/hop.nvim) - For navigating the visible screen faster
- [Aerial.nvim](https://github.com/stevearc/aerial.nvim) - For navigating a whole buffer faster and logically
