### ISSUE TITLE
You don't need to fork this to add your own colors, highlight groups etc.

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedarkpro.nvim#71]
I've noticed a lot of people fork this color scheme to add custom colors and highlight groups, or, to override a theme's defaults.

This color scheme has been designed to allow you to customise _nearly everything_ all from within the `setup` function. The below are links on how to achieve this from the readme:

- [Create your own colors or override a theme's defaults](https://github.com/olimorris/onedarkpro.nvim#configuring-colors)
- [Create your own highlight groups or override a theme's defaults](https://github.com/olimorris/onedarkpro.nvim#configuring-highlight-groups)
- [Create highlight groups for specific filetypes](https://github.com/olimorris/onedarkpro.nvim#configuring-filetype-highlight-groups)

**Comment by olimorris** [comment]
@AnasR7 - FYI

**Comment by AnasR7** [comment]
Okay, thank you for your information.
And gift me the tips for changing the color.

**Comment by olimorris** [comment]
@roadupcc - FYI

**Comment by roadupcc** [comment]
> @roadupcc - FYI

@olimorris how to change color for menu selection item (bg or fg)?
<img width="315" alt="image" src="https://user-images.githubusercontent.com/18000037/191140620-fd541663-2f88-4e27-9186-911918b77e5a.png">

**Comment by olimorris** [comment]
> > @roadupcc - FYI
> 
> 
> 
> @olimorris how to change color for menu selection item (bg or fg)?
> 
> <img width="315" alt="image" src="https://user-images.githubusercontent.com/18000037/191140620-fd541663-2f88-4e27-9186-911918b77e5a.png">
> 
> 
> 
> 

Might be `Pmenu` highlight groups. Search the repo for menu groups

**Comment by roadupcc** [comment]
@olimorris 
I added these options, but they don't seem to be all in effect, is there a bug in my configuration?

<img width="336" alt="image" src="https://user-images.githubusercontent.com/18000037/192128596-3b5c063a-1ec8-4157-9dca-4c4d69a899ab.png">

**Comment by olimorris** [comment]
@roadupcc - can we move this to a new issue item to avoid clogging this please?

**Comment by ahmed-rezk-dev** [comment]
highlights stoped working after updating??

**Comment by olimorris** [comment]
@stanleykozak - You could actually recreate your fork with [custom colors](https://github.com/olimorris/onedarkpro.nvim#configuring-colors) and [custom highlight groups](https://github.com/olimorris/onedarkpro.nvim#configuring-highlight-groups). That way you can stay in sync in the main theme

**Comment by AnasR7** [comment]
okay, thanks for your information. sorry for really2 being late replying.

**Comment by AnasR7** [comment]
i will delete the project and using in my config thanks for sharing I'm still newbie in this neovim config.
