### ISSUE TITLE
setup config does not work anymore as expected

### ISSUE THREAD

**Issue by dstadelm** [olimorris/onedarkpro.nvim#75]
Since commit d7b79bd2b1bae98a0c9bef25773c6d3ff828aa3 "full rewrite of the plugin" the setup function as documented throws an error if reloaded.

This is using the configuration setup from the README.md

```
Error detected while processing BufWritePost Autocommands for "*.lua"..script /home/user/.config/nvim-lua/lua/config/onedarkpro_config.lua:
E5113: Error while calling lua chunk: ...ack/packer/start/onedarkpro.nvim/lua/onedarkpro/init.lua:27: attempt to call field 'colors' (a table value)
stack traceback:
        ...ack/packer/start/onedarkpro.nvim/lua/onedarkpro/init.lua:27: in function 'setup'
        ...user/.config/nvim-lua/lua/config/onedarkpro_config.lua:4: in main chunk
```

**Comment by olimorris** [comment]
Can you share the autocommand you're using?

**Comment by dstadelm** [comment]
There is no autocmd
I load the setup in the packer config section

**Comment by dstadelm** [comment]
Also I've noticed there is no highlight for spell anymore, but that might be related.

**Comment by olimorris** [comment]
Can you re-create this issue and follow the `minimal.lua` file I have in the issue template? You're the first person to file an issue after the rewrite and the spell highlight groups are definately present.

I've tried pasting the default config from `README.md` and it works.
