### ISSUE TITLE
No spell highlighting

### ISSUE THREAD

**Issue by dstadelm** [olimorris/onedarkpro.nvim#76]
**Test with minimal.lua file**
Firstly, please test with the minimal.lua file contained within this [issue](https://github.com/olimorris/onedarkpro.nvim/issues/53). It will automatically download Packer and onedarkpro into a temp folder! No need to mess around or edit your existing config. However you will need to restart Neovim.
[x] done

**Describe the bug**
Enabling spell does not highlight the spelling mistakes

**System information**
- OS: linux ubuntu 22.04
- Neovim version (`nvim --version`): NVIM v0.8.0-dev-957-g946c0aa66
- onedarkpro config: (only using the minimal.lua)
```lua
None
```

**To reproduce**
1. nvim --clean -u minimal.lua minimal.lua
2. `:set spell spelllang=en` 
![Screenshot-2022-08-26-17:32:42](https://user-images.githubusercontent.com/3010527/186944094-e39a1968-d9cb-4cd5-a0d5-2d662aa25eb2.png)
3. :colorscheme default
![Screenshot-2022-08-26-17:33:05](https://user-images.githubusercontent.com/3010527/186944208-375d4d15-410d-49f8-b7e5-8ebd2d9b2720.png)

**Comment by dstadelm** [comment]
My current workaround is to set 
SpellBad, SpellCap, SpellRare, SpellLocal to some values (in my case the same as I use for diagnostics.
```lua

 highlights = {
           SpellBad = { fg = "#8b3434", bg = "#2a252b", style = "italic" },
           SpellCap = { fg = "#835d1a", bg = "#292928", style = "italic" },
           SpellRare = { fg = "#48b0bd", bg = "#25252b",  style = "italic" },
           SpellLocal = { fg = "#7e3992", bg = "#292534", style = "italic" },
           DiagnosticVirtualTextError = { fg = "#8b3434", bg = "#2a252b", style = "italic" },
           DiagnosticVirtualTextWarn = { fg = "#835d1a", bg = "#292928", style = "italic" },
           DiagnosticVirtualTextInfo = { fg = "#48b0bd", bg = "#25252b",  style = "italic" },
           DiagnosticVirtualTextHint = { fg = "#7e3992", bg = "#292534", style = "italic" },
           Pmenu = {bg = utils.darken("#1e2127", 0.4)},
           PmenuSel = {bg = utils.lighten("#1e2127", 0.8)},
           NormalFloat = {bg = utils.darken("#1e2127", 0.4)},
  },

```

**Comment by olimorris** [comment]
Hoping this should be fixed in the latest commit. Please let me know.

**Comment by olimorris** [comment]
@dstadelm any update on if this is now working?

**Comment by dstadelm** [comment]
Sorry, yes it is working now as expected. Thank you for all the hard work you're putting into you're theme!

**Comment by olimorris** [comment]
My pleasure and glad you're enjoying it.
