### ISSUE TITLE
treesitter overrides not working after nvim breaking changes

### ISSUE THREAD

**Issue by petobens** [olimorris/onedarkpro.nvim#79]
Consider the following minimal.lua file:
```lua
local fn = vim.fn

-- Ignore default config and plugins and define new dirs
local test_dir = '/tmp/nvim-minimal'
vim.opt.runtimepath:remove(fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(fn.expand('~/.local/share/nvim/site'))
vim.opt.runtimepath:append(fn.expand(test_dir))
vim.opt.packpath:append(fn.expand(test_dir))

-- Install packer
local install_path = test_dir .. '/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    packer_bootstrap = fn.system({
        'git',
        'clone',
        '--depth',
        '1',
        'https://github.com/wbthomason/packer.nvim',
        install_path,
    })
    vim.cmd([[packadd packer.nvim]])
end

-- Setup packer
local packer = require('packer')
packer.init({
    package_root = test_dir .. '/pack',
    compile_path = test_dir .. '/plugin/packer_compiled.lua',
})
packer.startup(function(use)
    -- Packer can manage itself
    use('wbthomason/packer.nvim')

    -- Plugins
    use({
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate',
        requires = { 'nvim-treesitter/playground' },
    })
    use({ 'olimorris/onedarkpro.nvim', branch = 'develop' })

    -- Auto install plugins
    if packer_bootstrap then
        packer.sync()
    end
end)

-- Plugin setup
local ok, treesitter = pcall(require, 'nvim-treesitter.configs')
if ok then
    treesitter.setup({
        highlight = {
            enable = true,
        },
        ensure_installed = { 'bash', 'markdown' },
    })
end

local ok, onedarkpro = pcall(require, 'onedarkpro')
if ok then
    local p = {
        fg = '#abb2bf',
        dark_red = '#be5046',
    }
    onedarkpro.setup({
        theme = 'onedark',
        colors = p,
        ft_highlights = {
            markdown = {
                markdownTSPunctSpecial = { fg = p.dark_red, style = 'bold' },
            },
        },
        ft_highlights_force = true,
    })
    onedarkpro.load()
end
```
Now, as in the GIF, do
1. Open a markdown file such as `~/Desktop/foo.md`
2. Note that `#` symbol is not highlighted in red
3. Run `TSHighlightCapturesUnderCursor` (the reported highlight group is no longer `markdownTSPunctuationSpecial`)

I guess that after https://github.com/neovim/neovim/pull/19931 there are some breaking changes to treesitter highlights (as stated in https://github.com/neovim/neovim/issues/14090#issuecomment-1228444035)

Also relevant: https://github.com/nvim-treesitter/playground/pull/90

![Peek 2022-08-27 17-52](https://user-images.githubusercontent.com/2583971/187047582-80bac621-39fa-45bb-8605-17e0d0d6c130.gif)

**Comment by olimorris** [comment]
So I've just tested this with the following:

```ruby
# Ruby file
def this_is_a_test
  message = "Testing Treesitter"
  puts message
end
```

and with `TSHighlightCapturesUnderCursor`:

<img width="738" alt="Screen Shot 2022-08-28 at 10 35 56@2x" src="https://user-images.githubusercontent.com/9512444/187067556-4b14a581-d501-449f-b4bd-a6ce795e6d78.png">

and when I edit my onedarkpro config to:

```lua
highlights = {
  TSVariable = { bg = "${green}" },
  variable = { bg = "${red}"},
  rubyvariable = { bg = "${purple}"},
}
```

I see:

<img width="461" alt="Screen Shot 2022-08-28 at 10 38 29@2x" src="https://user-images.githubusercontent.com/9512444/187067634-1539be88-9283-4c88-8182-b7a9e890b63a.png">

Which suggests that `TSVariable` is still working.

This is the challenge with nightly, there's always so many moving parts and thinks breaking all the time. I'll keep an eye on this as I work in nightly.

**Comment by petobens** [comment]
Can you try reproducing the following? Start with this minimal.lua file:

```lua
local fn = vim.fn

-- Ignore default config and plugins and define new dirs
local test_dir = '/tmp/nvim-minimal'
vim.opt.runtimepath:remove(fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(fn.expand('~/.local/share/nvim/site'))
vim.opt.runtimepath:append(fn.expand(test_dir))
vim.opt.packpath:append(fn.expand(test_dir))

-- Install packer
local install_path = test_dir .. '/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    packer_bootstrap = fn.system({
        'git',
        'clone',
        '--depth',
        '1',
        'https://github.com/wbthomason/packer.nvim',
        install_path,
    })
    vim.cmd([[packadd packer.nvim]])
end

-- Setup packer
local packer = require('packer')
packer.init({
    package_root = test_dir .. '/pack',
    compile_path = test_dir .. '/plugin/packer_compiled.lua',
})
packer.startup(function(use)
    -- Packer can manage itself
    use('wbthomason/packer.nvim')

    -- Plugins
    use({
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate',
        requires = { 'nvim-treesitter/playground' },
    })
    use({ 'olimorris/onedarkpro.nvim' })

    -- Auto install plugins
    if packer_bootstrap then
        packer.sync()
    end
end)

-- Plugin setup
local ok, treesitter = pcall(require, 'nvim-treesitter.configs')
if ok then
    treesitter.setup({
        highlight = {
            enable = true,
        },
        ensure_installed = { 'python' },
    })
end

local ok, onedarkpro = pcall(require, 'onedarkpro')
if ok then
    local p = {
        dark_red = '#be5046',
    }
    onedarkpro.setup({
        theme = 'onedark',
        colors = p,
        ft_highlights = {
            python = {
                pythonTSConstant = { fg = p.dark_red }, -- Doesn't work (used to)
                -- TSConstant = { fg = p.dark_red }, -- works but is not filetype specific
            },
        },
    })
    onedarkpro.load()
end
```
Then, as in the GIF,
1. Open a python file (such as `foo.py`) with the following content:
```python
A_CONSTANT = 'foo'
```
2. See that the `pythonTSConstant` override to `dark_red` is not applied
3. Comment that line in the minimal.lua file and uncomment the `TS_Constant` line
4. Reopen the `foo.py` now the ft_highlight is correctly applied (but is not filetype specific).

So my point is that under neovim master I believe the `<ft><tree_sitter>` highlight groups (such as `pythonTSConstant`) no longer work.

![dark_red](https://user-images.githubusercontent.com/2583971/187076155-c88b328d-dddd-4d7c-8b49-fdc871b060c6.gif)

**Comment by olimorris** [comment]
I think we're aligned on this. As shown with the `rubyVariable` example above. But as there are no `<ft><treesitter>` highlights in the colorscheme by default then there shouldn't be a material impact for most users.

Is there an issue with this color scheme as a result of the changes on Neovim `HEAD` or do you need to redefine how you're applying your own custom highlights?

**Comment by petobens** [comment]
> Edit: And apologies if I am grossly misunderstanding this problem

No need for an apology and thanks for the patience.

> Do you not just need to redefine how you're applying your own custom highlights as a result of the changes in Neovim?

That's a fair question (I don't have a concrete anwser). From what I can surmise of this https://github.com/neovim/neovim/issues/14090#issuecomment-1228444035 I believe onedarkpro is lacking two things:

1. If I define a `pythonconstant` highlight group that should take precedence over `TSConstant` (currently using `pythonconstant` does nothing)
2. I have no idea now how to override something like a `markdownpunctuation.special` highlight group which I could easily override with `markdownTSPunctSpecial` before (maybe the answer is simply to set `TSPunctSpecial`).

**Comment by petobens** [comment]
One extra comment. If I run something like:
```
:lua vim.api.nvim_set_hl(0, "@constant.python", {fg="Green"})
```
Then I can effectively access the `pythonconstant` highlight group. So I guess my question is how to do this from within Onedark config

**Comment by olimorris** [comment]
> One extra comment. If I run something like:
> 
> ```
> 
> :lua vim.api.nvim_set_hl(0, "@constant.python", {fg="Green"})
> 
> ```
> 
> Then I can effectively access the `pythonconstant` highlight group. So I guess my question is how to do this from within Onedark config

Okay very interesting. And I guess you can't set that in the `highlights` config?

I will definitely look into this as it's a potentially awesome way to replace filetype highlights.

**Comment by petobens** [comment]
>  And I guess you can't set that in the highlights config?

Exactly. For instance while something like the following works:
```
lua vim.api.nvim_set_hl(0, "@punctuation.special.markdown", {fg="Green"})
```
it cannot be added to the `higlights` config (since we have `@` and `.`).

> I will definitely look into this as it's a potentially awesome way to replace filetype highlights.

Awesome! Thanks once again and sorry for all the back and forth.

**Comment by petobens** [comment]
> I will definitely look into this as it's a potentially awesome way to replace filetype highlights.

Indeed something like https://github.com/petobens/dotfiles/commit/e460ac8afca92942134ac5b377781832f824ebb5 fixes both this issue and #67

**Comment by olimorris** [comment]
@petobens - I've just tried:

```lua
highlights = {
      ["@variable.ruby"] = { bg = "${purple}" },
}
```

and I get:

<img width="756" alt="Screen Shot 2022-08-28 at 21 31 17@2x" src="https://user-images.githubusercontent.com/9512444/187093320-457c1ce4-c41e-4107-badf-0ba9b91556b7.png">

**Comment by olimorris** [comment]
Seems like they've added a lot more detail too. Previously:

```lua
ft_highlights = {
  TSFunction = { fg = "${blue}", style = "bold" }
}
```

accomplished what the below now does:

```lua
highlights = {
  ["@function.ruby"] = { fg = "${blue}", style = "bold" },
  ["@variable.ruby"] = { fg = "${blue}", style = "bold" },
}
```

**Comment by petobens** [comment]
Oh neat. I guess that's the way to go. Feel free to close this issue and the other #67 if you deem fit.

**Comment by olimorris** [comment]
I'll close this but leave #67 for now. After you've discovered this then I'm not sure what will happen with filetype highlights as this is a game changer.
