### ISSUE TITLE
Better Markdown treesitter highlights

### ISSUE THREAD

**Issue by mrjones2014** [olimorris/onedarkpro.nvim#81]
Through Treesitter this should be doable.

I'm thinking headings could get a different color, `**Bold**` text could be bold, `*italic*` or `_italic_` could be rendered as italic, backtick `inlilne_code` could be given a background color, etc.

**Comment by olimorris** [comment]
There's some really _sick_ [changes](https://github.com/neovim/neovim/issues/14090#issuecomment-1228444035) to TS highlights recently which are going to make this and filetype highlights, wayyyyy more interesting than they are currently.

I've put all of my ideas down onto a [roadmap](https://github.com/olimorris/onedarkpro.nvim/discussions/82) which I have opened up for discussion.

I see something like you've proposed, above, as something that will fall into the third item. For what it's worth, you could implement this now with:

```lua
-- Assuming you're on Nightly
highlights = {
      ["@text.title.markdown"] = { fg = "${blue}", style = "bold" },
}
```
produces:

<img width="700" alt="Screen Shot 2022-08-29 at 13 56 06@2x" src="https://user-images.githubusercontent.com/9512444/187206073-71f3eb52-5358-4410-8115-3141810c6ea9.png">

**Comment by mrjones2014** [comment]
Amazing, always one step ahead of me with this project 🤣

**Comment by olimorris** [comment]
You're always reading my mind 🤣  so please throw any ideas you have into that roadmap.

**Comment by mmirus** [comment]
:wave: @mrjones2014 If you're interested, here's what I have for Markdown currently:

```lua
local onedarkpro = require('onedarkpro')
local color = require("onedarkpro.lib.color")
local colors = onedarkpro.get_colors(vim.g.onedarkpro_style)

onedarkpro.setup({
  dark_theme = "onedark_vivid",
  colors = {
    onedark_vivid = {
      ...
      comment = color.lighten(colors.gray, 0.90),
    },
  },

...
ft_highlights = {
    markdown = {
      TSTitle = { fg = "${red}" },
      TSPunctSpecial = { fg = "${red}" },
      TSPunctDelimiter = { fg = "${comment}" },
      TSTextReference = { fg = "${blue}" },
      TSURI = { fg = "${comment}" },
      TSLiteral = { fg = "${green}" },
      TSParameter = { fg = "${fg}" },
    },
  }
...
```

I should redo these using the new capture syntax, but they still work.

This is in combination with conceal:

```
" Enable concealing
set conceallevel=2
```

I have mixed feelings about conceal. :man_shrugging: 

Here's the result:

![image](https://user-images.githubusercontent.com/524994/187251180-ea5f03d2-4ba3-4c67-beeb-90365de5c197.png)

To be honest, I'm not sure what's styling the bold and italic text. I'm not doing that in my custom highlights, so maybe this theme or one of my markdown-related plugins? I have `jxnblk/vim-mdx-js`, `SidOfc/mkdx`, and `iamcco/markdown-preview.nvim` installed (unlikely to be the last one).

**Comment by mrjones2014** [comment]
>I have mixed feelings about conceal. 🤷‍♂️

I personally _hate_ conceal but I'll definitely copy your highlights!

**Comment by mmirus** [comment]
Yeah, it's something I only discovered recently and I'm not sure if I'll keep using it. I feel like it has potential, but I might need to learn how to exercise more control over it (if possible) so I can change or disable parts of it I don't like.
