### ISSUE TITLE
Nvimtree directories in purple, but the screenshots show that it should be blue.

### ISSUE THREAD

**Issue by CleoMenezesJr** [olimorris/onedarkpro.nvim#87]
**System information**
- OS: Fedora Silverblue 37 (Linux)
- Neovim version (`nvim --version`): NVIM v0.7.0

![image](https://user-images.githubusercontent.com/54215258/189265184-065cf10c-a513-4632-a485-4e5c6d92d699.png)

**Comment by olimorris** [comment]
Can you post your config please, as the issue template asks for and tty with th minimal config? Saves us both time.

**Comment by olimorris** [comment]
Also, I think this is default behaviour as per `nvim_tree.lua`. You'll need to manually override the highlight groups to blue.
