### ISSUE TITLE
Config tips: nicer floating and unfocused windows

### ISSUE THREAD

**Issue by mmirus** [olimorris/onedarkpro.nvim#89]
I spent a little time tweaking my theme config today, and thought I'd share a few things that added a little extra polish for me.

These might be good candidates for improving the default config (in some form), or just helpful for other users to selectively include themselves!

## Match the floating window border background to the contents background

This applies to things like cmp or LSP hover definitions, when you have borders enabled for them.

**Before**

![image](https://user-images.githubusercontent.com/524994/192109115-ac42e498-13cb-4ab8-842e-4726d239ae00.png)

**After**

![image](https://user-images.githubusercontent.com/524994/192110765-1414ff49-c592-4492-8fc7-6c32bfb49bf1.png)

Or with the `solid` border type (my current preference):

![image](https://user-images.githubusercontent.com/524994/192109189-149ae720-619e-401e-aeaf-c61fd5b48350.png)

**How**

Incorporate this into your existing config:

```lua
local onedarkpro = require("onedarkpro")
local color = require("onedarkpro.lib.color")
local colors = onedarkpro.get_colors(vim.g.onedarkpro_style)

onedarkpro.setup({
  colors = {
    dark_gray = color.darken(colors.bg, 0.85),
  },
  highlights = {
    -- Make background of border on floating windows match background of contents
    FloatBorder = { bg = "${dark_gray}", fg = "${gray}" },
  }
}
```

## Improve `window_unfocused_color`

When `window_unfocused_color = true` is in the theme options, there are a couple things that don't look quite as nice as they could:

1. When telescope is open, the non-focused panes have the lighter, non-focused-window background color; only the input field has the dark, focused-window background color
2. The line number and sign column backgrounds don't change in non-focused windows

**Before**

![image](https://user-images.githubusercontent.com/524994/192109435-5067fb07-89c8-484b-b3d0-26e59df45166.png)

☝️ note the Telescope window backgrounds use the light, non-focused color, except the prompt

![image](https://user-images.githubusercontent.com/524994/192109477-a7e71d56-30a0-4e35-b099-aadff50fe723.png)

️☝️ note the number/sign column background color in the inactive window still has the active window colors, and doesn't match the body of the unfocused window

**After**

![image](https://user-images.githubusercontent.com/524994/192110941-25d621c8-c45d-40c0-a5bb-b896c66ac08e.png)

☝️ note the Telescope window backgrounds all now use the dark, focused color

![image](https://user-images.githubusercontent.com/524994/192110699-1457b9c7-fbcb-4e81-b3ee-f542c8711c15.png)

️☝️ note the number/sign column background color in the inactive window now matches the colors of the inactive window's body

**How**

First, add these to your highlights:

```lua
local onedarkpro = require("onedarkpro")
onedarkpro.setup({
  options = {
    window_unfocused_color = true, -- don't forget to enable this!
  },
  highlights = {
    -- Fix a few backgrounds when window_unfocused_color is enabled
    -- BUG: SignColumn doesn't get overridden for the current line in the inactive window
    CursorLineNrNC = { bg = "${color_column}", fg = "${gray}" },
    SignColumnNC = { bg = "${color_column}", fg = "${gray}" },
    LineNrNC = { bg = "${color_column}", fg = "${gray}" },
    TelescopeNormal = { bg = "${bg}", fg = "${fg}" },
    TelescopeBorder = { bg = "${bg}", fg = "${gray}" },
  },
}
```

Second, add this somewhere in your neovim config (must be in a lua file or block):

```lua
-- Set highlights for the gutter in non-focused windows
local HighlightGutterNC = vim.api.nvim_create_augroup("HighlightGutterNC", { clear = true })
vim.api.nvim_create_autocmd("WinLeave", {
  group = HighlightGutterNC,
  pattern = "*.*", -- This prevents the command from running on Telescope windows
  command = "set winhighlight=CursorLineNr:CursorLineNrNC,SignColumn:SignColumnNC,LineNr:LineNrNC",
})
vim.api.nvim_create_autocmd("WinEnter", {
  group = HighlightGutterNC,
  pattern = "*.*", -- This prevents the command from running on Telescope windows
  command = "set winhighlight=",
})
```

**Comment by olimorris** [comment]
These are some amazing improvement to the theme.

The first one is a must. Would you be willing to put into a pull request across all of the themes? I suspect `onelight` might need a little bit of testing but would be a huge improvement.

Regarding the second improvement, whilst the autocommands are very opinionated, if someone has `window_unfocused_color` set to `true` then I think it would be acceptable to include. What are your thoughts?

**Comment by mmirus** [comment]
Glad you like the changes! Here's a PR for the float border colors: https://github.com/olimorris/onedarkpro.nvim/pull/90

LMK if you see any errors.

I think the autocommands are fine if someone has the option enabled, but note that I haven't used my editor much since adding them, so we may find they need to be improved.

One thing you might be able to help with: is there a better pattern we can use than `*.*` to exclude Telescope's windows from the commands?

**Comment by olimorris** [comment]
> One thing you might be able to help with: is there a better pattern we can use than `*.*` to exclude Telescope's windows from the commands?

Could you do a filetype check and exclude `TelescopePrompt`?

**Comment by mmirus** [comment]
After a tragically long amount of time, I ended up with this for the unfocused window changes. If it looks good to you, I can try to do a PR soon that incorporates the highlight groups and autocommands into the theme.

```lua
local onedarkpro = require("onedarkpro")

onedarkpro.setup({
  options = {
    window_unfocused_color = true,
  },
  highlights = {
    CursorLineNrNC = { bg = "${color_column}", fg = "${gray}" },
    SignColumnNC = { bg = "${color_column}", fg = "${gray}" },
    LineNrNC = { bg = "${color_column}", fg = "${gray}" },
    TelescopeNormal = { bg = "${bg}", fg = "${fg}" },
    TelescopeBorder = { bg = "${bg}", fg = "${gray}" },
  },
})

vim.cmd("colorscheme onedarkpro")

-- Set highlights for the gutter in non-focused windows
local NCHighlights = "CursorLineNr:CursorLineNrNC,SignColumn:SignColumnNC,LineNr:LineNrNC"
local HighlightGutterNC = vim.api.nvim_create_augroup("HighlightGutterNC", { clear = true })
vim.api.nvim_create_autocmd("WinLeave", {
  group = HighlightGutterNC,
  command = "set winhighlight=" .. NCHighlights,
})
vim.api.nvim_create_autocmd("WinEnter", {
  group = HighlightGutterNC,
  command = "set winhighlight-=" .. NCHighlights,
})

```

As it turns out there were some Telescope winhighlight settings already, which my `WinEnter` autocommand was deleting previously. The `-=` here prevents that. This more generalized solution is better than targeting Telescope specifically, I think.

I would prefer to do a `+=` in the `WinLeave` autocommand to append to any existing value, but I got an error every time I tried something like that.

**Comment by olimorris** [comment]
Groups and autocommands look amazing and happy to accept a pull request. Heck, I might even start using this feature myself 😆 .

A couple of thoughts:

- Might be nice to give the group names something like "OneDarkPro_HighlightGutterNC" or something. That way anyone debugging will know where they've come from
- The autocommands would probably live nicely in the `main.lua`. Could copy what I did with the `terminal_colors` config option

**Comment by mmirus** [comment]
Thanks for the suggestions--very helpful. Here's the PR: https://github.com/olimorris/onedarkpro.nvim/pull/92

**Comment by olimorris** [comment]
Amazing. Thanks so much! Really excited to use this feature once again!

**Comment by mmirus** [comment]
No problem! Glad to be able to contribute something that makes your experience better--usually it's the other way around! :grin:
