### ISSUE TITLE
Pmenu color config  does not take effect

### ISSUE THREAD

**Issue by roadupcc** [olimorris/onedarkpro.nvim#91]
I added these options, but they don't seem to be all in effect, is there a bug in my configuration?
![image](https://user-images.githubusercontent.com/18000037/192172311-c934debd-9007-442e-b5a4-dd4e4afdc07b.png)

**Comment by olimorris** [comment]
I suspect another plugin is overwriting them. If you follow the instructions in the bug report to load the `minimal.lua` file, are you seeing the same issue?

I've just tried changing the `Pmenu` and it worked as intended.

**Comment by olimorris** [comment]
@roadupcc - Have you had a chance to test this yet?

**Comment by roadupcc** [comment]
> @roadupcc - Have you had a chance to test this yet?

Ohhhh, I'm sorry, I forgot this issue.
I test this `minimal.lua`, it looks like work good. Maybe some plugin have a modified.

Thank you for you contribution, it's a good theme.

**Comment by roadupcc** [comment]
> @roadupcc - Have you had a chance to test this yet?

Ohhhh, I'm sorry, I forgot this issue.
I test this `minimal.lua`, it looks like work good. Maybe some plugin have a modified.

Thank you for you contribution, it's a good theme.
