### ISSUE TITLE
No idea how to set custom cursorlinenr

### ISSUE THREAD

**Issue by amaanq** [olimorris/onedarkpro.nvim#93]
### Issue/Question/Feature request

I want the cursorlinenr's fg to be blue not purple, however I can set this but this unsets the bg and style. I have no idea how to retain the configs style. for reference...

```lua
local colors = require("onedarkpro").get_colors(vim.g.onedarkpro_theme);

require("onedarkpro").setup({
    dark_theme = "onedark_vivid",
    highlights = {
        CursorLineNr = {
            bg = config.options.cursorline and theme.generated.cursorline or theme.palette.bg,
            fg = colors.blue,
            style = config.options.bold
        },
    },
});
```

is what I have, the bg and style lines don't work, any help appreciated!

**Comment by mmirus** [comment]
Hey, @amaanq! Does this work for you?

```lua
CursorLineNr = {
  bg = "${cursorline}",
  fg = "${blue}",
  style = "bold",
}
```

PS - cool to see someone using the vivid option besides me!

**Comment by amaanq** [comment]
perfect! thank you :) and I do love the vivid theme much more than the regular, I'm a bit new to neovim and configuring with lua files in general, how does the ${var} work? just on any variable thats in the theme?

**Comment by amaanq** [comment]
also, i just installed nvim-notify since its supported, but I might have an issue here...getting ```Highlight group 'Normal' has no background highlight
Please provide an RGB hex value or highlight group with a background value for 'background_colour' option.
This is the colour that will be used for 100% transparency.``` on launch. Thanks and sorry again! :)

**Comment by olimorris** [comment]
> perfect! thank you :) and I do love the vivid theme much more than the regular, I'm a bit new to neovim and configuring with lua files in general, how does the ${var} work? just on any variable thats in the theme?

It's something that iz custom to this theme; not Neovim specifically. I'd recommend reading the `README`, thoroughly as we break out lots of examples on how to customise highlight groups

**Comment by olimorris** [comment]
> also, i just installed nvim-notify since its supported, but I might have an issue here...getting ```Highlight group 'Normal' has no background highlight
> 
> Please provide an RGB hex value or highlight group with a background value for 'background_colour' option.
> 
> This is the colour that will be used for 100% transparency.``` on launch. Thanks and sorry again! :)
> 
> 
> 
> EDIT: this is triggered when transparency is set to true, turning it off for now

Could you file this as a separate bug and I can investigate?
