### ISSUE TITLE
[Bug]: Error loading when cache exists

### ISSUE THREAD

**Issue by mmirus** [olimorris/onedarkpro.nvim#97]
### Your OneDarkPro config

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/onedarkpro"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
    install_plugins = true
end

local packer = require("packer")

packer.init({
    package_root = test_dir .. "/pack",
    compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

-- install plugins
packer.startup(function(use)
    use("wbthomason/packer.nvim")
    use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
    use("olimorris/onedarkpro.nvim")

    -- Add any additional plugins here

    if install_plugins then
        packer.sync()
    end
end)

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
    treesitter.setup({
        ensure_installed = "all",
        ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
        highlight = { enable = true },
    })
end

-- setup onedarkpro
local ok, onedarkpro = pcall(require, "onedarkpro")
if ok then
    onedarkpro.setup({
	    caching = true
      -- Your onedarkpro config here
    })
    vim.cmd("colorscheme onedarkpro")
end
```

### Error messages

```
Error detected while processing /home/mmirus/minimal.lua:
E5113: Error while calling lua chunk: /home/mmirus/minimal.lua:57: Vim(lua):E5108: Error executing lua ...acker/start/onedark
pro.nvim/lua/onedarkpro/lib/cache.lua:101: Vim(luafile):E5112: Error while creating lua chunk: /home/mmirus/.cache/nvim/oneda
rkpro/onedark.lua:7: '=' expected near 'AerialClass'
stack traceback:
        [C]: in function 'cmd'
        ...acker/start/onedarkpro.nvim/lua/onedarkpro/lib/cache.lua:101: in function 'load'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        /home/mmirus/minimal.lua:57: in main chunk
stack traceback:
        [C]: in function 'cmd'
        /home/mmirus/minimal.lua:57: in main chunk
```

### Expected

Theme loads successfully

### Actual

Error occurs and theme is not applied

### Reproduce the bug

Steps to reproduce:

1. Set `caching = true` in theme setup
2. Run `:OnedarkproCache`
3. Restart neovim

### Final checks

- [X] I have made sure this is not a duplicate issue
- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`

**Comment by olimorris** [comment]
Great spot thanks!

Really obvious miss on my part and I'd been staring at a test file for a few hours which had the error in. Basically I didn't wrap the vim commands in a `vim.cmd` call.

**Comment by mmirus** [comment]
Thanks! Heads up that now if I run the cache command from the minimal config, I end up with this after restarting:

![image](https://user-images.githubusercontent.com/524994/193691380-cb875b92-a2d7-430b-a7a8-fa6e8821a10e.png)

If I run it from my full config, I don't experience that, so I'm not sure what's going on.

LMK if you'd like me to make a new issue.

**Comment by olimorris** [comment]
I've just tried it and also get this error but wondering if we've hit a rogue edge case with the `minimal.lua` file. If I pair back my regular config down to just `caching = true`, it works

**Comment by mmirus** [comment]
Could be! I haven't had a chance to look into it further. Just noticed another issue with caching, though, that I will make a new issue for.
