### ISSUE TITLE
[Feature]: Command to show all available colors in the palette as hex codes

### ISSUE THREAD

**Issue by mrjones2014** [olimorris/onedarkpro.nvim#99]
### Issue/Question/Enhancement

Trying to write custom highlight groups for certain plugins. It would be cool to be able to do something like: `:Onedarkpro colors`

Which would output the palette into a temporary, unmodifiable, scratch buffer in a format like

```
colors.blue                 #XXXXXX
colors.gray                 #XXXXXX
colors.bg_statusline        #XXXXXX
...
```

So then if you're using a [colorizer plugin](https://github.com/norcalli/nvim-colorizer.lua) you can see what the actual colors look like.

**Comment by mrjones2014** [comment]
For context, I'm trying to figure out what color is being used for my statusline's blank space, so I can set the cmdline popup from [noice.nvim](https://github.com/folke/noice.nvim) to the same color.

**Comment by olimorris** [comment]
This should be pretty easy to do actually as we have a global variable `vim.g.onedarkpro_colors` available which outputs:

```lua

{
  bg = "#282c34",
  bg_statusline = "#33373E",
  black = "#282c34",
  blue = "#61afef",
  brackets = "#abb2bf",
  bufferline_text_focus = "#949aa2",
  color_column = "#2E323A",
  cursorline = "#2e323b",
  cyan = "#56b6c2",
  diff_add = "#003e4a",
  diff_delete = "#501b20",
  diff_text = "#005869",
  fg = "#abb2bf",
  fg_gutter = "#696B71",
  float_bg = "#22252C",
  ghost_text = "#555961",
  gray = "#5c6370",
  green = "#98c379",
  highlight = "#e2be7d",
  indentline = "#3c414d",
  light = false,
  name = "onedark",
  none = "NONE",
  orange = "#d19a66",
  purple = "#c678dd",
  red = "#e06c75",
  selection = "#53565D",
  statusline_bg = "#2e323b",
  telescope_prompt = "#2e323a",
  telescope_results = "#21252d",
  vim = "#81b766",
  virtual_text_error = "#E9989E",
  virtual_text_hint = "#78C5CE",
  virtual_text_information = "#90C7F4",
  virtual_text_warning = "#EDD3A3",
  white = "#abb2bf",
  yellow = "#e5c07b"
}
```

It even includes the custom colors you define. Anything you can throw my way regarding creating scratch buffers?

**Comment by mrjones2014** [comment]
I'm setting one up for the 1Password sidebar in [op/sidebar/init.lua](https://github.com/mrjones2014/op.nvim/blob/master/lua/op/sidebar/init.lua) which uses some utilities set up in [op/buffers.lua](https://github.com/mrjones2014/op.nvim/blob/master/lua/op/buffers.lua).

But your use case should be a quite a bit simpler as you just need to make a buffer, not a "sidebar" so you shouldn't need any of the autocmd stuff or window movement stuff I'm doing in there.

You should pretty much just need to do something like (pseudo-code):

```lua
-- do your thing to generate the lines of text
local lines = {}
-- params are: listed, scratch. see :h nvim_create_buf
local buf = vim.api.nvim_create_buf(true, true)
-- see :h nvim_buf_set_lines, tldr using range 0,-1 means "the whole buffer"
vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
vim.api.nvim_buf_set_option(buf, 'modifiable', false)
-- set a unique filetype so I can configure colorizer.nvim to attach to it automatically
vim.api.nvim_buf_set_option(buf, 'filetype', 'OnedarkproColors')
```

**Comment by mrjones2014** [comment]
I can help out with the buffer stuff if you put a PR up. I had to mess around with the window/buffer API's _a lot_ to get the 1Password sidebar working lol

**Comment by olimorris** [comment]
Oh this is great. Thank you.

I'll finish it off tonight and merge.

**Comment by olimorris** [comment]
Please run `:OnedarkproColors` and let me know what you think.

**Comment by mrjones2014** [comment]
That looks great, my one nitpick would be, could we align the colors into columns so I can use visual-block mode to select them, e.g.

```
green                    = "#89ca78"
telescope_prompt         = "#101010"
telescope_results        = "#000000"
none                     = "NONE"
virtual_text_hint        = "#55C8D1"
virtual_text_information = "#90C7F4"
virtual_text_warning     = "#EDD3A3"
virtual_text_error       = "#F48B9A"
```

**Comment by olimorris** [comment]
Proper nitpick that 😉 . Let me know what you think now.

**Comment by mrjones2014** [comment]
That looks perfect, thanks for the quick turnaround on this! This will help a ton when trying to theme new plugins.

I might submit a PR for a `noice.nvim` plugin soon, once I figure out all the details 😉

**Comment by mrjones2014** [comment]
One more nitpick, can you either filter out or sort to the top the two items: `none` and `name`? Since they don't have actual colors associated with them.

**Comment by olimorris** [comment]
> One more nitpick, can you either filter out or sort to the top the items: `none`, `name`, and `light` (a boolean)? Since they don't have actual colors associated with them.

...and done. Will tidy up the code later.

**Comment by mrjones2014** [comment]
Amazing thanks for your quick work on this, helps a lot 👍
